// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"database/sql"
)

const adjustManualBalance = `-- name: AdjustManualBalance :one
UPDATE accounts SET balance_cents = balance_cents + ?1, balance_at = ?2, updated_at = ?2
WHERE id = ?3 AND is_manual = 1
RETURNING balance_cents
`

type AdjustManualBalanceParams struct {
	Delta int64         `json:"delta"`
	Now   sql.NullInt64 `json:"now"`
	ID    int64         `json:"id"`
}

// Manual accounts only: a manual transaction moved money in or out.
func (q *Queries) AdjustManualBalance(ctx context.Context, arg AdjustManualBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adjustManualBalance, arg.Delta, arg.Now, arg.ID)
	var balance_cents int64
	err := row.Scan(&balance_cents)
	return balance_cents, err
}

const clearAccountExternal = `-- name: ClearAccountExternal :exec
UPDATE accounts SET external_id = NULL, updated_at = ? WHERE id = ?
`

type ClearAccountExternalParams struct {
	UpdatedAt int64 `json:"updated_at"`
	ID        int64 `json:"id"`
}

func (q *Queries) ClearAccountExternal(ctx context.Context, arg ClearAccountExternalParams) error {
	_, err := q.db.ExecContext(ctx, clearAccountExternal, arg.UpdatedAt, arg.ID)
	return err
}

const countAccountTransactions = `-- name: CountAccountTransactions :one
SELECT COUNT(*) FROM transactions WHERE account_id = ?
`

func (q *Queries) CountAccountTransactions(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccountTransactions, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    household_id, connection_id, institution_id, external_id, institution_name, provider_name,
    name, mask, type, currency, balance_cents, available_cents, balance_at, status,
    review_candidate_id, is_manual, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, household_id, connection_id, institution_id, external_id, institution_name, provider_name, name, mask, type, currency, balance_cents, available_cents, balance_at, status, review_candidate_id, include_in_net_worth, hidden, owner_user_id, is_manual, created_at, updated_at, builtin, color, color_source
`

type CreateAccountParams struct {
	HouseholdID       int64          `json:"household_id"`
	ConnectionID      sql.NullInt64  `json:"connection_id"`
	InstitutionID     sql.NullInt64  `json:"institution_id"`
	ExternalID        sql.NullString `json:"external_id"`
	InstitutionName   string         `json:"institution_name"`
	ProviderName      string         `json:"provider_name"`
	Name              string         `json:"name"`
	Mask              string         `json:"mask"`
	Type              string         `json:"type"`
	Currency          string         `json:"currency"`
	BalanceCents      int64          `json:"balance_cents"`
	AvailableCents    sql.NullInt64  `json:"available_cents"`
	BalanceAt         sql.NullInt64  `json:"balance_at"`
	Status            string         `json:"status"`
	ReviewCandidateID sql.NullInt64  `json:"review_candidate_id"`
	IsManual          int64          `json:"is_manual"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.HouseholdID,
		arg.ConnectionID,
		arg.InstitutionID,
		arg.ExternalID,
		arg.InstitutionName,
		arg.ProviderName,
		arg.Name,
		arg.Mask,
		arg.Type,
		arg.Currency,
		arg.BalanceCents,
		arg.AvailableCents,
		arg.BalanceAt,
		arg.Status,
		arg.ReviewCandidateID,
		arg.IsManual,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ConnectionID,
		&i.InstitutionID,
		&i.ExternalID,
		&i.InstitutionName,
		&i.ProviderName,
		&i.Name,
		&i.Mask,
		&i.Type,
		&i.Currency,
		&i.BalanceCents,
		&i.AvailableCents,
		&i.BalanceAt,
		&i.Status,
		&i.ReviewCandidateID,
		&i.IncludeInNetWorth,
		&i.Hidden,
		&i.OwnerUserID,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Builtin,
		&i.Color,
		&i.ColorSource,
	)
	return i, err
}

const createBuiltinAccount = `-- name: CreateBuiltinAccount :one
INSERT INTO accounts (household_id, name, type, currency, balance_cents, balance_at, status, is_manual, builtin, created_at, updated_at)
VALUES (?, ?, ?, 'USD', 0, ?, 'active', 1, ?, ?, ?)
RETURNING id, household_id, connection_id, institution_id, external_id, institution_name, provider_name, name, mask, type, currency, balance_cents, available_cents, balance_at, status, review_candidate_id, include_in_net_worth, hidden, owner_user_id, is_manual, created_at, updated_at, builtin, color, color_source
`

type CreateBuiltinAccountParams struct {
	HouseholdID int64         `json:"household_id"`
	Name        string        `json:"name"`
	Type        string        `json:"type"`
	BalanceAt   sql.NullInt64 `json:"balance_at"`
	Builtin     string        `json:"builtin"`
	CreatedAt   int64         `json:"created_at"`
	UpdatedAt   int64         `json:"updated_at"`
}

func (q *Queries) CreateBuiltinAccount(ctx context.Context, arg CreateBuiltinAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createBuiltinAccount,
		arg.HouseholdID,
		arg.Name,
		arg.Type,
		arg.BalanceAt,
		arg.Builtin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ConnectionID,
		&i.InstitutionID,
		&i.ExternalID,
		&i.InstitutionName,
		&i.ProviderName,
		&i.Name,
		&i.Mask,
		&i.Type,
		&i.Currency,
		&i.BalanceCents,
		&i.AvailableCents,
		&i.BalanceAt,
		&i.Status,
		&i.ReviewCandidateID,
		&i.IncludeInNetWorth,
		&i.Hidden,
		&i.OwnerUserID,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Builtin,
		&i.Color,
		&i.ColorSource,
	)
	return i, err
}

const createConnection = `-- name: CreateConnection :one

INSERT INTO connections (household_id, provider, name, secret_enc, created_at, next_sync_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, household_id, provider, name, secret_enc, status, last_error, last_sync_at, synced_through, next_sync_at, requests_day, requests_count, created_at
`

type CreateConnectionParams struct {
	HouseholdID int64         `json:"household_id"`
	Provider    string        `json:"provider"`
	Name        string        `json:"name"`
	SecretEnc   []byte        `json:"secret_enc"`
	CreatedAt   int64         `json:"created_at"`
	NextSyncAt  sql.NullInt64 `json:"next_sync_at"`
}

// ---- connections ----
func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnection,
		arg.HouseholdID,
		arg.Provider,
		arg.Name,
		arg.SecretEnc,
		arg.CreatedAt,
		arg.NextSyncAt,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Provider,
		&i.Name,
		&i.SecretEnc,
		&i.Status,
		&i.LastError,
		&i.LastSyncAt,
		&i.SyncedThrough,
		&i.NextSyncAt,
		&i.RequestsDay,
		&i.RequestsCount,
		&i.CreatedAt,
	)
	return i, err
}

const dailyAccountTotals = `-- name: DailyAccountTotals :many
SELECT t.account_id, t.date, CAST(SUM(t.amount_cents) AS INTEGER) AS total
FROM transactions t
WHERE t.household_id = ? AND t.provisional = 0
GROUP BY t.account_id, t.date
`

type DailyAccountTotalsRow struct {
	AccountID int64  `json:"account_id"`
	Date      string `json:"date"`
	Total     int64  `json:"total"`
}

// Per-account daily sums of settled transactions, used to rebuild balances before the first
// snapshot. Provisional rows (manual pending entries, email alerts on synced accounts) are left
// out: the bank balance doesn't include them yet.
func (q *Queries) DailyAccountTotals(ctx context.Context, householdID int64) ([]DailyAccountTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, dailyAccountTotals, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyAccountTotalsRow
	for rows.Next() {
		var i DailyAccountTotalsRow
		if err := rows.Scan(&i.AccountID, &i.Date, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ? AND household_id = ?
`

type DeleteAccountParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, arg.ID, arg.HouseholdID)
	return err
}

const deleteAccountLogo = `-- name: DeleteAccountLogo :exec
DELETE FROM account_logos WHERE account_id = ?
`

func (q *Queries) DeleteAccountLogo(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccountLogo, accountID)
	return err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections WHERE id = ? AND household_id = ?
`

type DeleteConnectionParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteConnection, arg.ID, arg.HouseholdID)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const disconnectConnectionAccounts = `-- name: DisconnectConnectionAccounts :exec
UPDATE accounts SET status = 'disconnected', updated_at = ?
WHERE connection_id = ? AND status IN ('active', 'review')
`

type DisconnectConnectionAccountsParams struct {
	UpdatedAt    int64         `json:"updated_at"`
	ConnectionID sql.NullInt64 `json:"connection_id"`
}

func (q *Queries) DisconnectConnectionAccounts(ctx context.Context, arg DisconnectConnectionAccountsParams) error {
	_, err := q.db.ExecContext(ctx, disconnectConnectionAccounts, arg.UpdatedAt, arg.ConnectionID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, household_id, connection_id, institution_id, external_id, institution_name, provider_name, name, mask, type, currency, balance_cents, available_cents, balance_at, status, review_candidate_id, include_in_net_worth, hidden, owner_user_id, is_manual, created_at, updated_at, builtin, color, color_source FROM accounts WHERE id = ? AND household_id = ?
`

type GetAccountParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, arg.ID, arg.HouseholdID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ConnectionID,
		&i.InstitutionID,
		&i.ExternalID,
		&i.InstitutionName,
		&i.ProviderName,
		&i.Name,
		&i.Mask,
		&i.Type,
		&i.Currency,
		&i.BalanceCents,
		&i.AvailableCents,
		&i.BalanceAt,
		&i.Status,
		&i.ReviewCandidateID,
		&i.IncludeInNetWorth,
		&i.Hidden,
		&i.OwnerUserID,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Builtin,
		&i.Color,
		&i.ColorSource,
	)
	return i, err
}

const getAccountByExternal = `-- name: GetAccountByExternal :one
SELECT id, household_id, connection_id, institution_id, external_id, institution_name, provider_name, name, mask, type, currency, balance_cents, available_cents, balance_at, status, review_candidate_id, include_in_net_worth, hidden, owner_user_id, is_manual, created_at, updated_at, builtin, color, color_source FROM accounts WHERE connection_id = ? AND external_id = ?
`

type GetAccountByExternalParams struct {
	ConnectionID sql.NullInt64  `json:"connection_id"`
	ExternalID   sql.NullString `json:"external_id"`
}

func (q *Queries) GetAccountByExternal(ctx context.Context, arg GetAccountByExternalParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByExternal, arg.ConnectionID, arg.ExternalID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ConnectionID,
		&i.InstitutionID,
		&i.ExternalID,
		&i.InstitutionName,
		&i.ProviderName,
		&i.Name,
		&i.Mask,
		&i.Type,
		&i.Currency,
		&i.BalanceCents,
		&i.AvailableCents,
		&i.BalanceAt,
		&i.Status,
		&i.ReviewCandidateID,
		&i.IncludeInNetWorth,
		&i.Hidden,
		&i.OwnerUserID,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Builtin,
		&i.Color,
		&i.ColorSource,
	)
	return i, err
}

const getAccountLogo = `-- name: GetAccountLogo :one
SELECT l.mime, l.data, l.updated_at FROM account_logos l JOIN accounts a ON a.id = l.account_id
WHERE l.account_id = ? AND a.household_id = ?
`

type GetAccountLogoParams struct {
	AccountID   int64 `json:"account_id"`
	HouseholdID int64 `json:"household_id"`
}

type GetAccountLogoRow struct {
	Mime      string `json:"mime"`
	Data      []byte `json:"data"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) GetAccountLogo(ctx context.Context, arg GetAccountLogoParams) (GetAccountLogoRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountLogo, arg.AccountID, arg.HouseholdID)
	var i GetAccountLogoRow
	err := row.Scan(&i.Mime, &i.Data, &i.UpdatedAt)
	return i, err
}

const getBuiltinAccount = `-- name: GetBuiltinAccount :one

SELECT id, household_id, connection_id, institution_id, external_id, institution_name, provider_name, name, mask, type, currency, balance_cents, available_cents, balance_at, status, review_candidate_id, include_in_net_worth, hidden, owner_user_id, is_manual, created_at, updated_at, builtin, color, color_source FROM accounts WHERE household_id = ? AND builtin = ?
`

type GetBuiltinAccountParams struct {
	HouseholdID int64  `json:"household_id"`
	Builtin     string `json:"builtin"`
}

// ---- built-in accounts ----
func (q *Queries) GetBuiltinAccount(ctx context.Context, arg GetBuiltinAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getBuiltinAccount, arg.HouseholdID, arg.Builtin)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ConnectionID,
		&i.InstitutionID,
		&i.ExternalID,
		&i.InstitutionName,
		&i.ProviderName,
		&i.Name,
		&i.Mask,
		&i.Type,
		&i.Currency,
		&i.BalanceCents,
		&i.AvailableCents,
		&i.BalanceAt,
		&i.Status,
		&i.ReviewCandidateID,
		&i.IncludeInNetWorth,
		&i.Hidden,
		&i.OwnerUserID,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Builtin,
		&i.Color,
		&i.ColorSource,
	)
	return i, err
}

const getConnection = `-- name: GetConnection :one
SELECT id, household_id, provider, name, secret_enc, status, last_error, last_sync_at, synced_through, next_sync_at, requests_day, requests_count, created_at FROM connections WHERE id = ? AND household_id = ?
`

type GetConnectionParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnection, arg.ID, arg.HouseholdID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Provider,
		&i.Name,
		&i.SecretEnc,
		&i.Status,
		&i.LastError,
		&i.LastSyncAt,
		&i.SyncedThrough,
		&i.NextSyncAt,
		&i.RequestsDay,
		&i.RequestsCount,
		&i.CreatedAt,
	)
	return i, err
}

const getConnectionByID = `-- name: GetConnectionByID :one
SELECT id, household_id, provider, name, secret_enc, status, last_error, last_sync_at, synced_through, next_sync_at, requests_day, requests_count, created_at FROM connections WHERE id = ?
`

func (q *Queries) GetConnectionByID(ctx context.Context, id int64) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnectionByID, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Provider,
		&i.Name,
		&i.SecretEnc,
		&i.Status,
		&i.LastError,
		&i.LastSyncAt,
		&i.SyncedThrough,
		&i.NextSyncAt,
		&i.RequestsDay,
		&i.RequestsCount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByExternal = `-- name: GetTransactionByExternal :one

SELECT id, pending FROM transactions WHERE account_id = ? AND external_id = ?
`

type GetTransactionByExternalParams struct {
	AccountID  int64          `json:"account_id"`
	ExternalID sql.NullString `json:"external_id"`
}

type GetTransactionByExternalRow struct {
	ID      int64 `json:"id"`
	Pending int64 `json:"pending"`
}

// ---- transactions (sync side) ----
func (q *Queries) GetTransactionByExternal(ctx context.Context, arg GetTransactionByExternalParams) (GetTransactionByExternalRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByExternal, arg.AccountID, arg.ExternalID)
	var i GetTransactionByExternalRow
	err := row.Scan(&i.ID, &i.Pending)
	return i, err
}

const insertSyncEvent = `-- name: InsertSyncEvent :exec

INSERT INTO sync_events (connection_id, at, kind, account_id, message) VALUES (?, ?, ?, ?, ?)
`

type InsertSyncEventParams struct {
	ConnectionID int64         `json:"connection_id"`
	At           int64         `json:"at"`
	Kind         string        `json:"kind"`
	AccountID    sql.NullInt64 `json:"account_id"`
	Message      string        `json:"message"`
}

// ---- sync events ----
func (q *Queries) InsertSyncEvent(ctx context.Context, arg InsertSyncEventParams) error {
	_, err := q.db.ExecContext(ctx, insertSyncEvent,
		arg.ConnectionID,
		arg.At,
		arg.Kind,
		arg.AccountID,
		arg.Message,
	)
	return err
}

const insertSyncedTransaction = `-- name: InsertSyncedTransaction :one
INSERT INTO transactions (
    household_id, account_id, external_id, source, date, amount_cents, description, payee, memo,
    pending, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertSyncedTransactionParams struct {
	HouseholdID int64          `json:"household_id"`
	AccountID   int64          `json:"account_id"`
	ExternalID  sql.NullString `json:"external_id"`
	Source      string         `json:"source"`
	Date        string         `json:"date"`
	AmountCents int64          `json:"amount_cents"`
	Description string         `json:"description"`
	Payee       string         `json:"payee"`
	Memo        string         `json:"memo"`
	Pending     int64          `json:"pending"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) InsertSyncedTransaction(ctx context.Context, arg InsertSyncedTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSyncedTransaction,
		arg.HouseholdID,
		arg.AccountID,
		arg.ExternalID,
		arg.Source,
		arg.Date,
		arg.AmountCents,
		arg.Description,
		arg.Payee,
		arg.Memo,
		arg.Pending,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAccountLogoTimes = `-- name: ListAccountLogoTimes :many
SELECT l.account_id, l.updated_at FROM account_logos l JOIN accounts a ON a.id = l.account_id WHERE a.household_id = ?
`

type ListAccountLogoTimesRow struct {
	AccountID int64 `json:"account_id"`
	UpdatedAt int64 `json:"updated_at"`
}

func (q *Queries) ListAccountLogoTimes(ctx context.Context, householdID int64) ([]ListAccountLogoTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountLogoTimes, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountLogoTimesRow
	for rows.Next() {
		var i ListAccountLogoTimesRow
		if err := rows.Scan(&i.AccountID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountSnapshotsBefore = `-- name: ListAccountSnapshotsBefore :many
SELECT s.account_id, s.date, s.balance_cents FROM balance_snapshots s
JOIN accounts a ON a.id = s.account_id
WHERE a.household_id = ? AND s.date = (
    SELECT MAX(s2.date) FROM balance_snapshots s2 WHERE s2.account_id = s.account_id AND s2.date < ?
)
`

type ListAccountSnapshotsBeforeParams struct {
	HouseholdID int64  `json:"household_id"`
	Date        string `json:"date"`
}

// Latest snapshot per account strictly before a date, used to seed history.
func (q *Queries) ListAccountSnapshotsBefore(ctx context.Context, arg ListAccountSnapshotsBeforeParams) ([]BalanceSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listAccountSnapshotsBefore, arg.HouseholdID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceSnapshot
	for rows.Next() {
		var i BalanceSnapshot
		if err := rows.Scan(&i.AccountID, &i.Date, &i.BalanceCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountTransactionKeys = `-- name: ListAccountTransactionKeys :many
SELECT id, external_id, date, amount_cents, pending FROM transactions WHERE account_id = ?
`

type ListAccountTransactionKeysRow struct {
	ID          int64          `json:"id"`
	ExternalID  sql.NullString `json:"external_id"`
	Date        string         `json:"date"`
	AmountCents int64          `json:"amount_cents"`
	Pending     int64          `json:"pending"`
}

func (q *Queries) ListAccountTransactionKeys(ctx context.Context, accountID int64) ([]ListAccountTransactionKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountTransactionKeys, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountTransactionKeysRow
	for rows.Next() {
		var i ListAccountTransactionKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Date,
			&i.AmountCents,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many

SELECT id, household_id, connection_id, institution_id, external_id, institution_name, provider_name, name, mask, type, currency, balance_cents, available_cents, balance_at, status, review_candidate_id, include_in_net_worth, hidden, owner_user_id, is_manual, created_at, updated_at, builtin, color, color_source FROM accounts WHERE household_id = ? ORDER BY type, name, id
`

// ---- accounts ----
func (q *Queries) ListAccounts(ctx context.Context, householdID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ConnectionID,
			&i.InstitutionID,
			&i.ExternalID,
			&i.InstitutionName,
			&i.ProviderName,
			&i.Name,
			&i.Mask,
			&i.Type,
			&i.Currency,
			&i.BalanceCents,
			&i.AvailableCents,
			&i.BalanceAt,
			&i.Status,
			&i.ReviewCandidateID,
			&i.IncludeInNetWorth,
			&i.Hidden,
			&i.OwnerUserID,
			&i.IsManual,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Builtin,
			&i.Color,
			&i.ColorSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsNeedingColor = `-- name: ListAccountsNeedingColor :many
SELECT id, household_id, connection_id, institution_id, external_id, institution_name, provider_name, name, mask, type, currency, balance_cents, available_cents, balance_at, status, review_candidate_id, include_in_net_worth, hidden, owner_user_id, is_manual, created_at, updated_at, builtin, color, color_source FROM accounts WHERE household_id = ? AND color_source = '' ORDER BY id
`

func (q *Queries) ListAccountsNeedingColor(ctx context.Context, householdID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsNeedingColor, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ConnectionID,
			&i.InstitutionID,
			&i.ExternalID,
			&i.InstitutionName,
			&i.ProviderName,
			&i.Name,
			&i.Mask,
			&i.Type,
			&i.Currency,
			&i.BalanceCents,
			&i.AvailableCents,
			&i.BalanceAt,
			&i.Status,
			&i.ReviewCandidateID,
			&i.IncludeInNetWorth,
			&i.Hidden,
			&i.OwnerUserID,
			&i.IsManual,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Builtin,
			&i.Color,
			&i.ColorSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionAccounts = `-- name: ListConnectionAccounts :many
SELECT id, household_id, connection_id, institution_id, external_id, institution_name, provider_name, name, mask, type, currency, balance_cents, available_cents, balance_at, status, review_candidate_id, include_in_net_worth, hidden, owner_user_id, is_manual, created_at, updated_at, builtin, color, color_source FROM accounts WHERE connection_id = ?
`

func (q *Queries) ListConnectionAccounts(ctx context.Context, connectionID sql.NullInt64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionAccounts, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ConnectionID,
			&i.InstitutionID,
			&i.ExternalID,
			&i.InstitutionName,
			&i.ProviderName,
			&i.Name,
			&i.Mask,
			&i.Type,
			&i.Currency,
			&i.BalanceCents,
			&i.AvailableCents,
			&i.BalanceAt,
			&i.Status,
			&i.ReviewCandidateID,
			&i.IncludeInNetWorth,
			&i.Hidden,
			&i.OwnerUserID,
			&i.IsManual,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Builtin,
			&i.Color,
			&i.ColorSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnections = `-- name: ListConnections :many
SELECT id, household_id, provider, name, secret_enc, status, last_error, last_sync_at, synced_through, next_sync_at, requests_day, requests_count, created_at FROM connections WHERE household_id = ? ORDER BY id
`

func (q *Queries) ListConnections(ctx context.Context, householdID int64) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, listConnections, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Provider,
			&i.Name,
			&i.SecretEnc,
			&i.Status,
			&i.LastError,
			&i.LastSyncAt,
			&i.SyncedThrough,
			&i.NextSyncAt,
			&i.RequestsDay,
			&i.RequestsCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueConnections = `-- name: ListDueConnections :many
SELECT id, household_id, provider, name, secret_enc, status, last_error, last_sync_at, synced_through, next_sync_at, requests_day, requests_count, created_at FROM connections
WHERE status != 'revoked' AND next_sync_at IS NOT NULL AND next_sync_at <= ?
ORDER BY next_sync_at
`

func (q *Queries) ListDueConnections(ctx context.Context, nextSyncAt sql.NullInt64) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, listDueConnections, nextSyncAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Provider,
			&i.Name,
			&i.SecretEnc,
			&i.Status,
			&i.LastError,
			&i.LastSyncAt,
			&i.SyncedThrough,
			&i.NextSyncAt,
			&i.RequestsDay,
			&i.RequestsCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdSnapshots = `-- name: ListHouseholdSnapshots :many
SELECT s.account_id, s.date, s.balance_cents FROM balance_snapshots s
JOIN accounts a ON a.id = s.account_id
WHERE a.household_id = ? AND s.date >= ?
ORDER BY s.date
`

type ListHouseholdSnapshotsParams struct {
	HouseholdID int64  `json:"household_id"`
	Date        string `json:"date"`
}

func (q *Queries) ListHouseholdSnapshots(ctx context.Context, arg ListHouseholdSnapshotsParams) ([]BalanceSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholdSnapshots, arg.HouseholdID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceSnapshot
	for rows.Next() {
		var i BalanceSnapshot
		if err := rows.Scan(&i.AccountID, &i.Date, &i.BalanceCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsNeedingColor = `-- name: ListHouseholdsNeedingColor :many
SELECT DISTINCT household_id FROM accounts WHERE color_source = ''
`

func (q *Queries) ListHouseholdsNeedingColor(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholdsNeedingColor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var household_id int64
		if err := rows.Scan(&household_id); err != nil {
			return nil, err
		}
		items = append(items, household_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstitutions = `-- name: ListInstitutions :many
SELECT i.id, i.connection_id, i.external_id, i.name, i.url, i.status, i.last_error FROM institutions i
JOIN connections c ON c.id = i.connection_id
WHERE c.household_id = ?
ORDER BY i.id
`

func (q *Queries) ListInstitutions(ctx context.Context, householdID int64) ([]Institution, error) {
	rows, err := q.db.QueryContext(ctx, listInstitutions, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Institution
	for rows.Next() {
		var i Institution
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.ExternalID,
			&i.Name,
			&i.Url,
			&i.Status,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSynced = `-- name: ListPendingSynced :many
SELECT id, external_id FROM transactions
WHERE account_id = ? AND source = ? AND pending = 1 AND date >= ?
`

type ListPendingSyncedParams struct {
	AccountID int64  `json:"account_id"`
	Source    string `json:"source"`
	Date      string `json:"date"`
}

type ListPendingSyncedRow struct {
	ID         int64          `json:"id"`
	ExternalID sql.NullString `json:"external_id"`
}

func (q *Queries) ListPendingSynced(ctx context.Context, arg ListPendingSyncedParams) ([]ListPendingSyncedRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingSynced, arg.AccountID, arg.Source, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingSyncedRow
	for rows.Next() {
		var i ListPendingSyncedRow
		if err := rows.Scan(&i.ID, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncEvents = `-- name: ListSyncEvents :many
SELECT id, connection_id, at, kind, account_id, message FROM sync_events WHERE connection_id = ? ORDER BY at DESC, id DESC LIMIT ?
`

type ListSyncEventsParams struct {
	ConnectionID int64 `json:"connection_id"`
	Limit        int64 `json:"limit"`
}

func (q *Queries) ListSyncEvents(ctx context.Context, arg ListSyncEventsParams) ([]SyncEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSyncEvents, arg.ConnectionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncEvent
	for rows.Next() {
		var i SyncEvent
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.At,
			&i.Kind,
			&i.AccountID,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveSnapshots = `-- name: MoveSnapshots :exec
INSERT OR IGNORE INTO balance_snapshots (account_id, date, balance_cents)
SELECT ?1, src.date, src.balance_cents FROM balance_snapshots src WHERE src.account_id = ?2
`

type MoveSnapshotsParams struct {
	IntoID int64 `json:"into_id"`
	FromID int64 `json:"from_id"`
}

func (q *Queries) MoveSnapshots(ctx context.Context, arg MoveSnapshotsParams) error {
	_, err := q.db.ExecContext(ctx, moveSnapshots, arg.IntoID, arg.FromID)
	return err
}

const moveTransaction = `-- name: MoveTransaction :exec
UPDATE transactions SET account_id = ?, updated_at = ? WHERE id = ?
`

type MoveTransactionParams struct {
	AccountID int64 `json:"account_id"`
	UpdatedAt int64 `json:"updated_at"`
	ID        int64 `json:"id"`
}

func (q *Queries) MoveTransaction(ctx context.Context, arg MoveTransactionParams) error {
	_, err := q.db.ExecContext(ctx, moveTransaction, arg.AccountID, arg.UpdatedAt, arg.ID)
	return err
}

const relinkAccount = `-- name: RelinkAccount :exec
UPDATE accounts
SET connection_id = ?, institution_id = ?, external_id = ?, institution_name = ?, provider_name = ?,
    status = 'active', review_candidate_id = NULL, updated_at = ?
WHERE id = ?
`

type RelinkAccountParams struct {
	ConnectionID    sql.NullInt64  `json:"connection_id"`
	InstitutionID   sql.NullInt64  `json:"institution_id"`
	ExternalID      sql.NullString `json:"external_id"`
	InstitutionName string         `json:"institution_name"`
	ProviderName    string         `json:"provider_name"`
	UpdatedAt       int64          `json:"updated_at"`
	ID              int64          `json:"id"`
}

func (q *Queries) RelinkAccount(ctx context.Context, arg RelinkAccountParams) error {
	_, err := q.db.ExecContext(ctx, relinkAccount,
		arg.ConnectionID,
		arg.InstitutionID,
		arg.ExternalID,
		arg.InstitutionName,
		arg.ProviderName,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setAccountColor = `-- name: SetAccountColor :exec

UPDATE accounts SET color = ?, color_source = ?, updated_at = ? WHERE id = ? AND household_id = ?
`

type SetAccountColorParams struct {
	Color       string `json:"color"`
	ColorSource string `json:"color_source"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
}

// ---- account look ----
func (q *Queries) SetAccountColor(ctx context.Context, arg SetAccountColorParams) error {
	_, err := q.db.ExecContext(ctx, setAccountColor,
		arg.Color,
		arg.ColorSource,
		arg.UpdatedAt,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const setAccountLogo = `-- name: SetAccountLogo :exec
INSERT INTO account_logos (account_id, mime, data, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT (account_id) DO UPDATE SET mime = excluded.mime, data = excluded.data, updated_at = excluded.updated_at
`

type SetAccountLogoParams struct {
	AccountID int64  `json:"account_id"`
	Mime      string `json:"mime"`
	Data      []byte `json:"data"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetAccountLogo(ctx context.Context, arg SetAccountLogoParams) error {
	_, err := q.db.ExecContext(ctx, setAccountLogo,
		arg.AccountID,
		arg.Mime,
		arg.Data,
		arg.UpdatedAt,
	)
	return err
}

const setAccountStatus = `-- name: SetAccountStatus :exec
UPDATE accounts SET status = ?, review_candidate_id = NULL, updated_at = ? WHERE id = ?
`

type SetAccountStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAccountStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const setConnectionRequests = `-- name: SetConnectionRequests :exec
UPDATE connections SET requests_day = ?, requests_count = ? WHERE id = ?
`

type SetConnectionRequestsParams struct {
	RequestsDay   string `json:"requests_day"`
	RequestsCount int64  `json:"requests_count"`
	ID            int64  `json:"id"`
}

func (q *Queries) SetConnectionRequests(ctx context.Context, arg SetConnectionRequestsParams) error {
	_, err := q.db.ExecContext(ctx, setConnectionRequests, arg.RequestsDay, arg.RequestsCount, arg.ID)
	return err
}

const setConnectionSyncError = `-- name: SetConnectionSyncError :exec
UPDATE connections SET status = ?, last_error = ?, next_sync_at = ? WHERE id = ?
`

type SetConnectionSyncErrorParams struct {
	Status     string        `json:"status"`
	LastError  string        `json:"last_error"`
	NextSyncAt sql.NullInt64 `json:"next_sync_at"`
	ID         int64         `json:"id"`
}

func (q *Queries) SetConnectionSyncError(ctx context.Context, arg SetConnectionSyncErrorParams) error {
	_, err := q.db.ExecContext(ctx, setConnectionSyncError,
		arg.Status,
		arg.LastError,
		arg.NextSyncAt,
		arg.ID,
	)
	return err
}

const setConnectionSyncOK = `-- name: SetConnectionSyncOK :exec
UPDATE connections
SET status = 'active', last_error = '', last_sync_at = ?, synced_through = ?, next_sync_at = ?
WHERE id = ?
`

type SetConnectionSyncOKParams struct {
	LastSyncAt    sql.NullInt64 `json:"last_sync_at"`
	SyncedThrough sql.NullInt64 `json:"synced_through"`
	NextSyncAt    sql.NullInt64 `json:"next_sync_at"`
	ID            int64         `json:"id"`
}

func (q *Queries) SetConnectionSyncOK(ctx context.Context, arg SetConnectionSyncOKParams) error {
	_, err := q.db.ExecContext(ctx, setConnectionSyncOK,
		arg.LastSyncAt,
		arg.SyncedThrough,
		arg.NextSyncAt,
		arg.ID,
	)
	return err
}

const setInstitutionStatus = `-- name: SetInstitutionStatus :exec
UPDATE institutions SET status = ?, last_error = ? WHERE id = ?
`

type SetInstitutionStatusParams struct {
	Status    string `json:"status"`
	LastError string `json:"last_error"`
	ID        int64  `json:"id"`
}

func (q *Queries) SetInstitutionStatus(ctx context.Context, arg SetInstitutionStatusParams) error {
	_, err := q.db.ExecContext(ctx, setInstitutionStatus, arg.Status, arg.LastError, arg.ID)
	return err
}

const setManualBalance = `-- name: SetManualBalance :exec
UPDATE accounts SET balance_cents = ?, balance_at = ?, updated_at = ? WHERE id = ? AND household_id = ?
`

type SetManualBalanceParams struct {
	BalanceCents int64         `json:"balance_cents"`
	BalanceAt    sql.NullInt64 `json:"balance_at"`
	UpdatedAt    int64         `json:"updated_at"`
	ID           int64         `json:"id"`
	HouseholdID  int64         `json:"household_id"`
}

func (q *Queries) SetManualBalance(ctx context.Context, arg SetManualBalanceParams) error {
	_, err := q.db.ExecContext(ctx, setManualBalance,
		arg.BalanceCents,
		arg.BalanceAt,
		arg.UpdatedAt,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const setTransactionExternal = `-- name: SetTransactionExternal :exec
UPDATE transactions SET external_id = ? WHERE id = ?
`

type SetTransactionExternalParams struct {
	ExternalID sql.NullString `json:"external_id"`
	ID         int64          `json:"id"`
}

func (q *Queries) SetTransactionExternal(ctx context.Context, arg SetTransactionExternalParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionExternal, arg.ExternalID, arg.ID)
	return err
}

const updateAccountFromSync = `-- name: UpdateAccountFromSync :one
UPDATE accounts
SET institution_id = ?1, institution_name = ?2,
    provider_name = ?3, currency = ?4,
    balance_cents = CASE WHEN balance_at > ?5 THEN balance_cents ELSE ?6 END,
    available_cents = CASE WHEN balance_at > ?5 THEN available_cents ELSE ?7 END,
    balance_at = CASE WHEN balance_at > ?5 THEN balance_at ELSE ?5 END,
    status = CASE WHEN status = 'disconnected' THEN 'active' ELSE status END,
    updated_at = ?8
WHERE id = ?9
RETURNING balance_cents
`

type UpdateAccountFromSyncParams struct {
	InstitutionID   sql.NullInt64 `json:"institution_id"`
	InstitutionName string        `json:"institution_name"`
	ProviderName    string        `json:"provider_name"`
	Currency        string        `json:"currency"`
	BalanceAt       sql.NullInt64 `json:"balance_at"`
	BalanceCents    int64         `json:"balance_cents"`
	AvailableCents  sql.NullInt64 `json:"available_cents"`
	UpdatedAt       int64         `json:"updated_at"`
	ID              int64         `json:"id"`
}

// A balance read more recently than the bank's (e.g. from a balance-summary email) is kept until
// the bank reports a newer one. Returns the balance the account ends up with.
func (q *Queries) UpdateAccountFromSync(ctx context.Context, arg UpdateAccountFromSyncParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateAccountFromSync,
		arg.InstitutionID,
		arg.InstitutionName,
		arg.ProviderName,
		arg.Currency,
		arg.BalanceAt,
		arg.BalanceCents,
		arg.AvailableCents,
		arg.UpdatedAt,
		arg.ID,
	)
	var balance_cents int64
	err := row.Scan(&balance_cents)
	return balance_cents, err
}

const updateAccountSettings = `-- name: UpdateAccountSettings :exec
UPDATE accounts
SET name = ?, type = ?, include_in_net_worth = ?, hidden = ?, status = ?, updated_at = ?
WHERE id = ? AND household_id = ?
`

type UpdateAccountSettingsParams struct {
	Name              string `json:"name"`
	Type              string `json:"type"`
	IncludeInNetWorth int64  `json:"include_in_net_worth"`
	Hidden            int64  `json:"hidden"`
	Status            string `json:"status"`
	UpdatedAt         int64  `json:"updated_at"`
	ID                int64  `json:"id"`
	HouseholdID       int64  `json:"household_id"`
}

func (q *Queries) UpdateAccountSettings(ctx context.Context, arg UpdateAccountSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountSettings,
		arg.Name,
		arg.Type,
		arg.IncludeInNetWorth,
		arg.Hidden,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const updateSyncedTransaction = `-- name: UpdateSyncedTransaction :exec
UPDATE transactions
SET date = ?, amount_cents = ?, description = ?, payee = ?, memo = ?, pending = ?, updated_at = ?
WHERE id = ?
`

type UpdateSyncedTransactionParams struct {
	Date        string `json:"date"`
	AmountCents int64  `json:"amount_cents"`
	Description string `json:"description"`
	Payee       string `json:"payee"`
	Memo        string `json:"memo"`
	Pending     int64  `json:"pending"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateSyncedTransaction(ctx context.Context, arg UpdateSyncedTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncedTransaction,
		arg.Date,
		arg.AmountCents,
		arg.Description,
		arg.Payee,
		arg.Memo,
		arg.Pending,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertBalanceSnapshot = `-- name: UpsertBalanceSnapshot :exec

INSERT INTO balance_snapshots (account_id, date, balance_cents) VALUES (?, ?, ?)
ON CONFLICT (account_id, date) DO UPDATE SET balance_cents = excluded.balance_cents
`

type UpsertBalanceSnapshotParams struct {
	AccountID    int64  `json:"account_id"`
	Date         string `json:"date"`
	BalanceCents int64  `json:"balance_cents"`
}

// ---- balances ----
func (q *Queries) UpsertBalanceSnapshot(ctx context.Context, arg UpsertBalanceSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertBalanceSnapshot, arg.AccountID, arg.Date, arg.BalanceCents)
	return err
}

const upsertInstitution = `-- name: UpsertInstitution :one

INSERT INTO institutions (connection_id, external_id, name, url)
VALUES (?, ?, ?, ?)
ON CONFLICT (connection_id, external_id) DO UPDATE SET name = excluded.name, url = excluded.url
RETURNING id, connection_id, external_id, name, url, status, last_error
`

type UpsertInstitutionParams struct {
	ConnectionID int64  `json:"connection_id"`
	ExternalID   string `json:"external_id"`
	Name         string `json:"name"`
	Url          string `json:"url"`
}

// ---- institutions ----
func (q *Queries) UpsertInstitution(ctx context.Context, arg UpsertInstitutionParams) (Institution, error) {
	row := q.db.QueryRowContext(ctx, upsertInstitution,
		arg.ConnectionID,
		arg.ExternalID,
		arg.Name,
		arg.Url,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ExternalID,
		&i.Name,
		&i.Url,
		&i.Status,
		&i.LastError,
	)
	return i, err
}
