// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_usage.sql

package db

import (
	"context"
	"database/sql"
)

const aIUsageByFeature = `-- name: AIUsageByFeature :many
SELECT feature,
  CAST(COUNT(*) AS INTEGER) AS requests,
  CAST(COALESCE(SUM(cost_micros), 0) AS INTEGER) AS cost_micros,
  CAST(SUM(CASE WHEN cost_micros IS NULL THEN 1 ELSE 0 END) AS INTEGER) AS unpriced,
  CAST(COALESCE(SUM(prompt_tokens + completion_tokens), 0) AS INTEGER) AS tokens
FROM ai_usage
WHERE household_id = ?1 AND created_at >= ?2 AND created_at < ?3
GROUP BY feature ORDER BY cost_micros DESC, feature
`

type AIUsageByFeatureParams struct {
	HouseholdID int64 `json:"household_id"`
	FromTs      int64 `json:"from_ts"`
	ToTs        int64 `json:"to_ts"`
}

type AIUsageByFeatureRow struct {
	Feature    string `json:"feature"`
	Requests   int64  `json:"requests"`
	CostMicros int64  `json:"cost_micros"`
	Unpriced   int64  `json:"unpriced"`
	Tokens     int64  `json:"tokens"`
}

// Usage over [from, to) (unix seconds), per feature.
func (q *Queries) AIUsageByFeature(ctx context.Context, arg AIUsageByFeatureParams) ([]AIUsageByFeatureRow, error) {
	rows, err := q.db.QueryContext(ctx, aIUsageByFeature, arg.HouseholdID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AIUsageByFeatureRow
	for rows.Next() {
		var i AIUsageByFeatureRow
		if err := rows.Scan(
			&i.Feature,
			&i.Requests,
			&i.CostMicros,
			&i.Unpriced,
			&i.Tokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aIUsageForRef = `-- name: AIUsageForRef :one
SELECT CAST(COUNT(*) AS INTEGER) AS requests,
  CAST(COALESCE(SUM(cost_micros), 0) AS INTEGER) AS cost_micros,
  CAST(SUM(CASE WHEN cost_micros IS NULL THEN 1 ELSE 0 END) AS INTEGER) AS unpriced
FROM ai_usage WHERE household_id = ? AND feature = ? AND ref_id = ?
`

type AIUsageForRefParams struct {
	HouseholdID int64         `json:"household_id"`
	Feature     string        `json:"feature"`
	RefID       sql.NullInt64 `json:"ref_id"`
}

type AIUsageForRefRow struct {
	Requests   int64 `json:"requests"`
	CostMicros int64 `json:"cost_micros"`
	Unpriced   int64 `json:"unpriced"`
}

func (q *Queries) AIUsageForRef(ctx context.Context, arg AIUsageForRefParams) (AIUsageForRefRow, error) {
	row := q.db.QueryRowContext(ctx, aIUsageForRef, arg.HouseholdID, arg.Feature, arg.RefID)
	var i AIUsageForRefRow
	err := row.Scan(&i.Requests, &i.CostMicros, &i.Unpriced)
	return i, err
}

const insertAIUsage = `-- name: InsertAIUsage :exec
INSERT INTO ai_usage (household_id, created_at, feature, ref_id, model, local, prompt_tokens, completion_tokens, cost_micros)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAIUsageParams struct {
	HouseholdID      int64         `json:"household_id"`
	CreatedAt        int64         `json:"created_at"`
	Feature          string        `json:"feature"`
	RefID            sql.NullInt64 `json:"ref_id"`
	Model            string        `json:"model"`
	Local            int64         `json:"local"`
	PromptTokens     int64         `json:"prompt_tokens"`
	CompletionTokens int64         `json:"completion_tokens"`
	CostMicros       sql.NullInt64 `json:"cost_micros"`
}

func (q *Queries) InsertAIUsage(ctx context.Context, arg InsertAIUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertAIUsage,
		arg.HouseholdID,
		arg.CreatedAt,
		arg.Feature,
		arg.RefID,
		arg.Model,
		arg.Local,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostMicros,
	)
	return err
}
