// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aichanges.sql

package db

import (
	"context"
	"database/sql"
)

const insertAIChange = `-- name: InsertAIChange :exec
INSERT INTO ai_changes (household_id, transaction_id, email_message_id, field, old_value, new_value, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAIChangeParams struct {
	HouseholdID    int64         `json:"household_id"`
	TransactionID  int64         `json:"transaction_id"`
	EmailMessageID sql.NullInt64 `json:"email_message_id"`
	Field          string        `json:"field"`
	OldValue       string        `json:"old_value"`
	NewValue       string        `json:"new_value"`
	CreatedAt      int64         `json:"created_at"`
}

func (q *Queries) InsertAIChange(ctx context.Context, arg InsertAIChangeParams) error {
	_, err := q.db.ExecContext(ctx, insertAIChange,
		arg.HouseholdID,
		arg.TransactionID,
		arg.EmailMessageID,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
		arg.CreatedAt,
	)
	return err
}

const listAIChanges = `-- name: ListAIChanges :many
SELECT c.id, c.household_id, c.transaction_id, c.email_message_id, c.field, c.old_value, c.new_value, c.created_at, c.undone_at, CAST(COALESCE(m.subject, '') AS TEXT) AS email_subject FROM ai_changes c
LEFT JOIN email_messages m ON m.id = c.email_message_id
WHERE c.transaction_id = ? AND c.household_id = ? AND c.undone_at IS NULL ORDER BY c.id
`

type ListAIChangesParams struct {
	TransactionID int64 `json:"transaction_id"`
	HouseholdID   int64 `json:"household_id"`
}

type ListAIChangesRow struct {
	ID             int64         `json:"id"`
	HouseholdID    int64         `json:"household_id"`
	TransactionID  int64         `json:"transaction_id"`
	EmailMessageID sql.NullInt64 `json:"email_message_id"`
	Field          string        `json:"field"`
	OldValue       string        `json:"old_value"`
	NewValue       string        `json:"new_value"`
	CreatedAt      int64         `json:"created_at"`
	UndoneAt       sql.NullInt64 `json:"undone_at"`
	EmailSubject   string        `json:"email_subject"`
}

func (q *Queries) ListAIChanges(ctx context.Context, arg ListAIChangesParams) ([]ListAIChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAIChanges, arg.TransactionID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIChangesRow
	for rows.Next() {
		var i ListAIChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.TransactionID,
			&i.EmailMessageID,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.UndoneAt,
			&i.EmailSubject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAIChangesUndone = `-- name: MarkAIChangesUndone :exec
UPDATE ai_changes SET undone_at = ? WHERE transaction_id = ? AND household_id = ? AND undone_at IS NULL
`

type MarkAIChangesUndoneParams struct {
	UndoneAt      sql.NullInt64 `json:"undone_at"`
	TransactionID int64         `json:"transaction_id"`
	HouseholdID   int64         `json:"household_id"`
}

func (q *Queries) MarkAIChangesUndone(ctx context.Context, arg MarkAIChangesUndoneParams) error {
	_, err := q.db.ExecContext(ctx, markAIChangesUndone, arg.UndoneAt, arg.TransactionID, arg.HouseholdID)
	return err
}

const removeTransactionTag = `-- name: RemoveTransactionTag :exec
DELETE FROM transaction_tags WHERE transaction_id = ? AND tag_id = ?
`

type RemoveTransactionTagParams struct {
	TransactionID int64 `json:"transaction_id"`
	TagID         int64 `json:"tag_id"`
}

func (q *Queries) RemoveTransactionTag(ctx context.Context, arg RemoveTransactionTagParams) error {
	_, err := q.db.ExecContext(ctx, removeTransactionTag, arg.TransactionID, arg.TagID)
	return err
}

const setTransactionCategoryAI = `-- name: SetTransactionCategoryAI :exec
UPDATE transactions SET category_id = ?, category_source = ?, updated_at = ? WHERE id = ? AND household_id = ?
`

type SetTransactionCategoryAIParams struct {
	CategoryID     sql.NullInt64 `json:"category_id"`
	CategorySource string        `json:"category_source"`
	UpdatedAt      int64         `json:"updated_at"`
	ID             int64         `json:"id"`
	HouseholdID    int64         `json:"household_id"`
}

// Narrow writes the email AI may make.
func (q *Queries) SetTransactionCategoryAI(ctx context.Context, arg SetTransactionCategoryAIParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionCategoryAI,
		arg.CategoryID,
		arg.CategorySource,
		arg.UpdatedAt,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const setTransactionNeedsReview = `-- name: SetTransactionNeedsReview :exec
UPDATE transactions SET needs_review = ?, updated_at = ? WHERE id = ? AND household_id = ?
`

type SetTransactionNeedsReviewParams struct {
	NeedsReview int64 `json:"needs_review"`
	UpdatedAt   int64 `json:"updated_at"`
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) SetTransactionNeedsReview(ctx context.Context, arg SetTransactionNeedsReviewParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionNeedsReview,
		arg.NeedsReview,
		arg.UpdatedAt,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const setTransactionNotes = `-- name: SetTransactionNotes :exec
UPDATE transactions SET notes = ?, updated_at = ? WHERE id = ? AND household_id = ?
`

type SetTransactionNotesParams struct {
	Notes       string `json:"notes"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
}

func (q *Queries) SetTransactionNotes(ctx context.Context, arg SetTransactionNotesParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionNotes,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}
