// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package db

import (
	"context"
	"database/sql"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, household_id, user_id, name, prefix, token_hash, scope, created_at, last_used_at, revoked_at FROM api_keys WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, tokenHash []byte) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, tokenHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (household_id, user_id, name, prefix, token_hash, scope, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, household_id, user_id, name, prefix, token_hash, scope, created_at, last_used_at, revoked_at
`

type InsertAPIKeyParams struct {
	HouseholdID int64  `json:"household_id"`
	UserID      int64  `json:"user_id"`
	Name        string `json:"name"`
	Prefix      string `json:"prefix"`
	TokenHash   []byte `json:"token_hash"`
	Scope       string `json:"scope"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, insertAPIKey,
		arg.HouseholdID,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.Scope,
		arg.CreatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT k.id, k.household_id, k.user_id, k.name, k.prefix, k.token_hash, k.scope, k.created_at, k.last_used_at, k.revoked_at, u.name AS user_name FROM api_keys k JOIN users u ON u.id = k.user_id
WHERE k.household_id = ? AND k.revoked_at IS NULL ORDER BY k.id
`

type ListAPIKeysRow struct {
	ID          int64         `json:"id"`
	HouseholdID int64         `json:"household_id"`
	UserID      int64         `json:"user_id"`
	Name        string        `json:"name"`
	Prefix      string        `json:"prefix"`
	TokenHash   []byte        `json:"token_hash"`
	Scope       string        `json:"scope"`
	CreatedAt   int64         `json:"created_at"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
	UserName    string        `json:"user_name"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, householdID int64) ([]ListAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.TokenHash,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = ? WHERE id = ? AND household_id = ? AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
	ID          int64         `json:"id"`
	HouseholdID int64         `json:"household_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIKey, arg.RevokedAt, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = ? WHERE id = ?
`

type TouchAPIKeyParams struct {
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	ID         int64         `json:"id"`
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey, arg.LastUsedAt, arg.ID)
	return err
}
