// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package db

import (
	"context"
	"database/sql"
)

const clearGoalTransactions = `-- name: ClearGoalTransactions :exec
UPDATE transactions SET goal_id = NULL WHERE goal_id = ? AND household_id = ?
`

type ClearGoalTransactionsParams struct {
	GoalID      sql.NullInt64 `json:"goal_id"`
	HouseholdID int64         `json:"household_id"`
}

func (q *Queries) ClearGoalTransactions(ctx context.Context, arg ClearGoalTransactionsParams) error {
	_, err := q.db.ExecContext(ctx, clearGoalTransactions, arg.GoalID, arg.HouseholdID)
	return err
}

const createBuiltinGoal = `-- name: CreateBuiltinGoal :one
INSERT INTO goals (household_id, name, icon, builtin, created_at) VALUES (?, ?, ?, ?, ?) RETURNING id, household_id, name, icon, target_cents, target_date, starting_cents, archived, sort, created_at, builtin
`

type CreateBuiltinGoalParams struct {
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Icon        string `json:"icon"`
	Builtin     string `json:"builtin"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateBuiltinGoal(ctx context.Context, arg CreateBuiltinGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createBuiltinGoal,
		arg.HouseholdID,
		arg.Name,
		arg.Icon,
		arg.Builtin,
		arg.CreatedAt,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.TargetCents,
		&i.TargetDate,
		&i.StartingCents,
		&i.Archived,
		&i.Sort,
		&i.CreatedAt,
		&i.Builtin,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (household_id, name, icon, target_cents, target_date, starting_cents, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, household_id, name, icon, target_cents, target_date, starting_cents, archived, sort, created_at, builtin
`

type CreateGoalParams struct {
	HouseholdID   int64          `json:"household_id"`
	Name          string         `json:"name"`
	Icon          string         `json:"icon"`
	TargetCents   int64          `json:"target_cents"`
	TargetDate    sql.NullString `json:"target_date"`
	StartingCents int64          `json:"starting_cents"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.HouseholdID,
		arg.Name,
		arg.Icon,
		arg.TargetCents,
		arg.TargetDate,
		arg.StartingCents,
		arg.CreatedAt,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.TargetCents,
		&i.TargetDate,
		&i.StartingCents,
		&i.Archived,
		&i.Sort,
		&i.CreatedAt,
		&i.Builtin,
	)
	return i, err
}

const dailyCategoryTotals = `-- name: DailyCategoryTotals :many

SELECT t.category_id AS category_id, t.date, CAST(SUM(t.amount_cents) AS INTEGER) AS total
FROM transactions t JOIN accounts a ON a.id = t.account_id
WHERE t.household_id = ?1 AND t.date >= ?2 AND t.date < ?3
  AND t.category_id IS NOT NULL AND t.hidden = 0 AND t.linked_txn_id IS NULL AND a.status != 'ignored'
GROUP BY t.category_id, t.date
`

type DailyCategoryTotalsParams struct {
	HouseholdID int64  `json:"household_id"`
	FromDate    string `json:"from_date"`
	ToDate      string `json:"to_date"`
}

type DailyCategoryTotalsRow struct {
	CategoryID sql.NullInt64 `json:"category_id"`
	Date       string        `json:"date"`
	Total      int64         `json:"total"`
}

// ---- totals ----
// Signed daily totals per category over [from, to), for budgets and history. Leaves out
// hidden rows, linked provisional rows (their posted twin counts) and ignored accounts.
func (q *Queries) DailyCategoryTotals(ctx context.Context, arg DailyCategoryTotalsParams) ([]DailyCategoryTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, dailyCategoryTotals, arg.HouseholdID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyCategoryTotalsRow
	for rows.Next() {
		var i DailyCategoryTotalsRow
		if err := rows.Scan(&i.CategoryID, &i.Date, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailyGoalTotals = `-- name: DailyGoalTotals :many
SELECT t.goal_id AS goal_id, t.date, CAST(SUM(ABS(t.amount_cents)) AS INTEGER) AS total
FROM transactions t JOIN accounts a ON a.id = t.account_id
WHERE t.household_id = ?1 AND t.date >= ?2 AND t.date < ?3
  AND t.goal_id IS NOT NULL AND t.goal_withdrawal = 0 AND t.hidden = 0 AND t.linked_txn_id IS NULL AND a.status != 'ignored'
GROUP BY t.goal_id, t.date
`

type DailyGoalTotalsParams struct {
	HouseholdID int64  `json:"household_id"`
	FromDate    string `json:"from_date"`
	ToDate      string `json:"to_date"`
}

type DailyGoalTotalsRow struct {
	GoalID sql.NullInt64 `json:"goal_id"`
	Date   string        `json:"date"`
	Total  int64         `json:"total"`
}

// Money put toward each goal per day (absolute amounts) over [from, to). Money spent from a
// goal (goal_withdrawal) isn't a contribution.
func (q *Queries) DailyGoalTotals(ctx context.Context, arg DailyGoalTotalsParams) ([]DailyGoalTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, dailyGoalTotals, arg.HouseholdID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyGoalTotalsRow
	for rows.Next() {
		var i DailyGoalTotalsRow
		if err := rows.Scan(&i.GoalID, &i.Date, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBudgetAmountsFor = `-- name: DeleteBudgetAmountsFor :exec
DELETE FROM budget_amounts
WHERE household_id = ?1
  AND category_id IS ?2 AND goal_id IS ?3
`

type DeleteBudgetAmountsForParams struct {
	HouseholdID int64         `json:"household_id"`
	CategoryID  sql.NullInt64 `json:"category_id"`
	GoalID      sql.NullInt64 `json:"goal_id"`
}

// All rows of one category or goal are rewritten together (see budget.SetAmount).
func (q *Queries) DeleteBudgetAmountsFor(ctx context.Context, arg DeleteBudgetAmountsForParams) error {
	_, err := q.db.ExecContext(ctx, deleteBudgetAmountsFor, arg.HouseholdID, arg.CategoryID, arg.GoalID)
	return err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = ? AND household_id = ?
`

type DeleteGoalParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.ExecContext(ctx, deleteGoal, arg.ID, arg.HouseholdID)
	return err
}

const getBuiltinGoal = `-- name: GetBuiltinGoal :one
SELECT id, household_id, name, icon, target_cents, target_date, starting_cents, archived, sort, created_at, builtin FROM goals WHERE household_id = ? AND builtin = ? ORDER BY id LIMIT 1
`

type GetBuiltinGoalParams struct {
	HouseholdID int64  `json:"household_id"`
	Builtin     string `json:"builtin"`
}

func (q *Queries) GetBuiltinGoal(ctx context.Context, arg GetBuiltinGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getBuiltinGoal, arg.HouseholdID, arg.Builtin)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.TargetCents,
		&i.TargetDate,
		&i.StartingCents,
		&i.Archived,
		&i.Sort,
		&i.CreatedAt,
		&i.Builtin,
	)
	return i, err
}

const getCategoryGroupKind = `-- name: GetCategoryGroupKind :one
SELECT kind FROM category_groups WHERE id = ?
`

func (q *Queries) GetCategoryGroupKind(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getCategoryGroupKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, household_id, name, icon, target_cents, target_date, starting_cents, archived, sort, created_at, builtin FROM goals WHERE id = ? AND household_id = ?
`

type GetGoalParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoal, arg.ID, arg.HouseholdID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.TargetCents,
		&i.TargetDate,
		&i.StartingCents,
		&i.Archived,
		&i.Sort,
		&i.CreatedAt,
		&i.Builtin,
	)
	return i, err
}

const insertBudgetAmount = `-- name: InsertBudgetAmount :exec
INSERT INTO budget_amounts (household_id, category_id, goal_id, month, amount_cents, forward)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertBudgetAmountParams struct {
	HouseholdID int64         `json:"household_id"`
	CategoryID  sql.NullInt64 `json:"category_id"`
	GoalID      sql.NullInt64 `json:"goal_id"`
	Month       string        `json:"month"`
	AmountCents int64         `json:"amount_cents"`
	Forward     int64         `json:"forward"`
}

func (q *Queries) InsertBudgetAmount(ctx context.Context, arg InsertBudgetAmountParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetAmount,
		arg.HouseholdID,
		arg.CategoryID,
		arg.GoalID,
		arg.Month,
		arg.AmountCents,
		arg.Forward,
	)
	return err
}

const listBudgetAmounts = `-- name: ListBudgetAmounts :many

SELECT id, household_id, category_id, goal_id, month, amount_cents, forward FROM budget_amounts WHERE household_id = ? ORDER BY month
`

// ---- budget amounts ----
func (q *Queries) ListBudgetAmounts(ctx context.Context, householdID int64) ([]BudgetAmount, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetAmounts, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetAmount
	for rows.Next() {
		var i BudgetAmount
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.CategoryID,
			&i.GoalID,
			&i.Month,
			&i.AmountCents,
			&i.Forward,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many

SELECT g.id, g.household_id, g.name, g.icon, g.target_cents, g.target_date, g.starting_cents, g.archived, g.sort, g.created_at, g.builtin, CAST(COALESCE((
    SELECT SUM(ABS(t.amount_cents)) FROM transactions t
    WHERE t.goal_id = g.id AND t.goal_withdrawal = 0 AND t.hidden = 0 AND t.linked_txn_id IS NULL), 0) AS INTEGER) AS contributed_cents,
  CAST(COALESCE((
    SELECT SUM(ABS(t.amount_cents)) FROM transactions t
    WHERE t.goal_id = g.id AND t.goal_withdrawal = 1 AND t.hidden = 0 AND t.linked_txn_id IS NULL), 0) AS INTEGER) AS withdrawn_cents
FROM goals g WHERE g.household_id = ? ORDER BY g.archived, g.sort, g.id
`

type ListGoalsRow struct {
	ID               int64          `json:"id"`
	HouseholdID      int64          `json:"household_id"`
	Name             string         `json:"name"`
	Icon             string         `json:"icon"`
	TargetCents      int64          `json:"target_cents"`
	TargetDate       sql.NullString `json:"target_date"`
	StartingCents    int64          `json:"starting_cents"`
	Archived         int64          `json:"archived"`
	Sort             int64          `json:"sort"`
	CreatedAt        int64          `json:"created_at"`
	Builtin          string         `json:"builtin"`
	ContributedCents int64          `json:"contributed_cents"`
	WithdrawnCents   int64          `json:"withdrawn_cents"`
}

// ---- goals ----
func (q *Queries) ListGoals(ctx context.Context, householdID int64) ([]ListGoalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoals, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalsRow
	for rows.Next() {
		var i ListGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Icon,
			&i.TargetCents,
			&i.TargetDate,
			&i.StartingCents,
			&i.Archived,
			&i.Sort,
			&i.CreatedAt,
			&i.Builtin,
			&i.ContributedCents,
			&i.WithdrawnCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdSettings = `-- name: ListHouseholdSettings :many

SELECT key, value FROM household_settings WHERE household_id = ?
`

type ListHouseholdSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// ---- household settings ----
func (q *Queries) ListHouseholdSettings(ctx context.Context, householdID int64) ([]ListHouseholdSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholdSettings, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseholdSettingsRow
	for rows.Next() {
		var i ListHouseholdSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryBudgetHidden = `-- name: SetCategoryBudgetHidden :exec
UPDATE categories SET budget_hidden = ? WHERE id = ? AND household_id = ?
`

type SetCategoryBudgetHiddenParams struct {
	BudgetHidden int64 `json:"budget_hidden"`
	ID           int64 `json:"id"`
	HouseholdID  int64 `json:"household_id"`
}

func (q *Queries) SetCategoryBudgetHidden(ctx context.Context, arg SetCategoryBudgetHiddenParams) error {
	_, err := q.db.ExecContext(ctx, setCategoryBudgetHidden, arg.BudgetHidden, arg.ID, arg.HouseholdID)
	return err
}

const setCategoryChunk = `-- name: SetCategoryChunk :exec
UPDATE categories SET chunk = ? WHERE id = ? AND household_id = ?
`

type SetCategoryChunkParams struct {
	Chunk       string `json:"chunk"`
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
}

func (q *Queries) SetCategoryChunk(ctx context.Context, arg SetCategoryChunkParams) error {
	_, err := q.db.ExecContext(ctx, setCategoryChunk, arg.Chunk, arg.ID, arg.HouseholdID)
	return err
}

const setHouseholdSetting = `-- name: SetHouseholdSetting :exec
INSERT INTO household_settings (household_id, key, value) VALUES (?, ?, ?)
ON CONFLICT (household_id, key) DO UPDATE SET value = excluded.value
`

type SetHouseholdSettingParams struct {
	HouseholdID int64  `json:"household_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
}

func (q *Queries) SetHouseholdSetting(ctx context.Context, arg SetHouseholdSettingParams) error {
	_, err := q.db.ExecContext(ctx, setHouseholdSetting, arg.HouseholdID, arg.Key, arg.Value)
	return err
}

const setTransactionGoal = `-- name: SetTransactionGoal :exec
UPDATE transactions SET goal_withdrawal = CASE WHEN goal_id IS ?1 THEN goal_withdrawal ELSE 0 END,
    goal_id = ?1
WHERE id = ?2 AND household_id = ?3
`

type SetTransactionGoalParams struct {
	GoalID      sql.NullInt64 `json:"goal_id"`
	ID          int64         `json:"id"`
	HouseholdID int64         `json:"household_id"`
}

// Moving a transaction to another goal (or none) makes it a contribution again.
func (q *Queries) SetTransactionGoal(ctx context.Context, arg SetTransactionGoalParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionGoal, arg.GoalID, arg.ID, arg.HouseholdID)
	return err
}

const setTransactionGoalWithdrawal = `-- name: SetTransactionGoalWithdrawal :exec
UPDATE transactions SET goal_id = ?, goal_withdrawal = ? WHERE id = ? AND household_id = ?
`

type SetTransactionGoalWithdrawalParams struct {
	GoalID         sql.NullInt64 `json:"goal_id"`
	GoalWithdrawal int64         `json:"goal_withdrawal"`
	ID             int64         `json:"id"`
	HouseholdID    int64         `json:"household_id"`
}

func (q *Queries) SetTransactionGoalWithdrawal(ctx context.Context, arg SetTransactionGoalWithdrawalParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionGoalWithdrawal,
		arg.GoalID,
		arg.GoalWithdrawal,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const updateGoal = `-- name: UpdateGoal :exec
UPDATE goals SET name = ?, icon = ?, target_cents = ?, target_date = ?, starting_cents = ?, archived = ?
WHERE id = ? AND household_id = ?
`

type UpdateGoalParams struct {
	Name          string         `json:"name"`
	Icon          string         `json:"icon"`
	TargetCents   int64          `json:"target_cents"`
	TargetDate    sql.NullString `json:"target_date"`
	StartingCents int64          `json:"starting_cents"`
	Archived      int64          `json:"archived"`
	ID            int64          `json:"id"`
	HouseholdID   int64          `json:"household_id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) error {
	_, err := q.db.ExecContext(ctx, updateGoal,
		arg.Name,
		arg.Icon,
		arg.TargetCents,
		arg.TargetDate,
		arg.StartingCents,
		arg.Archived,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}
