// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
)

const createChatThread = `-- name: CreateChatThread :one
INSERT INTO chat_threads (user_id, title, context, created_at, updated_at) VALUES (?, ?, ?, ?, ?) RETURNING id, user_id, title, created_at, updated_at, context
`

type CreateChatThreadParams struct {
	UserID    int64  `json:"user_id"`
	Title     string `json:"title"`
	Context   string `json:"context"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateChatThread(ctx context.Context, arg CreateChatThreadParams) (ChatThread, error) {
	row := q.db.QueryRowContext(ctx, createChatThread,
		arg.UserID,
		arg.Title,
		arg.Context,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Context,
	)
	return i, err
}

const deleteChatThread = `-- name: DeleteChatThread :exec
DELETE FROM chat_threads WHERE id = ? AND user_id = ?
`

type DeleteChatThreadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteChatThread(ctx context.Context, arg DeleteChatThreadParams) error {
	_, err := q.db.ExecContext(ctx, deleteChatThread, arg.ID, arg.UserID)
	return err
}

const getChatThread = `-- name: GetChatThread :one
SELECT id, user_id, title, created_at, updated_at, context FROM chat_threads WHERE id = ? AND user_id = ?
`

type GetChatThreadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetChatThread(ctx context.Context, arg GetChatThreadParams) (ChatThread, error) {
	row := q.db.QueryRowContext(ctx, getChatThread, arg.ID, arg.UserID)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Context,
	)
	return i, err
}

const insertChatMessage = `-- name: InsertChatMessage :one
INSERT INTO chat_messages (thread_id, role, content, tool_calls, tool_call_id, created_at)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, thread_id, role, content, tool_calls, tool_call_id, created_at
`

type InsertChatMessageParams struct {
	ThreadID   int64  `json:"thread_id"`
	Role       string `json:"role"`
	Content    string `json:"content"`
	ToolCalls  string `json:"tool_calls"`
	ToolCallID string `json:"tool_call_id"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, insertChatMessage,
		arg.ThreadID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
		arg.CreatedAt,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.CreatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, thread_id, role, content, tool_calls, tool_call_id, created_at FROM chat_messages WHERE thread_id = ? ORDER BY id
`

func (q *Queries) ListChatMessages(ctx context.Context, threadID int64) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatThreads = `-- name: ListChatThreads :many
SELECT id, user_id, title, created_at, updated_at, context FROM chat_threads WHERE user_id = ? ORDER BY updated_at DESC, id DESC LIMIT 50
`

func (q *Queries) ListChatThreads(ctx context.Context, userID int64) ([]ChatThread, error) {
	rows, err := q.db.QueryContext(ctx, listChatThreads, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatThread
	for rows.Next() {
		var i ChatThread
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameChatThread = `-- name: RenameChatThread :exec
UPDATE chat_threads SET title = ? WHERE id = ? AND user_id = ?
`

type RenameChatThreadParams struct {
	Title  string `json:"title"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) RenameChatThread(ctx context.Context, arg RenameChatThreadParams) error {
	_, err := q.db.ExecContext(ctx, renameChatThread, arg.Title, arg.ID, arg.UserID)
	return err
}

const touchChatThread = `-- name: TouchChatThread :exec
UPDATE chat_threads SET updated_at = ? WHERE id = ?
`

type TouchChatThreadParams struct {
	UpdatedAt int64 `json:"updated_at"`
	ID        int64 `json:"id"`
}

func (q *Queries) TouchChatThread(ctx context.Context, arg TouchChatThreadParams) error {
	_, err := q.db.ExecContext(ctx, touchChatThread, arg.UpdatedAt, arg.ID)
	return err
}
