// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: closeout.sql

package db

import (
	"context"
	"database/sql"
)

const createCloseout = `-- name: CreateCloseout :one
INSERT INTO budget_closeouts (household_id, month, closed_at, closed_by, budget_cents, actual_cents, surplus_cents, review)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, household_id, month, closed_at, closed_by, budget_cents, actual_cents, surplus_cents, review, analysis, analysis_at
`

type CreateCloseoutParams struct {
	HouseholdID  int64         `json:"household_id"`
	Month        string        `json:"month"`
	ClosedAt     int64         `json:"closed_at"`
	ClosedBy     sql.NullInt64 `json:"closed_by"`
	BudgetCents  int64         `json:"budget_cents"`
	ActualCents  int64         `json:"actual_cents"`
	SurplusCents int64         `json:"surplus_cents"`
	Review       string        `json:"review"`
}

func (q *Queries) CreateCloseout(ctx context.Context, arg CreateCloseoutParams) (BudgetCloseout, error) {
	row := q.db.QueryRowContext(ctx, createCloseout,
		arg.HouseholdID,
		arg.Month,
		arg.ClosedAt,
		arg.ClosedBy,
		arg.BudgetCents,
		arg.ActualCents,
		arg.SurplusCents,
		arg.Review,
	)
	var i BudgetCloseout
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Month,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.BudgetCents,
		&i.ActualCents,
		&i.SurplusCents,
		&i.Review,
		&i.Analysis,
		&i.AnalysisAt,
	)
	return i, err
}

const deleteCloseout = `-- name: DeleteCloseout :exec
DELETE FROM budget_closeouts WHERE id = ? AND household_id = ?
`

type DeleteCloseoutParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteCloseout(ctx context.Context, arg DeleteCloseoutParams) error {
	_, err := q.db.ExecContext(ctx, deleteCloseout, arg.ID, arg.HouseholdID)
	return err
}

const getCloseout = `-- name: GetCloseout :one
SELECT id, household_id, month, closed_at, closed_by, budget_cents, actual_cents, surplus_cents, review, analysis, analysis_at FROM budget_closeouts WHERE household_id = ? AND month = ?
`

type GetCloseoutParams struct {
	HouseholdID int64  `json:"household_id"`
	Month       string `json:"month"`
}

func (q *Queries) GetCloseout(ctx context.Context, arg GetCloseoutParams) (BudgetCloseout, error) {
	row := q.db.QueryRowContext(ctx, getCloseout, arg.HouseholdID, arg.Month)
	var i BudgetCloseout
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Month,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.BudgetCents,
		&i.ActualCents,
		&i.SurplusCents,
		&i.Review,
		&i.Analysis,
		&i.AnalysisAt,
	)
	return i, err
}

const insertCloseoutAllocation = `-- name: InsertCloseoutAllocation :exec
INSERT INTO closeout_allocations (closeout_id, household_id, category_id, goal_id, month, amount_cents)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCloseoutAllocationParams struct {
	CloseoutID  int64         `json:"closeout_id"`
	HouseholdID int64         `json:"household_id"`
	CategoryID  sql.NullInt64 `json:"category_id"`
	GoalID      sql.NullInt64 `json:"goal_id"`
	Month       string        `json:"month"`
	AmountCents int64         `json:"amount_cents"`
}

func (q *Queries) InsertCloseoutAllocation(ctx context.Context, arg InsertCloseoutAllocationParams) error {
	_, err := q.db.ExecContext(ctx, insertCloseoutAllocation,
		arg.CloseoutID,
		arg.HouseholdID,
		arg.CategoryID,
		arg.GoalID,
		arg.Month,
		arg.AmountCents,
	)
	return err
}

const listCloseoutAllocations = `-- name: ListCloseoutAllocations :many
SELECT a.id, a.category_id, a.goal_id, a.month, a.amount_cents,
  COALESCE(c.name, g.name, '') AS name, COALESCE(c.icon, g.icon, '') AS icon
FROM closeout_allocations a
LEFT JOIN categories c ON c.id = a.category_id
LEFT JOIN goals g ON g.id = a.goal_id
WHERE a.closeout_id = ? ORDER BY a.id
`

type ListCloseoutAllocationsRow struct {
	ID          int64         `json:"id"`
	CategoryID  sql.NullInt64 `json:"category_id"`
	GoalID      sql.NullInt64 `json:"goal_id"`
	Month       string        `json:"month"`
	AmountCents int64         `json:"amount_cents"`
	Name        string        `json:"name"`
	Icon        string        `json:"icon"`
}

func (q *Queries) ListCloseoutAllocations(ctx context.Context, closeoutID int64) ([]ListCloseoutAllocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCloseoutAllocations, closeoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCloseoutAllocationsRow
	for rows.Next() {
		var i ListCloseoutAllocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.GoalID,
			&i.Month,
			&i.AmountCents,
			&i.Name,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCloseoutMonths = `-- name: ListCloseoutMonths :many
SELECT month FROM budget_closeouts WHERE household_id = ? ORDER BY month DESC
`

func (q *Queries) ListCloseoutMonths(ctx context.Context, householdID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCloseoutMonths, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var month string
		if err := rows.Scan(&month); err != nil {
			return nil, err
		}
		items = append(items, month)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCloseoutAnalysis = `-- name: SetCloseoutAnalysis :exec
UPDATE budget_closeouts SET analysis = ?, analysis_at = ? WHERE id = ? AND household_id = ?
`

type SetCloseoutAnalysisParams struct {
	Analysis    string        `json:"analysis"`
	AnalysisAt  sql.NullInt64 `json:"analysis_at"`
	ID          int64         `json:"id"`
	HouseholdID int64         `json:"household_id"`
}

func (q *Queries) SetCloseoutAnalysis(ctx context.Context, arg SetCloseoutAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, setCloseoutAnalysis,
		arg.Analysis,
		arg.AnalysisAt,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}
