// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email.sql

package db

import (
	"context"
	"database/sql"
)

const countOpenEmailMessages = `-- name: CountOpenEmailMessages :one
SELECT
    CAST(COALESCE(SUM(status = 'unrouted'), 0) AS INTEGER) AS unrouted,
    CAST(COALESCE(SUM(status = 'parse_failed'), 0) AS INTEGER) AS parse_failed
FROM email_messages WHERE household_id = ?
`

type CountOpenEmailMessagesRow struct {
	Unrouted    int64 `json:"unrouted"`
	ParseFailed int64 `json:"parse_failed"`
}

func (q *Queries) CountOpenEmailMessages(ctx context.Context, householdID int64) (CountOpenEmailMessagesRow, error) {
	row := q.db.QueryRowContext(ctx, countOpenEmailMessages, householdID)
	var i CountOpenEmailMessagesRow
	err := row.Scan(&i.Unrouted, &i.ParseFailed)
	return i, err
}

const deleteEmailFilter = `-- name: DeleteEmailFilter :exec
DELETE FROM email_filters WHERE id = ? AND household_id = ?
`

type DeleteEmailFilterParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteEmailFilter(ctx context.Context, arg DeleteEmailFilterParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmailFilter, arg.ID, arg.HouseholdID)
	return err
}

const deleteMailbox = `-- name: DeleteMailbox :exec
DELETE FROM email_mailboxes WHERE id = ? AND household_id = ?
`

type DeleteMailboxParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteMailbox(ctx context.Context, arg DeleteMailboxParams) error {
	_, err := q.db.ExecContext(ctx, deleteMailbox, arg.ID, arg.HouseholdID)
	return err
}

const flagTransactionForReview = `-- name: FlagTransactionForReview :exec
UPDATE transactions SET needs_review = 1 WHERE id = ? AND household_id = ?
`

type FlagTransactionForReviewParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) FlagTransactionForReview(ctx context.Context, arg FlagTransactionForReviewParams) error {
	_, err := q.db.ExecContext(ctx, flagTransactionForReview, arg.ID, arg.HouseholdID)
	return err
}

const getBillForEmail = `-- name: GetBillForEmail :one
SELECT id, household_id, account_id, kind, amount_cents, minimum_cents, date, summary, email_message_id, created_at FROM account_bills WHERE email_message_id = ? ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetBillForEmail(ctx context.Context, emailMessageID sql.NullInt64) (AccountBill, error) {
	row := q.db.QueryRowContext(ctx, getBillForEmail, emailMessageID)
	var i AccountBill
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Kind,
		&i.AmountCents,
		&i.MinimumCents,
		&i.Date,
		&i.Summary,
		&i.EmailMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailFilter = `-- name: GetEmailFilter :one
SELECT id, household_id, name, priority, enabled, sender, subject_match, body_match, use_regex, account_id, parser, custom_parser, sign, created_at, source, "action" FROM email_filters WHERE id = ? AND household_id = ?
`

type GetEmailFilterParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetEmailFilter(ctx context.Context, arg GetEmailFilterParams) (EmailFilter, error) {
	row := q.db.QueryRowContext(ctx, getEmailFilter, arg.ID, arg.HouseholdID)
	var i EmailFilter
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Priority,
		&i.Enabled,
		&i.Sender,
		&i.SubjectMatch,
		&i.BodyMatch,
		&i.UseRegex,
		&i.AccountID,
		&i.Parser,
		&i.CustomParser,
		&i.Sign,
		&i.CreatedAt,
		&i.Source,
		&i.Action,
	)
	return i, err
}

const getEmailMessage = `-- name: GetEmailMessage :one
SELECT id, household_id, mailbox_id, message_id, uid, from_addr, from_name, subject, received_at, body_text, status, filter_id, transaction_id, error, created_at, ai_status, ai_kind, ai_summary, ai_recipe, ai_facts, applied FROM email_messages WHERE id = ? AND household_id = ?
`

type GetEmailMessageParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetEmailMessage(ctx context.Context, arg GetEmailMessageParams) (EmailMessage, error) {
	row := q.db.QueryRowContext(ctx, getEmailMessage, arg.ID, arg.HouseholdID)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MailboxID,
		&i.MessageID,
		&i.Uid,
		&i.FromAddr,
		&i.FromName,
		&i.Subject,
		&i.ReceivedAt,
		&i.BodyText,
		&i.Status,
		&i.FilterID,
		&i.TransactionID,
		&i.Error,
		&i.CreatedAt,
		&i.AiStatus,
		&i.AiKind,
		&i.AiSummary,
		&i.AiRecipe,
		&i.AiFacts,
		&i.Applied,
	)
	return i, err
}

const getEmailMessageForTransaction = `-- name: GetEmailMessageForTransaction :one
SELECT id, from_addr, from_name, subject, received_at FROM email_messages WHERE transaction_id = ? LIMIT 1
`

type GetEmailMessageForTransactionRow struct {
	ID         int64  `json:"id"`
	FromAddr   string `json:"from_addr"`
	FromName   string `json:"from_name"`
	Subject    string `json:"subject"`
	ReceivedAt int64  `json:"received_at"`
}

func (q *Queries) GetEmailMessageForTransaction(ctx context.Context, transactionID sql.NullInt64) (GetEmailMessageForTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, getEmailMessageForTransaction, transactionID)
	var i GetEmailMessageForTransactionRow
	err := row.Scan(
		&i.ID,
		&i.FromAddr,
		&i.FromName,
		&i.Subject,
		&i.ReceivedAt,
	)
	return i, err
}

const getMailbox = `-- name: GetMailbox :one
SELECT id, household_id, name, host, port, security, username, password_enc, folder, enabled, uid_validity, last_uid, status, last_error, last_checked_at, created_at, ai_read, ai_senders FROM email_mailboxes WHERE id = ? AND household_id = ?
`

type GetMailboxParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetMailbox(ctx context.Context, arg GetMailboxParams) (EmailMailbox, error) {
	row := q.db.QueryRowContext(ctx, getMailbox, arg.ID, arg.HouseholdID)
	var i EmailMailbox
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Security,
		&i.Username,
		&i.PasswordEnc,
		&i.Folder,
		&i.Enabled,
		&i.UidValidity,
		&i.LastUid,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.AiRead,
		&i.AiSenders,
	)
	return i, err
}

const getMailboxByID = `-- name: GetMailboxByID :one
SELECT id, household_id, name, host, port, security, username, password_enc, folder, enabled, uid_validity, last_uid, status, last_error, last_checked_at, created_at, ai_read, ai_senders FROM email_mailboxes WHERE id = ?
`

func (q *Queries) GetMailboxByID(ctx context.Context, id int64) (EmailMailbox, error) {
	row := q.db.QueryRowContext(ctx, getMailboxByID, id)
	var i EmailMailbox
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Security,
		&i.Username,
		&i.PasswordEnc,
		&i.Folder,
		&i.Enabled,
		&i.UidValidity,
		&i.LastUid,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.AiRead,
		&i.AiSenders,
	)
	return i, err
}

const insertAIEmailFilter = `-- name: InsertAIEmailFilter :one
INSERT INTO email_filters (household_id, name, priority, enabled, sender, subject_match, body_match, use_regex,
    account_id, parser, custom_parser, sign, source, created_at)
VALUES (?, ?, ?, 1, ?, ?, ?, 0, ?, ?, ?, ?, 'ai', ?) RETURNING id, household_id, name, priority, enabled, sender, subject_match, body_match, use_regex, account_id, parser, custom_parser, sign, created_at, source, "action"
`

type InsertAIEmailFilterParams struct {
	HouseholdID  int64  `json:"household_id"`
	Name         string `json:"name"`
	Priority     int64  `json:"priority"`
	Sender       string `json:"sender"`
	SubjectMatch string `json:"subject_match"`
	BodyMatch    string `json:"body_match"`
	AccountID    int64  `json:"account_id"`
	Parser       string `json:"parser"`
	CustomParser string `json:"custom_parser"`
	Sign         string `json:"sign"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) InsertAIEmailFilter(ctx context.Context, arg InsertAIEmailFilterParams) (EmailFilter, error) {
	row := q.db.QueryRowContext(ctx, insertAIEmailFilter,
		arg.HouseholdID,
		arg.Name,
		arg.Priority,
		arg.Sender,
		arg.SubjectMatch,
		arg.BodyMatch,
		arg.AccountID,
		arg.Parser,
		arg.CustomParser,
		arg.Sign,
		arg.CreatedAt,
	)
	var i EmailFilter
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Priority,
		&i.Enabled,
		&i.Sender,
		&i.SubjectMatch,
		&i.BodyMatch,
		&i.UseRegex,
		&i.AccountID,
		&i.Parser,
		&i.CustomParser,
		&i.Sign,
		&i.CreatedAt,
		&i.Source,
		&i.Action,
	)
	return i, err
}

const insertAccountBill = `-- name: InsertAccountBill :one
INSERT INTO account_bills (household_id, account_id, kind, amount_cents, minimum_cents, date, summary, email_message_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, household_id, account_id, kind, amount_cents, minimum_cents, date, summary, email_message_id, created_at
`

type InsertAccountBillParams struct {
	HouseholdID    int64          `json:"household_id"`
	AccountID      sql.NullInt64  `json:"account_id"`
	Kind           string         `json:"kind"`
	AmountCents    sql.NullInt64  `json:"amount_cents"`
	MinimumCents   sql.NullInt64  `json:"minimum_cents"`
	Date           sql.NullString `json:"date"`
	Summary        string         `json:"summary"`
	EmailMessageID sql.NullInt64  `json:"email_message_id"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) InsertAccountBill(ctx context.Context, arg InsertAccountBillParams) (AccountBill, error) {
	row := q.db.QueryRowContext(ctx, insertAccountBill,
		arg.HouseholdID,
		arg.AccountID,
		arg.Kind,
		arg.AmountCents,
		arg.MinimumCents,
		arg.Date,
		arg.Summary,
		arg.EmailMessageID,
		arg.CreatedAt,
	)
	var i AccountBill
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Kind,
		&i.AmountCents,
		&i.MinimumCents,
		&i.Date,
		&i.Summary,
		&i.EmailMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const insertEmailFilter = `-- name: InsertEmailFilter :one
INSERT INTO email_filters (household_id, name, priority, enabled, sender, subject_match, body_match, use_regex,
    account_id, parser, custom_parser, sign, action, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, household_id, name, priority, enabled, sender, subject_match, body_match, use_regex, account_id, parser, custom_parser, sign, created_at, source, "action"
`

type InsertEmailFilterParams struct {
	HouseholdID  int64  `json:"household_id"`
	Name         string `json:"name"`
	Priority     int64  `json:"priority"`
	Enabled      int64  `json:"enabled"`
	Sender       string `json:"sender"`
	SubjectMatch string `json:"subject_match"`
	BodyMatch    string `json:"body_match"`
	UseRegex     int64  `json:"use_regex"`
	AccountID    int64  `json:"account_id"`
	Parser       string `json:"parser"`
	CustomParser string `json:"custom_parser"`
	Sign         string `json:"sign"`
	Action       string `json:"action"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) InsertEmailFilter(ctx context.Context, arg InsertEmailFilterParams) (EmailFilter, error) {
	row := q.db.QueryRowContext(ctx, insertEmailFilter,
		arg.HouseholdID,
		arg.Name,
		arg.Priority,
		arg.Enabled,
		arg.Sender,
		arg.SubjectMatch,
		arg.BodyMatch,
		arg.UseRegex,
		arg.AccountID,
		arg.Parser,
		arg.CustomParser,
		arg.Sign,
		arg.Action,
		arg.CreatedAt,
	)
	var i EmailFilter
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Priority,
		&i.Enabled,
		&i.Sender,
		&i.SubjectMatch,
		&i.BodyMatch,
		&i.UseRegex,
		&i.AccountID,
		&i.Parser,
		&i.CustomParser,
		&i.Sign,
		&i.CreatedAt,
		&i.Source,
		&i.Action,
	)
	return i, err
}

const insertEmailMessage = `-- name: InsertEmailMessage :one
INSERT INTO email_messages (household_id, mailbox_id, message_id, uid, from_addr, from_name, subject,
    received_at, body_text, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'unrouted', ?)
ON CONFLICT (household_id, message_id) DO NOTHING
RETURNING id
`

type InsertEmailMessageParams struct {
	HouseholdID int64         `json:"household_id"`
	MailboxID   sql.NullInt64 `json:"mailbox_id"`
	MessageID   string        `json:"message_id"`
	Uid         int64         `json:"uid"`
	FromAddr    string        `json:"from_addr"`
	FromName    string        `json:"from_name"`
	Subject     string        `json:"subject"`
	ReceivedAt  int64         `json:"received_at"`
	BodyText    string        `json:"body_text"`
	CreatedAt   int64         `json:"created_at"`
}

func (q *Queries) InsertEmailMessage(ctx context.Context, arg InsertEmailMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEmailMessage,
		arg.HouseholdID,
		arg.MailboxID,
		arg.MessageID,
		arg.Uid,
		arg.FromAddr,
		arg.FromName,
		arg.Subject,
		arg.ReceivedAt,
		arg.BodyText,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertEmailTransaction = `-- name: InsertEmailTransaction :one
INSERT INTO transactions (
    household_id, account_id, source, date, amount_cents, description, payee, pending, provisional,
    created_at, updated_at
) VALUES (?, ?, 'email', ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertEmailTransactionParams struct {
	HouseholdID int64  `json:"household_id"`
	AccountID   int64  `json:"account_id"`
	Date        string `json:"date"`
	AmountCents int64  `json:"amount_cents"`
	Description string `json:"description"`
	Payee       string `json:"payee"`
	Pending     int64  `json:"pending"`
	Provisional int64  `json:"provisional"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) InsertEmailTransaction(ctx context.Context, arg InsertEmailTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEmailTransaction,
		arg.HouseholdID,
		arg.AccountID,
		arg.Date,
		arg.AmountCents,
		arg.Description,
		arg.Payee,
		arg.Pending,
		arg.Provisional,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMailbox = `-- name: InsertMailbox :one
INSERT INTO email_mailboxes (household_id, name, host, port, security, username, password_enc, folder, enabled, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, household_id, name, host, port, security, username, password_enc, folder, enabled, uid_validity, last_uid, status, last_error, last_checked_at, created_at, ai_read, ai_senders
`

type InsertMailboxParams struct {
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Host        string `json:"host"`
	Port        int64  `json:"port"`
	Security    string `json:"security"`
	Username    string `json:"username"`
	PasswordEnc []byte `json:"password_enc"`
	Folder      string `json:"folder"`
	Enabled     int64  `json:"enabled"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) InsertMailbox(ctx context.Context, arg InsertMailboxParams) (EmailMailbox, error) {
	row := q.db.QueryRowContext(ctx, insertMailbox,
		arg.HouseholdID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Security,
		arg.Username,
		arg.PasswordEnc,
		arg.Folder,
		arg.Enabled,
		arg.CreatedAt,
	)
	var i EmailMailbox
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Security,
		&i.Username,
		&i.PasswordEnc,
		&i.Folder,
		&i.Enabled,
		&i.UidValidity,
		&i.LastUid,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.AiRead,
		&i.AiSenders,
	)
	return i, err
}

const listEmailFilters = `-- name: ListEmailFilters :many
SELECT id, household_id, name, priority, enabled, sender, subject_match, body_match, use_regex, account_id, parser, custom_parser, sign, created_at, source, "action" FROM email_filters WHERE household_id = ? ORDER BY priority, id
`

func (q *Queries) ListEmailFilters(ctx context.Context, householdID int64) ([]EmailFilter, error) {
	rows, err := q.db.QueryContext(ctx, listEmailFilters, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailFilter
	for rows.Next() {
		var i EmailFilter
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Priority,
			&i.Enabled,
			&i.Sender,
			&i.SubjectMatch,
			&i.BodyMatch,
			&i.UseRegex,
			&i.AccountID,
			&i.Parser,
			&i.CustomParser,
			&i.Sign,
			&i.CreatedAt,
			&i.Source,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailMessages = `-- name: ListEmailMessages :many
SELECT m.id, m.mailbox_id, m.from_addr, m.from_name, m.subject, m.received_at, m.status, m.filter_id,
    m.transaction_id, m.error, m.ai_status, m.ai_kind, m.ai_summary, m.ai_recipe, m.ai_facts, m.applied, COALESCE(f.name, '') AS filter_name
FROM email_messages m LEFT JOIN email_filters f ON f.id = m.filter_id
WHERE m.household_id = ?1 AND (?2 = '' OR m.status = ?2)
ORDER BY m.received_at DESC, m.id DESC
LIMIT ?3
`

type ListEmailMessagesParams struct {
	HouseholdID int64       `json:"household_id"`
	Status      interface{} `json:"status"`
	Lim         int64       `json:"lim"`
}

type ListEmailMessagesRow struct {
	ID            int64         `json:"id"`
	MailboxID     sql.NullInt64 `json:"mailbox_id"`
	FromAddr      string        `json:"from_addr"`
	FromName      string        `json:"from_name"`
	Subject       string        `json:"subject"`
	ReceivedAt    int64         `json:"received_at"`
	Status        string        `json:"status"`
	FilterID      sql.NullInt64 `json:"filter_id"`
	TransactionID sql.NullInt64 `json:"transaction_id"`
	Error         string        `json:"error"`
	AiStatus      string        `json:"ai_status"`
	AiKind        string        `json:"ai_kind"`
	AiSummary     string        `json:"ai_summary"`
	AiRecipe      string        `json:"ai_recipe"`
	AiFacts       string        `json:"ai_facts"`
	Applied       string        `json:"applied"`
	FilterName    string        `json:"filter_name"`
}

func (q *Queries) ListEmailMessages(ctx context.Context, arg ListEmailMessagesParams) ([]ListEmailMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmailMessages, arg.HouseholdID, arg.Status, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailMessagesRow
	for rows.Next() {
		var i ListEmailMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.MailboxID,
			&i.FromAddr,
			&i.FromName,
			&i.Subject,
			&i.ReceivedAt,
			&i.Status,
			&i.FilterID,
			&i.TransactionID,
			&i.Error,
			&i.AiStatus,
			&i.AiKind,
			&i.AiSummary,
			&i.AiRecipe,
			&i.AiFacts,
			&i.Applied,
			&i.FilterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledMailboxes = `-- name: ListEnabledMailboxes :many
SELECT id, household_id, name, host, port, security, username, password_enc, folder, enabled, uid_validity, last_uid, status, last_error, last_checked_at, created_at, ai_read, ai_senders FROM email_mailboxes WHERE enabled = 1 ORDER BY id
`

func (q *Queries) ListEnabledMailboxes(ctx context.Context) ([]EmailMailbox, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledMailboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailMailbox
	for rows.Next() {
		var i EmailMailbox
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Security,
			&i.Username,
			&i.PasswordEnc,
			&i.Folder,
			&i.Enabled,
			&i.UidValidity,
			&i.LastUid,
			&i.Status,
			&i.LastError,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.AiRead,
			&i.AiSenders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkTargets = `-- name: ListLinkTargets :many
SELECT t.id, t.date, t.amount_cents, t.description, t.payee, COALESCE(m.name, '') AS merchant_name
FROM transactions t LEFT JOIN merchants m ON m.id = t.merchant_id
WHERE t.account_id = ?1 AND t.provisional = 0
  AND t.amount_cents >= ?2 AND t.amount_cents <= ?3
  AND t.date >= ?4 AND t.date <= ?5
  AND NOT EXISTS (SELECT 1 FROM transactions p WHERE p.linked_txn_id = t.id)
  AND NOT EXISTS (SELECT 1 FROM link_blacklist b WHERE b.posted_id = t.id AND b.provisional_id = ?6)
`

type ListLinkTargetsParams struct {
	AccountID     int64  `json:"account_id"`
	AmountLo      int64  `json:"amount_lo"`
	AmountHi      int64  `json:"amount_hi"`
	DateLo        string `json:"date_lo"`
	DateHi        string `json:"date_hi"`
	ProvisionalID int64  `json:"provisional_id"`
}

type ListLinkTargetsRow struct {
	ID           int64  `json:"id"`
	Date         string `json:"date"`
	AmountCents  int64  `json:"amount_cents"`
	Description  string `json:"description"`
	Payee        string `json:"payee"`
	MerchantName string `json:"merchant_name"`
}

// Posted rows a new provisional entry could be linked to (the reverse of ListLinkCandidates,
// for an email alert that arrives after the bank already posted the purchase).
func (q *Queries) ListLinkTargets(ctx context.Context, arg ListLinkTargetsParams) ([]ListLinkTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinkTargets,
		arg.AccountID,
		arg.AmountLo,
		arg.AmountHi,
		arg.DateLo,
		arg.DateHi,
		arg.ProvisionalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkTargetsRow
	for rows.Next() {
		var i ListLinkTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.Description,
			&i.Payee,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxes = `-- name: ListMailboxes :many
SELECT id, household_id, name, host, port, security, username, password_enc, folder, enabled, uid_validity, last_uid, status, last_error, last_checked_at, created_at, ai_read, ai_senders FROM email_mailboxes WHERE household_id = ? ORDER BY id
`

func (q *Queries) ListMailboxes(ctx context.Context, householdID int64) ([]EmailMailbox, error) {
	rows, err := q.db.QueryContext(ctx, listMailboxes, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailMailbox
	for rows.Next() {
		var i EmailMailbox
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Security,
			&i.Username,
			&i.PasswordEnc,
			&i.Folder,
			&i.Enabled,
			&i.UidValidity,
			&i.LastUid,
			&i.Status,
			&i.LastError,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.AiRead,
			&i.AiSenders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAIEmails = `-- name: ListPendingAIEmails :many
SELECT id, household_id, mailbox_id, message_id, uid, from_addr, from_name, subject, received_at, body_text, status, filter_id, transaction_id, error, created_at, ai_status, ai_kind, ai_summary, ai_recipe, ai_facts, applied FROM email_messages WHERE ai_status = 'pending' AND status IN ('unrouted', 'parse_failed')
ORDER BY received_at, id LIMIT ?
`

// Unrouted messages waiting for the AI, oldest first.
func (q *Queries) ListPendingAIEmails(ctx context.Context, limit int64) ([]EmailMessage, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAIEmails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailMessage
	for rows.Next() {
		var i EmailMessage
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MailboxID,
			&i.MessageID,
			&i.Uid,
			&i.FromAddr,
			&i.FromName,
			&i.Subject,
			&i.ReceivedAt,
			&i.BodyText,
			&i.Status,
			&i.FilterID,
			&i.TransactionID,
			&i.Error,
			&i.CreatedAt,
			&i.AiStatus,
			&i.AiKind,
			&i.AiSummary,
			&i.AiRecipe,
			&i.AiFacts,
			&i.Applied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentBills = `-- name: ListRecentBills :many
SELECT id, household_id, account_id, kind, amount_cents, minimum_cents, date, summary, email_message_id, created_at FROM account_bills WHERE household_id = ? AND created_at >= ? ORDER BY created_at DESC, id DESC
`

type ListRecentBillsParams struct {
	HouseholdID int64 `json:"household_id"`
	CreatedAt   int64 `json:"created_at"`
}

// Bill events from the last 75 days, newest first.
func (q *Queries) ListRecentBills(ctx context.Context, arg ListRecentBillsParams) ([]AccountBill, error) {
	rows, err := q.db.QueryContext(ctx, listRecentBills, arg.HouseholdID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountBill
	for rows.Next() {
		var i AccountBill
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.AccountID,
			&i.Kind,
			&i.AmountCents,
			&i.MinimumCents,
			&i.Date,
			&i.Summary,
			&i.EmailMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEmailBodies = `-- name: ListRecentEmailBodies :many
SELECT id, household_id, mailbox_id, message_id, uid, from_addr, from_name, subject, received_at, body_text, status, filter_id, transaction_id, error, created_at, ai_status, ai_kind, ai_summary, ai_recipe, ai_facts, applied FROM email_messages
WHERE household_id = ?1 AND body_text != ''
  AND (?2 = 0 OR status IN ('unrouted', 'parse_failed'))
ORDER BY received_at DESC, id DESC
LIMIT ?3
`

type ListRecentEmailBodiesParams struct {
	HouseholdID int64       `json:"household_id"`
	OnlyOpen    interface{} `json:"only_open"`
	Lim         int64       `json:"lim"`
}

// Recent messages with bodies, for re-routing and filter previews.
func (q *Queries) ListRecentEmailBodies(ctx context.Context, arg ListRecentEmailBodiesParams) ([]EmailMessage, error) {
	rows, err := q.db.QueryContext(ctx, listRecentEmailBodies, arg.HouseholdID, arg.OnlyOpen, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailMessage
	for rows.Next() {
		var i EmailMessage
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MailboxID,
			&i.MessageID,
			&i.Uid,
			&i.FromAddr,
			&i.FromName,
			&i.Subject,
			&i.ReceivedAt,
			&i.BodyText,
			&i.Status,
			&i.FilterID,
			&i.TransactionID,
			&i.Error,
			&i.CreatedAt,
			&i.AiStatus,
			&i.AiKind,
			&i.AiSummary,
			&i.AiRecipe,
			&i.AiFacts,
			&i.Applied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextEmailFilterPriority = `-- name: NextEmailFilterPriority :one
SELECT CAST(COALESCE(MAX(priority), 0) + 1 AS INTEGER) FROM email_filters WHERE household_id = ?
`

func (q *Queries) NextEmailFilterPriority(ctx context.Context, householdID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextEmailFilterPriority, householdID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneEmailBodies = `-- name: PruneEmailBodies :exec
UPDATE email_messages SET body_text = '' WHERE received_at < ? AND body_text != ''
`

func (q *Queries) PruneEmailBodies(ctx context.Context, receivedAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneEmailBodies, receivedAt)
	return err
}

const resetMailboxCursor = `-- name: ResetMailboxCursor :exec
UPDATE email_mailboxes SET uid_validity = 0, last_uid = 0, status = 'new', last_error = '' WHERE id = ?
`

// Changing the server or folder starts over from a fresh UID window.
func (q *Queries) ResetMailboxCursor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetMailboxCursor, id)
	return err
}

const setEmailAIFacts = `-- name: SetEmailAIFacts :exec
UPDATE email_messages SET ai_facts = ? WHERE id = ?
`

type SetEmailAIFactsParams struct {
	AiFacts string `json:"ai_facts"`
	ID      int64  `json:"id"`
}

func (q *Queries) SetEmailAIFacts(ctx context.Context, arg SetEmailAIFactsParams) error {
	_, err := q.db.ExecContext(ctx, setEmailAIFacts, arg.AiFacts, arg.ID)
	return err
}

const setEmailAIRecipe = `-- name: SetEmailAIRecipe :exec
UPDATE email_messages SET ai_recipe = ? WHERE id = ?
`

type SetEmailAIRecipeParams struct {
	AiRecipe string `json:"ai_recipe"`
	ID       int64  `json:"id"`
}

func (q *Queries) SetEmailAIRecipe(ctx context.Context, arg SetEmailAIRecipeParams) error {
	_, err := q.db.ExecContext(ctx, setEmailAIRecipe, arg.AiRecipe, arg.ID)
	return err
}

const setEmailAIResult = `-- name: SetEmailAIResult :exec
UPDATE email_messages SET ai_status = ?, ai_kind = ?, ai_summary = ?, status = ? WHERE id = ?
`

type SetEmailAIResultParams struct {
	AiStatus  string `json:"ai_status"`
	AiKind    string `json:"ai_kind"`
	AiSummary string `json:"ai_summary"`
	Status    string `json:"status"`
	ID        int64  `json:"id"`
}

func (q *Queries) SetEmailAIResult(ctx context.Context, arg SetEmailAIResultParams) error {
	_, err := q.db.ExecContext(ctx, setEmailAIResult,
		arg.AiStatus,
		arg.AiKind,
		arg.AiSummary,
		arg.Status,
		arg.ID,
	)
	return err
}

const setEmailAIStatus = `-- name: SetEmailAIStatus :exec
UPDATE email_messages SET ai_status = ? WHERE id = ?
`

type SetEmailAIStatusParams struct {
	AiStatus string `json:"ai_status"`
	ID       int64  `json:"id"`
}

func (q *Queries) SetEmailAIStatus(ctx context.Context, arg SetEmailAIStatusParams) error {
	_, err := q.db.ExecContext(ctx, setEmailAIStatus, arg.AiStatus, arg.ID)
	return err
}

const setEmailApplied = `-- name: SetEmailApplied :exec
UPDATE email_messages SET status = ?, filter_id = ?, applied = ?, error = '' WHERE id = ?
`

type SetEmailAppliedParams struct {
	Status   string        `json:"status"`
	FilterID sql.NullInt64 `json:"filter_id"`
	Applied  string        `json:"applied"`
	ID       int64         `json:"id"`
}

// An email a filter or the user acted on without creating a transaction.
func (q *Queries) SetEmailApplied(ctx context.Context, arg SetEmailAppliedParams) error {
	_, err := q.db.ExecContext(ctx, setEmailApplied,
		arg.Status,
		arg.FilterID,
		arg.Applied,
		arg.ID,
	)
	return err
}

const setEmailMessageResult = `-- name: SetEmailMessageResult :exec
UPDATE email_messages SET status = ?, filter_id = ?, transaction_id = ?, error = ? WHERE id = ?
`

type SetEmailMessageResultParams struct {
	Status        string        `json:"status"`
	FilterID      sql.NullInt64 `json:"filter_id"`
	TransactionID sql.NullInt64 `json:"transaction_id"`
	Error         string        `json:"error"`
	ID            int64         `json:"id"`
}

func (q *Queries) SetEmailMessageResult(ctx context.Context, arg SetEmailMessageResultParams) error {
	_, err := q.db.ExecContext(ctx, setEmailMessageResult,
		arg.Status,
		arg.FilterID,
		arg.TransactionID,
		arg.Error,
		arg.ID,
	)
	return err
}

const setMailboxAI = `-- name: SetMailboxAI :exec

UPDATE email_mailboxes SET ai_read = ?, ai_senders = ? WHERE id = ? AND household_id = ?
`

type SetMailboxAIParams struct {
	AiRead      int64  `json:"ai_read"`
	AiSenders   string `json:"ai_senders"`
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
}

// ---- AI reading ----
func (q *Queries) SetMailboxAI(ctx context.Context, arg SetMailboxAIParams) error {
	_, err := q.db.ExecContext(ctx, setMailboxAI,
		arg.AiRead,
		arg.AiSenders,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const setMailboxCursor = `-- name: SetMailboxCursor :exec
UPDATE email_mailboxes SET uid_validity = ?, last_uid = ? WHERE id = ?
`

type SetMailboxCursorParams struct {
	UidValidity int64 `json:"uid_validity"`
	LastUid     int64 `json:"last_uid"`
	ID          int64 `json:"id"`
}

func (q *Queries) SetMailboxCursor(ctx context.Context, arg SetMailboxCursorParams) error {
	_, err := q.db.ExecContext(ctx, setMailboxCursor, arg.UidValidity, arg.LastUid, arg.ID)
	return err
}

const setMailboxStatus = `-- name: SetMailboxStatus :exec
UPDATE email_mailboxes SET status = ?, last_error = ?, last_checked_at = ? WHERE id = ?
`

type SetMailboxStatusParams struct {
	Status        string        `json:"status"`
	LastError     string        `json:"last_error"`
	LastCheckedAt sql.NullInt64 `json:"last_checked_at"`
	ID            int64         `json:"id"`
}

func (q *Queries) SetMailboxStatus(ctx context.Context, arg SetMailboxStatusParams) error {
	_, err := q.db.ExecContext(ctx, setMailboxStatus,
		arg.Status,
		arg.LastError,
		arg.LastCheckedAt,
		arg.ID,
	)
	return err
}

const updateAIEmailFilterParser = `-- name: UpdateAIEmailFilterParser :exec
UPDATE email_filters SET parser = ?, custom_parser = ? WHERE id = ? AND household_id = ? AND source = 'ai'
`

type UpdateAIEmailFilterParserParams struct {
	Parser       string `json:"parser"`
	CustomParser string `json:"custom_parser"`
	ID           int64  `json:"id"`
	HouseholdID  int64  `json:"household_id"`
}

// The AI may only rewrite how its own filters read values.
func (q *Queries) UpdateAIEmailFilterParser(ctx context.Context, arg UpdateAIEmailFilterParserParams) error {
	_, err := q.db.ExecContext(ctx, updateAIEmailFilterParser,
		arg.Parser,
		arg.CustomParser,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const updateEmailFilter = `-- name: UpdateEmailFilter :exec
UPDATE email_filters SET name = ?, priority = ?, enabled = ?, sender = ?, subject_match = ?, body_match = ?,
    use_regex = ?, account_id = ?, parser = ?, custom_parser = ?, sign = ?, action = ?, source = 'user'
WHERE id = ? AND household_id = ?
`

type UpdateEmailFilterParams struct {
	Name         string `json:"name"`
	Priority     int64  `json:"priority"`
	Enabled      int64  `json:"enabled"`
	Sender       string `json:"sender"`
	SubjectMatch string `json:"subject_match"`
	BodyMatch    string `json:"body_match"`
	UseRegex     int64  `json:"use_regex"`
	AccountID    int64  `json:"account_id"`
	Parser       string `json:"parser"`
	CustomParser string `json:"custom_parser"`
	Sign         string `json:"sign"`
	Action       string `json:"action"`
	ID           int64  `json:"id"`
	HouseholdID  int64  `json:"household_id"`
}

func (q *Queries) UpdateEmailFilter(ctx context.Context, arg UpdateEmailFilterParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailFilter,
		arg.Name,
		arg.Priority,
		arg.Enabled,
		arg.Sender,
		arg.SubjectMatch,
		arg.BodyMatch,
		arg.UseRegex,
		arg.AccountID,
		arg.Parser,
		arg.CustomParser,
		arg.Sign,
		arg.Action,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const updateMailbox = `-- name: UpdateMailbox :exec
UPDATE email_mailboxes SET name = ?, host = ?, port = ?, security = ?, username = ?, password_enc = ?, folder = ?, enabled = ?
WHERE id = ? AND household_id = ?
`

type UpdateMailboxParams struct {
	Name        string `json:"name"`
	Host        string `json:"host"`
	Port        int64  `json:"port"`
	Security    string `json:"security"`
	Username    string `json:"username"`
	PasswordEnc []byte `json:"password_enc"`
	Folder      string `json:"folder"`
	Enabled     int64  `json:"enabled"`
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
}

func (q *Queries) UpdateMailbox(ctx context.Context, arg UpdateMailboxParams) error {
	_, err := q.db.ExecContext(ctx, updateMailbox,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Security,
		arg.Username,
		arg.PasswordEnc,
		arg.Folder,
		arg.Enabled,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}
