// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package db

import (
	"context"
	"database/sql"
)

const enrichImportedMatch = `-- name: EnrichImportedMatch :exec
UPDATE transactions SET category_id = ?, category_source = ?, notes = ?, needs_review = ?, updated_at = ?
WHERE id = ?
`

type EnrichImportedMatchParams struct {
	CategoryID     sql.NullInt64 `json:"category_id"`
	CategorySource string        `json:"category_source"`
	Notes          string        `json:"notes"`
	NeedsReview    int64         `json:"needs_review"`
	UpdatedAt      int64         `json:"updated_at"`
	ID             int64         `json:"id"`
}

func (q *Queries) EnrichImportedMatch(ctx context.Context, arg EnrichImportedMatchParams) error {
	_, err := q.db.ExecContext(ctx, enrichImportedMatch,
		arg.CategoryID,
		arg.CategorySource,
		arg.Notes,
		arg.NeedsReview,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const importMatchCandidates = `-- name: ImportMatchCandidates :many
SELECT id, date, category_id, category_source, notes, needs_review FROM transactions
WHERE account_id = ?1 AND amount_cents = ?2
  AND date >= ?3 AND date <= ?4
  AND source != 'import' AND provisional = 0 AND linked_txn_id IS NULL
ORDER BY date, id
`

type ImportMatchCandidatesParams struct {
	AccountID   int64  `json:"account_id"`
	AmountCents int64  `json:"amount_cents"`
	FromDate    string `json:"from_date"`
	ToDate      string `json:"to_date"`
}

type ImportMatchCandidatesRow struct {
	ID             int64         `json:"id"`
	Date           string        `json:"date"`
	CategoryID     sql.NullInt64 `json:"category_id"`
	CategorySource string        `json:"category_source"`
	Notes          string        `json:"notes"`
	NeedsReview    int64         `json:"needs_review"`
}

// Transactions already in an account that an imported row may duplicate (same amount, close
// date). Imported and provisional rows are never candidates.
func (q *Queries) ImportMatchCandidates(ctx context.Context, arg ImportMatchCandidatesParams) ([]ImportMatchCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, importMatchCandidates,
		arg.AccountID,
		arg.AmountCents,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportMatchCandidatesRow
	for rows.Next() {
		var i ImportMatchCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.CategoryID,
			&i.CategorySource,
			&i.Notes,
			&i.NeedsReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importedExternalIDs = `-- name: ImportedExternalIDs :many

SELECT external_id FROM transactions
WHERE household_id = ? AND source = 'import' AND external_id IS NOT NULL
`

// ---- file import (Monarch) ----
func (q *Queries) ImportedExternalIDs(ctx context.Context, householdID int64) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, importedExternalIDs, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var external_id sql.NullString
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBalanceSnapshotIfMissing = `-- name: InsertBalanceSnapshotIfMissing :exec
INSERT INTO balance_snapshots (account_id, date, balance_cents) VALUES (?, ?, ?)
ON CONFLICT (account_id, date) DO NOTHING
`

type InsertBalanceSnapshotIfMissingParams struct {
	AccountID    int64  `json:"account_id"`
	Date         string `json:"date"`
	BalanceCents int64  `json:"balance_cents"`
}

func (q *Queries) InsertBalanceSnapshotIfMissing(ctx context.Context, arg InsertBalanceSnapshotIfMissingParams) error {
	_, err := q.db.ExecContext(ctx, insertBalanceSnapshotIfMissing, arg.AccountID, arg.Date, arg.BalanceCents)
	return err
}

const insertImportedTransaction = `-- name: InsertImportedTransaction :one
INSERT INTO transactions (
    household_id, account_id, external_id, source, date, amount_cents, description, payee,
    merchant_id, category_id, category_source, notes, needs_review, created_at, updated_at
) VALUES (?, ?, ?, 'import', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertImportedTransactionParams struct {
	HouseholdID    int64          `json:"household_id"`
	AccountID      int64          `json:"account_id"`
	ExternalID     sql.NullString `json:"external_id"`
	Date           string         `json:"date"`
	AmountCents    int64          `json:"amount_cents"`
	Description    string         `json:"description"`
	Payee          string         `json:"payee"`
	MerchantID     sql.NullInt64  `json:"merchant_id"`
	CategoryID     sql.NullInt64  `json:"category_id"`
	CategorySource string         `json:"category_source"`
	Notes          string         `json:"notes"`
	NeedsReview    int64          `json:"needs_review"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) InsertImportedTransaction(ctx context.Context, arg InsertImportedTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertImportedTransaction,
		arg.HouseholdID,
		arg.AccountID,
		arg.ExternalID,
		arg.Date,
		arg.AmountCents,
		arg.Description,
		arg.Payee,
		arg.MerchantID,
		arg.CategoryID,
		arg.CategorySource,
		arg.Notes,
		arg.NeedsReview,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
