// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Household struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

type HouseholdMember struct {
	HouseholdID int64  `json:"household_id"`
	UserID      int64  `json:"user_id"`
	Role        string `json:"role"`
}

type Session struct {
	TokenHash  []byte `json:"token_hash"`
	UserID     int64  `json:"user_id"`
	CreatedAt  int64  `json:"created_at"`
	ExpiresAt  int64  `json:"expires_at"`
	LastSeenAt int64  `json:"last_seen_at"`
	UserAgent  string `json:"user_agent"`
	Ip         string `json:"ip"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type User struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      int64  `json:"is_admin"`
	CreatedAt    int64  `json:"created_at"`
}
