// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Account struct {
	ID                int64          `json:"id"`
	HouseholdID       int64          `json:"household_id"`
	ConnectionID      sql.NullInt64  `json:"connection_id"`
	InstitutionID     sql.NullInt64  `json:"institution_id"`
	ExternalID        sql.NullString `json:"external_id"`
	InstitutionName   string         `json:"institution_name"`
	ProviderName      string         `json:"provider_name"`
	Name              string         `json:"name"`
	Mask              string         `json:"mask"`
	Type              string         `json:"type"`
	Currency          string         `json:"currency"`
	BalanceCents      int64          `json:"balance_cents"`
	AvailableCents    sql.NullInt64  `json:"available_cents"`
	BalanceAt         sql.NullInt64  `json:"balance_at"`
	Status            string         `json:"status"`
	ReviewCandidateID sql.NullInt64  `json:"review_candidate_id"`
	IncludeInNetWorth int64          `json:"include_in_net_worth"`
	Hidden            int64          `json:"hidden"`
	OwnerUserID       sql.NullInt64  `json:"owner_user_id"`
	IsManual          int64          `json:"is_manual"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
	Builtin           string         `json:"builtin"`
}

type AccountBill struct {
	ID             int64          `json:"id"`
	HouseholdID    int64          `json:"household_id"`
	AccountID      sql.NullInt64  `json:"account_id"`
	Kind           string         `json:"kind"`
	AmountCents    sql.NullInt64  `json:"amount_cents"`
	MinimumCents   sql.NullInt64  `json:"minimum_cents"`
	Date           sql.NullString `json:"date"`
	Summary        string         `json:"summary"`
	EmailMessageID sql.NullInt64  `json:"email_message_id"`
	CreatedAt      int64          `json:"created_at"`
}

type BalanceSnapshot struct {
	AccountID    int64  `json:"account_id"`
	Date         string `json:"date"`
	BalanceCents int64  `json:"balance_cents"`
}

type BudgetAmount struct {
	ID          int64         `json:"id"`
	HouseholdID int64         `json:"household_id"`
	CategoryID  sql.NullInt64 `json:"category_id"`
	GoalID      sql.NullInt64 `json:"goal_id"`
	Month       string        `json:"month"`
	AmountCents int64         `json:"amount_cents"`
	Forward     int64         `json:"forward"`
}

type Category struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	GroupID     int64  `json:"group_id"`
	Name        string `json:"name"`
	Icon        string `json:"icon"`
	Sort        int64  `json:"sort"`
	Archived    int64  `json:"archived"`
	Chunk       string `json:"chunk"`
}

type CategoryGroup struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	Sort        int64  `json:"sort"`
}

type ChatMessage struct {
	ID         int64  `json:"id"`
	ThreadID   int64  `json:"thread_id"`
	Role       string `json:"role"`
	Content    string `json:"content"`
	ToolCalls  string `json:"tool_calls"`
	ToolCallID string `json:"tool_call_id"`
	CreatedAt  int64  `json:"created_at"`
}

type ChatThread struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	Title     string `json:"title"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Connection struct {
	ID            int64         `json:"id"`
	HouseholdID   int64         `json:"household_id"`
	Provider      string        `json:"provider"`
	Name          string        `json:"name"`
	SecretEnc     []byte        `json:"secret_enc"`
	Status        string        `json:"status"`
	LastError     string        `json:"last_error"`
	LastSyncAt    sql.NullInt64 `json:"last_sync_at"`
	SyncedThrough sql.NullInt64 `json:"synced_through"`
	NextSyncAt    sql.NullInt64 `json:"next_sync_at"`
	RequestsDay   string        `json:"requests_day"`
	RequestsCount int64         `json:"requests_count"`
	CreatedAt     int64         `json:"created_at"`
}

type EmailFilter struct {
	ID           int64  `json:"id"`
	HouseholdID  int64  `json:"household_id"`
	Name         string `json:"name"`
	Priority     int64  `json:"priority"`
	Enabled      int64  `json:"enabled"`
	Sender       string `json:"sender"`
	SubjectMatch string `json:"subject_match"`
	BodyMatch    string `json:"body_match"`
	UseRegex     int64  `json:"use_regex"`
	AccountID    int64  `json:"account_id"`
	Parser       string `json:"parser"`
	CustomParser string `json:"custom_parser"`
	Sign         string `json:"sign"`
	CreatedAt    int64  `json:"created_at"`
}

type EmailMailbox struct {
	ID            int64         `json:"id"`
	HouseholdID   int64         `json:"household_id"`
	Name          string        `json:"name"`
	Host          string        `json:"host"`
	Port          int64         `json:"port"`
	Security      string        `json:"security"`
	Username      string        `json:"username"`
	PasswordEnc   []byte        `json:"password_enc"`
	Folder        string        `json:"folder"`
	Enabled       int64         `json:"enabled"`
	UidValidity   int64         `json:"uid_validity"`
	LastUid       int64         `json:"last_uid"`
	Status        string        `json:"status"`
	LastError     string        `json:"last_error"`
	LastCheckedAt sql.NullInt64 `json:"last_checked_at"`
	CreatedAt     int64         `json:"created_at"`
	AiRead        int64         `json:"ai_read"`
	AiSenders     string        `json:"ai_senders"`
}

type EmailMessage struct {
	ID            int64         `json:"id"`
	HouseholdID   int64         `json:"household_id"`
	MailboxID     sql.NullInt64 `json:"mailbox_id"`
	MessageID     string        `json:"message_id"`
	Uid           int64         `json:"uid"`
	FromAddr      string        `json:"from_addr"`
	FromName      string        `json:"from_name"`
	Subject       string        `json:"subject"`
	ReceivedAt    int64         `json:"received_at"`
	BodyText      string        `json:"body_text"`
	Status        string        `json:"status"`
	FilterID      sql.NullInt64 `json:"filter_id"`
	TransactionID sql.NullInt64 `json:"transaction_id"`
	Error         string        `json:"error"`
	CreatedAt     int64         `json:"created_at"`
	AiStatus      string        `json:"ai_status"`
	AiKind        string        `json:"ai_kind"`
	AiSummary     string        `json:"ai_summary"`
}

type Goal struct {
	ID            int64          `json:"id"`
	HouseholdID   int64          `json:"household_id"`
	Name          string         `json:"name"`
	Icon          string         `json:"icon"`
	TargetCents   int64          `json:"target_cents"`
	TargetDate    sql.NullString `json:"target_date"`
	StartingCents int64          `json:"starting_cents"`
	Archived      int64          `json:"archived"`
	Sort          int64          `json:"sort"`
	CreatedAt     int64          `json:"created_at"`
}

type Household struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

type HouseholdMember struct {
	HouseholdID int64  `json:"household_id"`
	UserID      int64  `json:"user_id"`
	Role        string `json:"role"`
}

type HouseholdSetting struct {
	HouseholdID int64  `json:"household_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
}

type Institution struct {
	ID           int64  `json:"id"`
	ConnectionID int64  `json:"connection_id"`
	ExternalID   string `json:"external_id"`
	Name         string `json:"name"`
	Url          string `json:"url"`
	Status       string `json:"status"`
	LastError    string `json:"last_error"`
}

type LinkBlacklist struct {
	ProvisionalID int64 `json:"provisional_id"`
	PostedID      int64 `json:"posted_id"`
}

type Merchant struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Normalized  string `json:"normalized"`
}

type Notification struct {
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
	Kind      string        `json:"kind"`
	DedupeKey string        `json:"dedupe_key"`
	Title     string        `json:"title"`
	Body      string        `json:"body"`
	Url       string        `json:"url"`
	CreatedAt int64         `json:"created_at"`
	ReadAt    sql.NullInt64 `json:"read_at"`
}

type NotificationPref struct {
	UserID int64  `json:"user_id"`
	Prefs  string `json:"prefs"`
}

type PushSubscription struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	Endpoint  string `json:"endpoint"`
	P256dh    string `json:"p256dh"`
	Auth      string `json:"auth"`
	UserAgent string `json:"user_agent"`
	CreatedAt int64  `json:"created_at"`
}

type RecurringDismissed struct {
	HouseholdID int64  `json:"household_id"`
	Key         string `json:"key"`
}

type Rule struct {
	ID            int64         `json:"id"`
	HouseholdID   int64         `json:"household_id"`
	Priority      int64         `json:"priority"`
	MatchField    string        `json:"match_field"`
	MatchOp       string        `json:"match_op"`
	MatchValue    string        `json:"match_value"`
	AccountID     sql.NullInt64 `json:"account_id"`
	AmountMin     sql.NullInt64 `json:"amount_min"`
	AmountMax     sql.NullInt64 `json:"amount_max"`
	SetCategoryID sql.NullInt64 `json:"set_category_id"`
	SetMerchant   string        `json:"set_merchant"`
	AddTagID      sql.NullInt64 `json:"add_tag_id"`
	SetHidden     int64         `json:"set_hidden"`
	CreatedAt     int64         `json:"created_at"`
}

type Session struct {
	TokenHash  []byte `json:"token_hash"`
	UserID     int64  `json:"user_id"`
	CreatedAt  int64  `json:"created_at"`
	ExpiresAt  int64  `json:"expires_at"`
	LastSeenAt int64  `json:"last_seen_at"`
	UserAgent  string `json:"user_agent"`
	Ip         string `json:"ip"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SyncEvent struct {
	ID           int64         `json:"id"`
	ConnectionID int64         `json:"connection_id"`
	At           int64         `json:"at"`
	Kind         string        `json:"kind"`
	AccountID    sql.NullInt64 `json:"account_id"`
	Message      string        `json:"message"`
}

type Tag struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
}

type Transaction struct {
	ID             int64          `json:"id"`
	HouseholdID    int64          `json:"household_id"`
	AccountID      int64          `json:"account_id"`
	ExternalID     sql.NullString `json:"external_id"`
	Source         string         `json:"source"`
	Date           string         `json:"date"`
	AmountCents    int64          `json:"amount_cents"`
	Description    string         `json:"description"`
	Payee          string         `json:"payee"`
	Memo           string         `json:"memo"`
	Pending        int64          `json:"pending"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	MerchantID     sql.NullInt64  `json:"merchant_id"`
	CategoryID     sql.NullInt64  `json:"category_id"`
	CategorySource string         `json:"category_source"`
	Notes          string         `json:"notes"`
	Hidden         int64          `json:"hidden"`
	NeedsReview    int64          `json:"needs_review"`
	Provisional    int64          `json:"provisional"`
	LinkedTxnID    sql.NullInt64  `json:"linked_txn_id"`
	LinkedAt       sql.NullInt64  `json:"linked_at"`
	GoalID         sql.NullInt64  `json:"goal_id"`
	OwnerUserID    sql.NullInt64  `json:"owner_user_id"`
}

type TransactionTag struct {
	TransactionID int64 `json:"transaction_id"`
	TagID         int64 `json:"tag_id"`
}

type User struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      int64  `json:"is_admin"`
	CreatedAt    int64  `json:"created_at"`
}
