// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package db

import (
	"context"
	"database/sql"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = ? AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePushEndpoint = `-- name: DeletePushEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = ?
`

func (q *Queries) DeletePushEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.ExecContext(ctx, deletePushEndpoint, endpoint)
	return err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE id = ? AND user_id = ?
`

type DeletePushSubscriptionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscription, arg.ID, arg.UserID)
	return err
}

const getNotificationPrefs = `-- name: GetNotificationPrefs :one

SELECT prefs FROM notification_prefs WHERE user_id = ?
`

// ---- prefs ----
func (q *Queries) GetNotificationPrefs(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPrefs, userID)
	var prefs string
	err := row.Scan(&prefs)
	return prefs, err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notifications (user_id, kind, dedupe_key, title, body, url, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, dedupe_key) DO NOTHING
RETURNING id, user_id, kind, dedupe_key, title, body, url, created_at, read_at
`

type InsertNotificationParams struct {
	UserID    int64  `json:"user_id"`
	Kind      string `json:"kind"`
	DedupeKey string `json:"dedupe_key"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Url       string `json:"url"`
	CreatedAt int64  `json:"created_at"`
}

// ---- notifications ----
// Returns no row when the dedupe key was already used.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.UserID,
		arg.Kind,
		arg.DedupeKey,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.DedupeKey,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listBrokenAccounts = `-- name: ListBrokenAccounts :many
SELECT a.id, a.name, a.status, CAST(COALESCE(i.status, '') AS TEXT) AS institution_status,
    CAST(COALESCE((SELECT MAX(e.at) FROM sync_events e
        WHERE e.connection_id = a.connection_id AND e.kind IN ('account_disconnected', 'reauth')), 0) AS INTEGER) AS since
FROM accounts a LEFT JOIN institutions i ON i.id = a.institution_id
WHERE a.household_id = ? AND a.hidden = 0
  AND (a.status = 'disconnected' OR (a.status = 'active' AND i.status = 'reauth'))
`

type ListBrokenAccountsRow struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	Status            string `json:"status"`
	InstitutionStatus string `json:"institution_status"`
	Since             int64  `json:"since"`
}

// Accounts that stopped syncing: dropped from the connection, or their institution needs a
// new login. since = when it happened (latest matching sync event).
func (q *Queries) ListBrokenAccounts(ctx context.Context, householdID int64) ([]ListBrokenAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBrokenAccounts, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBrokenAccountsRow
	for rows.Next() {
		var i ListBrokenAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.InstitutionStatus,
			&i.Since,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdUsers = `-- name: ListHouseholdUsers :many
SELECT u.id, u.email, u.name, u.password_hash, u.is_admin, u.created_at FROM users u JOIN household_members m ON m.user_id = u.id
WHERE m.household_id = ? ORDER BY u.id
`

func (q *Queries) ListHouseholdUsers(ctx context.Context, householdID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholdUsers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLargeTransactions = `-- name: ListLargeTransactions :many

SELECT t.id, t.date, t.amount_cents, t.source, a.name AS account_name,
    CAST(COALESCE(m.name, NULLIF(t.payee, ''), t.description) AS TEXT) AS merchant
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN merchants m ON m.id = t.merchant_id
WHERE t.household_id = ?1 AND t.created_at >= ?2
  AND t.date >= ?3 AND t.amount_cents <= ?4
  AND t.source != 'manual' AND t.hidden = 0 AND t.linked_txn_id IS NULL AND a.status != 'ignored'
  AND NOT EXISTS (SELECT 1 FROM transactions p WHERE p.linked_txn_id = t.id)
ORDER BY t.id
`

type ListLargeTransactionsParams struct {
	HouseholdID  int64  `json:"household_id"`
	CreatedSince int64  `json:"created_since"`
	FromDate     string `json:"from_date"`
	MaxAmount    int64  `json:"max_amount"`
}

type ListLargeTransactionsRow struct {
	ID          int64  `json:"id"`
	Date        string `json:"date"`
	AmountCents int64  `json:"amount_cents"`
	Source      string `json:"source"`
	AccountName string `json:"account_name"`
	Merchant    string `json:"merchant"`
}

// ---- evaluator inputs ----
// Recent large money-out transactions nobody entered by hand: new since created_since, dated
// on/after from_date, not hidden, not a linked provisional row, and not the posted twin of a
// pending/email row (that one already alerted or was entered by the user).
func (q *Queries) ListLargeTransactions(ctx context.Context, arg ListLargeTransactionsParams) ([]ListLargeTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLargeTransactions,
		arg.HouseholdID,
		arg.CreatedSince,
		arg.FromDate,
		arg.MaxAmount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLargeTransactionsRow
	for rows.Next() {
		var i ListLargeTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.Source,
			&i.AccountName,
			&i.Merchant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, kind, dedupe_key, title, body, url, created_at, read_at FROM notifications WHERE user_id = ? ORDER BY created_at DESC, id DESC LIMIT ?
`

type ListNotificationsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.DedupeKey,
			&i.Title,
			&i.Body,
			&i.Url,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at FROM push_subscriptions WHERE user_id = ? ORDER BY id
`

func (q *Queries) ListPushSubscriptions(ctx context.Context, userID int64) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read_at = ? WHERE user_id = ? AND read_at IS NULL
`

type MarkNotificationsReadParams struct {
	ReadAt sql.NullInt64 `json:"read_at"`
	UserID int64         `json:"user_id"`
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationsRead, arg.ReadAt, arg.UserID)
	return err
}

const pruneNotifications = `-- name: PruneNotifications :exec
DELETE FROM notifications WHERE created_at < ?
`

func (q *Queries) PruneNotifications(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneNotifications, createdAt)
	return err
}

const setNotificationPrefs = `-- name: SetNotificationPrefs :exec
INSERT INTO notification_prefs (user_id, prefs) VALUES (?, ?)
ON CONFLICT (user_id) DO UPDATE SET prefs = excluded.prefs
`

type SetNotificationPrefsParams struct {
	UserID int64  `json:"user_id"`
	Prefs  string `json:"prefs"`
}

func (q *Queries) SetNotificationPrefs(ctx context.Context, arg SetNotificationPrefsParams) error {
	_, err := q.db.ExecContext(ctx, setNotificationPrefs, arg.UserID, arg.Prefs)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one

INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (endpoint) DO UPDATE SET user_id = excluded.user_id, p256dh = excluded.p256dh,
    auth = excluded.auth, user_agent = excluded.user_agent
RETURNING id, user_id, endpoint, p256dh, auth, user_agent, created_at
`

type UpsertPushSubscriptionParams struct {
	UserID    int64  `json:"user_id"`
	Endpoint  string `json:"endpoint"`
	P256dh    string `json:"p256dh"`
	Auth      string `json:"auth"`
	UserAgent string `json:"user_agent"`
	CreatedAt int64  `json:"created_at"`
}

// ---- push subscriptions ----
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
		arg.CreatedAt,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
