// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package db

import (
	"context"
	"database/sql"
)

const createNetworthAnnotation = `-- name: CreateNetworthAnnotation :one
INSERT INTO networth_annotations (household_id, date, label, icon, transaction_id, created_at)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type CreateNetworthAnnotationParams struct {
	HouseholdID   int64         `json:"household_id"`
	Date          string        `json:"date"`
	Label         string        `json:"label"`
	Icon          string        `json:"icon"`
	TransactionID sql.NullInt64 `json:"transaction_id"`
	CreatedAt     int64         `json:"created_at"`
}

func (q *Queries) CreateNetworthAnnotation(ctx context.Context, arg CreateNetworthAnnotationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createNetworthAnnotation,
		arg.HouseholdID,
		arg.Date,
		arg.Label,
		arg.Icon,
		arg.TransactionID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createRecurringItem = `-- name: CreateRecurringItem :one
INSERT INTO recurring_items (household_id, name, merchant_id, match_text, account_id, category_id,
    amount_cents, amount_varies, cadence, anchor_date, day2, series_key, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, household_id, name, merchant_id, match_text, account_id, category_id, amount_cents, amount_varies, cadence, anchor_date, day2, series_key, created_at, updated_at
`

type CreateRecurringItemParams struct {
	HouseholdID  int64         `json:"household_id"`
	Name         string        `json:"name"`
	MerchantID   sql.NullInt64 `json:"merchant_id"`
	MatchText    string        `json:"match_text"`
	AccountID    sql.NullInt64 `json:"account_id"`
	CategoryID   sql.NullInt64 `json:"category_id"`
	AmountCents  int64         `json:"amount_cents"`
	AmountVaries int64         `json:"amount_varies"`
	Cadence      string        `json:"cadence"`
	AnchorDate   string        `json:"anchor_date"`
	Day2         int64         `json:"day2"`
	SeriesKey    string        `json:"series_key"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
}

func (q *Queries) CreateRecurringItem(ctx context.Context, arg CreateRecurringItemParams) (RecurringItem, error) {
	row := q.db.QueryRowContext(ctx, createRecurringItem,
		arg.HouseholdID,
		arg.Name,
		arg.MerchantID,
		arg.MatchText,
		arg.AccountID,
		arg.CategoryID,
		arg.AmountCents,
		arg.AmountVaries,
		arg.Cadence,
		arg.AnchorDate,
		arg.Day2,
		arg.SeriesKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RecurringItem
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.MerchantID,
		&i.MatchText,
		&i.AccountID,
		&i.CategoryID,
		&i.AmountCents,
		&i.AmountVaries,
		&i.Cadence,
		&i.AnchorDate,
		&i.Day2,
		&i.SeriesKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNetworthAnnotation = `-- name: DeleteNetworthAnnotation :execrows
DELETE FROM networth_annotations WHERE id = ? AND household_id = ?
`

type DeleteNetworthAnnotationParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteNetworthAnnotation(ctx context.Context, arg DeleteNetworthAnnotationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNetworthAnnotation, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRecurringItem = `-- name: DeleteRecurringItem :execrows
DELETE FROM recurring_items WHERE id = ? AND household_id = ?
`

type DeleteRecurringItemParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteRecurringItem(ctx context.Context, arg DeleteRecurringItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecurringItem, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRecurringItem = `-- name: GetRecurringItem :one
SELECT id, household_id, name, merchant_id, match_text, account_id, category_id, amount_cents, amount_varies, cadence, anchor_date, day2, series_key, created_at, updated_at FROM recurring_items WHERE id = ? AND household_id = ?
`

type GetRecurringItemParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetRecurringItem(ctx context.Context, arg GetRecurringItemParams) (RecurringItem, error) {
	row := q.db.QueryRowContext(ctx, getRecurringItem, arg.ID, arg.HouseholdID)
	var i RecurringItem
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.MerchantID,
		&i.MatchText,
		&i.AccountID,
		&i.CategoryID,
		&i.AmountCents,
		&i.AmountVaries,
		&i.Cadence,
		&i.AnchorDate,
		&i.Day2,
		&i.SeriesKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNetworthAnnotations = `-- name: ListNetworthAnnotations :many
SELECT n.id, n.date, n.label, n.icon, n.transaction_id,
    CAST(COALESCE(m.name, NULLIF(t.payee, ''), t.description, '') AS TEXT) AS txn_name,
    COALESCE(t.amount_cents, 0) AS txn_amount, COALESCE(t.date, '') AS txn_date
FROM networth_annotations n
LEFT JOIN transactions t ON t.id = n.transaction_id
LEFT JOIN merchants m ON m.id = t.merchant_id
WHERE n.household_id = ?
ORDER BY n.date, n.id
`

type ListNetworthAnnotationsRow struct {
	ID            int64         `json:"id"`
	Date          string        `json:"date"`
	Label         string        `json:"label"`
	Icon          string        `json:"icon"`
	TransactionID sql.NullInt64 `json:"transaction_id"`
	TxnName       string        `json:"txn_name"`
	TxnAmount     int64         `json:"txn_amount"`
	TxnDate       string        `json:"txn_date"`
}

func (q *Queries) ListNetworthAnnotations(ctx context.Context, householdID int64) ([]ListNetworthAnnotationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetworthAnnotations, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNetworthAnnotationsRow
	for rows.Next() {
		var i ListNetworthAnnotationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Label,
			&i.Icon,
			&i.TransactionID,
			&i.TxnName,
			&i.TxnAmount,
			&i.TxnDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringItems = `-- name: ListRecurringItems :many
SELECT id, household_id, name, merchant_id, match_text, account_id, category_id, amount_cents, amount_varies, cadence, anchor_date, day2, series_key, created_at, updated_at FROM recurring_items WHERE household_id = ? ORDER BY id
`

func (q *Queries) ListRecurringItems(ctx context.Context, householdID int64) ([]RecurringItem, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringItems, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringItem
	for rows.Next() {
		var i RecurringItem
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.MerchantID,
			&i.MatchText,
			&i.AccountID,
			&i.CategoryID,
			&i.AmountCents,
			&i.AmountVaries,
			&i.Cadence,
			&i.AnchorDate,
			&i.Day2,
			&i.SeriesKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNetworthAnnotation = `-- name: UpdateNetworthAnnotation :execrows
UPDATE networth_annotations SET date = ?, label = ?, icon = ?, transaction_id = ?
WHERE id = ? AND household_id = ?
`

type UpdateNetworthAnnotationParams struct {
	Date          string        `json:"date"`
	Label         string        `json:"label"`
	Icon          string        `json:"icon"`
	TransactionID sql.NullInt64 `json:"transaction_id"`
	ID            int64         `json:"id"`
	HouseholdID   int64         `json:"household_id"`
}

func (q *Queries) UpdateNetworthAnnotation(ctx context.Context, arg UpdateNetworthAnnotationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNetworthAnnotation,
		arg.Date,
		arg.Label,
		arg.Icon,
		arg.TransactionID,
		arg.ID,
		arg.HouseholdID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRecurringItem = `-- name: UpdateRecurringItem :exec
UPDATE recurring_items SET name = ?, merchant_id = ?, match_text = ?, account_id = ?, category_id = ?,
    amount_cents = ?, amount_varies = ?, cadence = ?, anchor_date = ?, day2 = ?, updated_at = ?
WHERE id = ? AND household_id = ?
`

type UpdateRecurringItemParams struct {
	Name         string        `json:"name"`
	MerchantID   sql.NullInt64 `json:"merchant_id"`
	MatchText    string        `json:"match_text"`
	AccountID    sql.NullInt64 `json:"account_id"`
	CategoryID   sql.NullInt64 `json:"category_id"`
	AmountCents  int64         `json:"amount_cents"`
	AmountVaries int64         `json:"amount_varies"`
	Cadence      string        `json:"cadence"`
	AnchorDate   string        `json:"anchor_date"`
	Day2         int64         `json:"day2"`
	UpdatedAt    int64         `json:"updated_at"`
	ID           int64         `json:"id"`
	HouseholdID  int64         `json:"household_id"`
}

func (q *Queries) UpdateRecurringItem(ctx context.Context, arg UpdateRecurringItemParams) error {
	_, err := q.db.ExecContext(ctx, updateRecurringItem,
		arg.Name,
		arg.MerchantID,
		arg.MatchText,
		arg.AccountID,
		arg.CategoryID,
		arg.AmountCents,
		arg.AmountVaries,
		arg.Cadence,
		arg.AnchorDate,
		arg.Day2,
		arg.UpdatedAt,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}
