// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"database/sql"
)

const dismissRecurring = `-- name: DismissRecurring :exec
INSERT OR IGNORE INTO recurring_dismissed (household_id, key) VALUES (?, ?)
`

type DismissRecurringParams struct {
	HouseholdID int64  `json:"household_id"`
	Key         string `json:"key"`
}

func (q *Queries) DismissRecurring(ctx context.Context, arg DismissRecurringParams) error {
	_, err := q.db.ExecContext(ctx, dismissRecurring, arg.HouseholdID, arg.Key)
	return err
}

const firstTransactionDate = `-- name: FirstTransactionDate :one
SELECT CAST(COALESCE(MIN(date), '') AS TEXT) FROM transactions WHERE household_id = ? AND hidden = 0
`

func (q *Queries) FirstTransactionDate(ctx context.Context, householdID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, firstTransactionDate, householdID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const interestCharges = `-- name: InterestCharges :many
SELECT t.account_id, CAST(SUM(-t.amount_cents) AS INTEGER) AS total
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.household_id = ?1 AND t.date >= ?2 AND t.amount_cents < 0
  AND t.hidden = 0 AND t.linked_txn_id IS NULL
  AND a.type IN ('credit_card', 'loan', 'mortgage', 'other_liability')
  AND (LOWER(t.description) LIKE '%interest%' OR LOWER(t.description) LIKE '%finance charge%')
GROUP BY t.account_id
`

type InterestChargesParams struct {
	HouseholdID int64  `json:"household_id"`
	FromDate    string `json:"from_date"`
}

type InterestChargesRow struct {
	AccountID int64 `json:"account_id"`
	Total     int64 `json:"total"`
}

// Interest and finance charges posted to debt accounts since a date, per account.
func (q *Queries) InterestCharges(ctx context.Context, arg InterestChargesParams) ([]InterestChargesRow, error) {
	rows, err := q.db.QueryContext(ctx, interestCharges, arg.HouseholdID, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterestChargesRow
	for rows.Next() {
		var i InterestChargesRow
		if err := rows.Scan(&i.AccountID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringDismissed = `-- name: ListRecurringDismissed :many
SELECT key FROM recurring_dismissed WHERE household_id = ?
`

func (q *Queries) ListRecurringDismissed(ctx context.Context, householdID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringDismissed, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recurringCandidates = `-- name: RecurringCandidates :many

SELECT t.id, t.date, t.amount_cents, t.merchant_id, t.description,
    CAST(COALESCE(m.name, NULLIF(t.payee, ''), t.description) AS TEXT) AS merchant,
    t.category_id, COALESCE(c.name, '') AS category_name, COALESCE(c.icon, '') AS category_icon,
    t.account_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN merchants m ON m.id = t.merchant_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN category_groups g ON g.id = c.group_id
WHERE t.household_id = ?1 AND t.date >= ?2
  AND t.hidden = 0 AND t.linked_txn_id IS NULL AND a.status != 'ignored'
  AND COALESCE(g.kind, '') != 'transfer'
ORDER BY t.date, t.id
`

type RecurringCandidatesParams struct {
	HouseholdID int64  `json:"household_id"`
	FromDate    string `json:"from_date"`
}

type RecurringCandidatesRow struct {
	ID           int64         `json:"id"`
	Date         string        `json:"date"`
	AmountCents  int64         `json:"amount_cents"`
	MerchantID   sql.NullInt64 `json:"merchant_id"`
	Description  string        `json:"description"`
	Merchant     string        `json:"merchant"`
	CategoryID   sql.NullInt64 `json:"category_id"`
	CategoryName string        `json:"category_name"`
	CategoryIcon string        `json:"category_icon"`
	AccountID    int64         `json:"account_id"`
	AccountName  string        `json:"account_name"`
}

// ---- recurring ----
// History the recurring detector reads: non-transfer, visible, unlinked rows since a date.
func (q *Queries) RecurringCandidates(ctx context.Context, arg RecurringCandidatesParams) ([]RecurringCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, recurringCandidates, arg.HouseholdID, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringCandidatesRow
	for rows.Next() {
		var i RecurringCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.MerchantID,
			&i.Description,
			&i.Merchant,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.AccountID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportRows = `-- name: ReportRows :many

SELECT t.date, t.category_id, COALESCE(g.kind, '') AS kind,
    CAST(COALESCE(m.name, NULLIF(t.payee, ''), t.description) AS TEXT) AS merchant,
    CAST(SUM(t.amount_cents) AS INTEGER) AS total
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN merchants m ON m.id = t.merchant_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN category_groups g ON g.id = c.group_id
WHERE t.household_id = ?1 AND t.date >= ?2 AND t.date < ?3
  AND t.hidden = 0 AND t.linked_txn_id IS NULL AND a.status != 'ignored'
GROUP BY t.date, t.category_id, merchant
`

type ReportRowsParams struct {
	HouseholdID int64  `json:"household_id"`
	FromDate    string `json:"from_date"`
	ToDate      string `json:"to_date"`
}

type ReportRowsRow struct {
	Date       string        `json:"date"`
	CategoryID sql.NullInt64 `json:"category_id"`
	Kind       string        `json:"kind"`
	Merchant   string        `json:"merchant"`
	Total      int64         `json:"total"`
}

// ---- reports ----
// Signed totals per day, category and merchant over [from, to). Same exclusions as the
// budget totals: hidden rows, linked provisional rows and ignored accounts.
func (q *Queries) ReportRows(ctx context.Context, arg ReportRowsParams) ([]ReportRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, reportRows, arg.HouseholdID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportRowsRow
	for rows.Next() {
		var i ReportRowsRow
		if err := rows.Scan(
			&i.Date,
			&i.CategoryID,
			&i.Kind,
			&i.Merchant,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTreeRows = `-- name: ReportTreeRows :many
SELECT t.category_id, COALESCE(g.kind, '') AS kind,
    CAST(COALESCE(m.name, NULLIF(t.payee, ''), t.description) AS TEXT) AS merchant,
    CAST(CASE WHEN t.goal_withdrawal = 0 THEN COALESCE(t.goal_id, 0) ELSE 0 END AS INTEGER) AS goal_id,
    CAST(SUM(CASE WHEN t.goal_id IS NOT NULL AND t.goal_withdrawal = 0 THEN ABS(t.amount_cents) ELSE t.amount_cents END) AS INTEGER) AS total,
    CAST(COUNT(*) AS INTEGER) AS n
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN merchants m ON m.id = t.merchant_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN category_groups g ON g.id = c.group_id
WHERE t.household_id = ?1 AND t.date >= ?2 AND t.date < ?3
  AND t.hidden = 0 AND t.linked_txn_id IS NULL AND a.status != 'ignored'
GROUP BY t.category_id, 3, 4
`

type ReportTreeRowsParams struct {
	HouseholdID int64  `json:"household_id"`
	FromDate    string `json:"from_date"`
	ToDate      string `json:"to_date"`
}

type ReportTreeRowsRow struct {
	CategoryID sql.NullInt64 `json:"category_id"`
	Kind       string        `json:"kind"`
	Merchant   string        `json:"merchant"`
	GoalID     int64         `json:"goal_id"`
	Total      int64         `json:"total"`
	N          int64         `json:"n"`
}

// Totals per category, merchant and goal over [from, to) for the spending tree and cash flow
// diagram. Same exclusions as ReportRows. Rows put toward a goal (not withdrawals) carry
// goal_id and their absolute amount, like goal contributions in the budget.
func (q *Queries) ReportTreeRows(ctx context.Context, arg ReportTreeRowsParams) ([]ReportTreeRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, reportTreeRows, arg.HouseholdID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportTreeRowsRow
	for rows.Next() {
		var i ReportTreeRowsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Kind,
			&i.Merchant,
			&i.GoalID,
			&i.Total,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreRecurring = `-- name: RestoreRecurring :exec
DELETE FROM recurring_dismissed WHERE household_id = ? AND key = ?
`

type RestoreRecurringParams struct {
	HouseholdID int64  `json:"household_id"`
	Key         string `json:"key"`
}

func (q *Queries) RestoreRecurring(ctx context.Context, arg RestoreRecurringParams) error {
	_, err := q.db.ExecContext(ctx, restoreRecurring, arg.HouseholdID, arg.Key)
	return err
}
