// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const addRuleTag = `-- name: AddRuleTag :exec
INSERT OR IGNORE INTO rule_tags (rule_id, tag_id) VALUES (?, ?)
`

type AddRuleTagParams struct {
	RuleID int64 `json:"rule_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddRuleTag(ctx context.Context, arg AddRuleTagParams) error {
	_, err := q.db.ExecContext(ctx, addRuleTag, arg.RuleID, arg.TagID)
	return err
}

const addTransactionTag = `-- name: AddTransactionTag :exec
INSERT OR IGNORE INTO transaction_tags (transaction_id, tag_id)
SELECT ?1, t.id FROM tags t WHERE t.id = ?2 AND t.household_id = ?3
`

type AddTransactionTagParams struct {
	TransactionID int64 `json:"transaction_id"`
	TagID         int64 `json:"tag_id"`
	HouseholdID   int64 `json:"household_id"`
}

func (q *Queries) AddTransactionTag(ctx context.Context, arg AddTransactionTagParams) error {
	_, err := q.db.ExecContext(ctx, addTransactionTag, arg.TransactionID, arg.TagID, arg.HouseholdID)
	return err
}

const blacklistLink = `-- name: BlacklistLink :exec
INSERT OR IGNORE INTO link_blacklist (provisional_id, posted_id) VALUES (?, ?)
`

type BlacklistLinkParams struct {
	ProvisionalID int64 `json:"provisional_id"`
	PostedID      int64 `json:"posted_id"`
}

func (q *Queries) BlacklistLink(ctx context.Context, arg BlacklistLinkParams) error {
	_, err := q.db.ExecContext(ctx, blacklistLink, arg.ProvisionalID, arg.PostedID)
	return err
}

const clearRuleTags = `-- name: ClearRuleTags :exec
DELETE FROM rule_tags WHERE rule_id = ?
`

func (q *Queries) ClearRuleTags(ctx context.Context, ruleID int64) error {
	_, err := q.db.ExecContext(ctx, clearRuleTags, ruleID)
	return err
}

const clearTransactionTags = `-- name: ClearTransactionTags :exec
DELETE FROM transaction_tags WHERE transaction_id = ?
`

func (q *Queries) ClearTransactionTags(ctx context.Context, transactionID int64) error {
	_, err := q.db.ExecContext(ctx, clearTransactionTags, transactionID)
	return err
}

const copyTransactionTags = `-- name: CopyTransactionTags :exec
INSERT OR IGNORE INTO transaction_tags (transaction_id, tag_id)
SELECT ?1, src.tag_id FROM transaction_tags src WHERE src.transaction_id = ?2
`

type CopyTransactionTagsParams struct {
	ToID   int64 `json:"to_id"`
	FromID int64 `json:"from_id"`
}

func (q *Queries) CopyTransactionTags(ctx context.Context, arg CopyTransactionTagsParams) error {
	_, err := q.db.ExecContext(ctx, copyTransactionTags, arg.ToID, arg.FromID)
	return err
}

const countCategoryGroups = `-- name: CountCategoryGroups :one

SELECT COUNT(*) FROM category_groups WHERE household_id = ?
`

// ---- categories ----
func (q *Queries) CountCategoryGroups(ctx context.Context, householdID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoryGroups, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoryTransactions = `-- name: CountCategoryTransactions :one
SELECT COUNT(*) FROM transactions WHERE category_id = ? AND household_id = ?
`

type CountCategoryTransactionsParams struct {
	CategoryID  sql.NullInt64 `json:"category_id"`
	HouseholdID int64         `json:"household_id"`
}

func (q *Queries) CountCategoryTransactions(ctx context.Context, arg CountCategoryTransactionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoryTransactions, arg.CategoryID, arg.HouseholdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (household_id, group_id, name, icon, sort) VALUES (?, ?, ?, ?, ?) RETURNING id, household_id, group_id, name, icon, sort, archived, chunk, budget_hidden
`

type CreateCategoryParams struct {
	HouseholdID int64  `json:"household_id"`
	GroupID     int64  `json:"group_id"`
	Name        string `json:"name"`
	Icon        string `json:"icon"`
	Sort        int64  `json:"sort"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.HouseholdID,
		arg.GroupID,
		arg.Name,
		arg.Icon,
		arg.Sort,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.GroupID,
		&i.Name,
		&i.Icon,
		&i.Sort,
		&i.Archived,
		&i.Chunk,
		&i.BudgetHidden,
	)
	return i, err
}

const createCategoryGroup = `-- name: CreateCategoryGroup :one
INSERT INTO category_groups (household_id, name, kind, sort) VALUES (?, ?, ?, ?) RETURNING id, household_id, name, kind, sort
`

type CreateCategoryGroupParams struct {
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	Sort        int64  `json:"sort"`
}

func (q *Queries) CreateCategoryGroup(ctx context.Context, arg CreateCategoryGroupParams) (CategoryGroup, error) {
	row := q.db.QueryRowContext(ctx, createCategoryGroup,
		arg.HouseholdID,
		arg.Name,
		arg.Kind,
		arg.Sort,
	)
	var i CategoryGroup
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Kind,
		&i.Sort,
	)
	return i, err
}

const createRule = `-- name: CreateRule :one
INSERT INTO rules (
    household_id, priority, match_field, match_op, match_value, account_id, amount_min, amount_max,
    direction, day_min, day_max, set_category_id, set_merchant, set_hidden, set_goal_id, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, household_id, priority, match_field, match_op, match_value, account_id, amount_min, amount_max, set_category_id, set_merchant, add_tag_id, set_hidden, created_at, direction, day_min, day_max, set_goal_id
`

type CreateRuleParams struct {
	HouseholdID   int64         `json:"household_id"`
	Priority      int64         `json:"priority"`
	MatchField    string        `json:"match_field"`
	MatchOp       string        `json:"match_op"`
	MatchValue    string        `json:"match_value"`
	AccountID     sql.NullInt64 `json:"account_id"`
	AmountMin     sql.NullInt64 `json:"amount_min"`
	AmountMax     sql.NullInt64 `json:"amount_max"`
	Direction     string        `json:"direction"`
	DayMin        sql.NullInt64 `json:"day_min"`
	DayMax        sql.NullInt64 `json:"day_max"`
	SetCategoryID sql.NullInt64 `json:"set_category_id"`
	SetMerchant   string        `json:"set_merchant"`
	SetHidden     int64         `json:"set_hidden"`
	SetGoalID     sql.NullInt64 `json:"set_goal_id"`
	CreatedAt     int64         `json:"created_at"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, createRule,
		arg.HouseholdID,
		arg.Priority,
		arg.MatchField,
		arg.MatchOp,
		arg.MatchValue,
		arg.AccountID,
		arg.AmountMin,
		arg.AmountMax,
		arg.Direction,
		arg.DayMin,
		arg.DayMax,
		arg.SetCategoryID,
		arg.SetMerchant,
		arg.SetHidden,
		arg.SetGoalID,
		arg.CreatedAt,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Priority,
		&i.MatchField,
		&i.MatchOp,
		&i.MatchValue,
		&i.AccountID,
		&i.AmountMin,
		&i.AmountMax,
		&i.SetCategoryID,
		&i.SetMerchant,
		&i.AddTagID,
		&i.SetHidden,
		&i.CreatedAt,
		&i.Direction,
		&i.DayMin,
		&i.DayMax,
		&i.SetGoalID,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = ? AND household_id = ?
`

type DeleteCategoryParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCategory, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteManualTransaction = `-- name: DeleteManualTransaction :exec
DELETE FROM transactions WHERE id = ? AND household_id = ? AND source = 'manual'
`

type DeleteManualTransactionParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteManualTransaction(ctx context.Context, arg DeleteManualTransactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteManualTransaction, arg.ID, arg.HouseholdID)
	return err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = ? AND household_id = ?
`

type DeleteRuleParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRule, arg.ID, arg.HouseholdID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, household_id, group_id, name, icon, sort, archived, chunk, budget_hidden FROM categories WHERE id = ? AND household_id = ?
`

type GetCategoryParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, arg.ID, arg.HouseholdID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.GroupID,
		&i.Name,
		&i.Icon,
		&i.Sort,
		&i.Archived,
		&i.Chunk,
		&i.BudgetHidden,
	)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, household_id, name, normalized FROM merchants WHERE id = ? AND household_id = ?
`

type GetMerchantParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetMerchant(ctx context.Context, arg GetMerchantParams) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchant, arg.ID, arg.HouseholdID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Normalized,
	)
	return i, err
}

const getRule = `-- name: GetRule :one
SELECT id, household_id, priority, match_field, match_op, match_value, account_id, amount_min, amount_max, set_category_id, set_merchant, add_tag_id, set_hidden, created_at, direction, day_min, day_max, set_goal_id FROM rules WHERE id = ? AND household_id = ?
`

type GetRuleParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, getRule, arg.ID, arg.HouseholdID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Priority,
		&i.MatchField,
		&i.MatchOp,
		&i.MatchValue,
		&i.AccountID,
		&i.AmountMin,
		&i.AmountMax,
		&i.SetCategoryID,
		&i.SetMerchant,
		&i.AddTagID,
		&i.SetHidden,
		&i.CreatedAt,
		&i.Direction,
		&i.DayMin,
		&i.DayMax,
		&i.SetGoalID,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, household_id, account_id, external_id, source, date, amount_cents, description, payee, memo, pending, created_at, updated_at, merchant_id, category_id, category_source, notes, hidden, needs_review, provisional, linked_txn_id, linked_at, goal_id, owner_user_id, ai_cat_tried, goal_withdrawal FROM transactions WHERE id = ? AND household_id = ?
`

type GetTransactionParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, arg.ID, arg.HouseholdID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.ExternalID,
		&i.Source,
		&i.Date,
		&i.AmountCents,
		&i.Description,
		&i.Payee,
		&i.Memo,
		&i.Pending,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MerchantID,
		&i.CategoryID,
		&i.CategorySource,
		&i.Notes,
		&i.Hidden,
		&i.NeedsReview,
		&i.Provisional,
		&i.LinkedTxnID,
		&i.LinkedAt,
		&i.GoalID,
		&i.OwnerUserID,
		&i.AiCatTried,
		&i.GoalWithdrawal,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, household_id, account_id, external_id, source, date, amount_cents, description, payee, memo, pending, created_at, updated_at, merchant_id, category_id, category_source, notes, hidden, needs_review, provisional, linked_txn_id, linked_at, goal_id, owner_user_id, ai_cat_tried, goal_withdrawal FROM transactions WHERE id = ?
`

func (q *Queries) GetTransactionByID(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.ExternalID,
		&i.Source,
		&i.Date,
		&i.AmountCents,
		&i.Description,
		&i.Payee,
		&i.Memo,
		&i.Pending,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MerchantID,
		&i.CategoryID,
		&i.CategorySource,
		&i.Notes,
		&i.Hidden,
		&i.NeedsReview,
		&i.Provisional,
		&i.LinkedTxnID,
		&i.LinkedAt,
		&i.GoalID,
		&i.OwnerUserID,
		&i.AiCatTried,
		&i.GoalWithdrawal,
	)
	return i, err
}

const getTransactionView = `-- name: GetTransactionView :one
SELECT t.id, t.household_id, t.account_id, t.external_id, t.source, t.date, t.amount_cents, t.description, t.payee, t.memo, t.pending, t.created_at, t.updated_at, t.merchant_id, t.category_id, t.category_source, t.notes, t.hidden, t.needs_review, t.provisional, t.linked_txn_id, t.linked_at, t.goal_id, t.owner_user_id, t.ai_cat_tried, t.goal_withdrawal, a.name AS account_name, a.mask AS account_mask,
    COALESCE(m.name, '') AS merchant_name,
    COALESCE(c.name, '') AS category_name, COALESCE(c.icon, '') AS category_icon,
    EXISTS (SELECT 1 FROM transactions p WHERE p.linked_txn_id = t.id) AS has_linked,
    CAST(COALESCE((SELECT p.source FROM transactions p WHERE p.linked_txn_id = t.id ORDER BY p.id LIMIT 1), '') AS TEXT) AS linked_source,
    CAST(COALESCE(t.owner_user_id, a.owner_user_id, 0) AS INTEGER) AS owner_id
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN merchants m ON m.id = t.merchant_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.id = ? AND t.household_id = ?
`

type GetTransactionViewParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

type GetTransactionViewRow struct {
	ID             int64          `json:"id"`
	HouseholdID    int64          `json:"household_id"`
	AccountID      int64          `json:"account_id"`
	ExternalID     sql.NullString `json:"external_id"`
	Source         string         `json:"source"`
	Date           string         `json:"date"`
	AmountCents    int64          `json:"amount_cents"`
	Description    string         `json:"description"`
	Payee          string         `json:"payee"`
	Memo           string         `json:"memo"`
	Pending        int64          `json:"pending"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	MerchantID     sql.NullInt64  `json:"merchant_id"`
	CategoryID     sql.NullInt64  `json:"category_id"`
	CategorySource string         `json:"category_source"`
	Notes          string         `json:"notes"`
	Hidden         int64          `json:"hidden"`
	NeedsReview    int64          `json:"needs_review"`
	Provisional    int64          `json:"provisional"`
	LinkedTxnID    sql.NullInt64  `json:"linked_txn_id"`
	LinkedAt       sql.NullInt64  `json:"linked_at"`
	GoalID         sql.NullInt64  `json:"goal_id"`
	OwnerUserID    sql.NullInt64  `json:"owner_user_id"`
	AiCatTried     int64          `json:"ai_cat_tried"`
	GoalWithdrawal int64          `json:"goal_withdrawal"`
	AccountName    string         `json:"account_name"`
	AccountMask    string         `json:"account_mask"`
	MerchantName   string         `json:"merchant_name"`
	CategoryName   string         `json:"category_name"`
	CategoryIcon   string         `json:"category_icon"`
	HasLinked      bool           `json:"has_linked"`
	LinkedSource   string         `json:"linked_source"`
	OwnerID        int64          `json:"owner_id"`
}

func (q *Queries) GetTransactionView(ctx context.Context, arg GetTransactionViewParams) (GetTransactionViewRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionView, arg.ID, arg.HouseholdID)
	var i GetTransactionViewRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.ExternalID,
		&i.Source,
		&i.Date,
		&i.AmountCents,
		&i.Description,
		&i.Payee,
		&i.Memo,
		&i.Pending,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MerchantID,
		&i.CategoryID,
		&i.CategorySource,
		&i.Notes,
		&i.Hidden,
		&i.NeedsReview,
		&i.Provisional,
		&i.LinkedTxnID,
		&i.LinkedAt,
		&i.GoalID,
		&i.OwnerUserID,
		&i.AiCatTried,
		&i.GoalWithdrawal,
		&i.AccountName,
		&i.AccountMask,
		&i.MerchantName,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.HasLinked,
		&i.LinkedSource,
		&i.OwnerID,
	)
	return i, err
}

const insertManualTransaction = `-- name: InsertManualTransaction :one
INSERT INTO transactions (
    household_id, account_id, source, date, amount_cents, description, payee, pending, provisional,
    merchant_id, category_id, category_source, notes, needs_review, owner_user_id, created_at, updated_at
) VALUES (?, ?, 'manual', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertManualTransactionParams struct {
	HouseholdID    int64         `json:"household_id"`
	AccountID      int64         `json:"account_id"`
	Date           string        `json:"date"`
	AmountCents    int64         `json:"amount_cents"`
	Description    string        `json:"description"`
	Payee          string        `json:"payee"`
	Pending        int64         `json:"pending"`
	Provisional    int64         `json:"provisional"`
	MerchantID     sql.NullInt64 `json:"merchant_id"`
	CategoryID     sql.NullInt64 `json:"category_id"`
	CategorySource string        `json:"category_source"`
	Notes          string        `json:"notes"`
	NeedsReview    int64         `json:"needs_review"`
	OwnerUserID    sql.NullInt64 `json:"owner_user_id"`
	CreatedAt      int64         `json:"created_at"`
	UpdatedAt      int64         `json:"updated_at"`
}

func (q *Queries) InsertManualTransaction(ctx context.Context, arg InsertManualTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertManualTransaction,
		arg.HouseholdID,
		arg.AccountID,
		arg.Date,
		arg.AmountCents,
		arg.Description,
		arg.Payee,
		arg.Pending,
		arg.Provisional,
		arg.MerchantID,
		arg.CategoryID,
		arg.CategorySource,
		arg.Notes,
		arg.NeedsReview,
		arg.OwnerUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const linkTransaction = `-- name: LinkTransaction :exec
UPDATE transactions SET linked_txn_id = ?, linked_at = ? WHERE id = ?
`

type LinkTransactionParams struct {
	LinkedTxnID sql.NullInt64 `json:"linked_txn_id"`
	LinkedAt    sql.NullInt64 `json:"linked_at"`
	ID          int64         `json:"id"`
}

func (q *Queries) LinkTransaction(ctx context.Context, arg LinkTransactionParams) error {
	_, err := q.db.ExecContext(ctx, linkTransaction, arg.LinkedTxnID, arg.LinkedAt, arg.ID)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT id, household_id, group_id, name, icon, sort, archived, chunk, budget_hidden FROM categories WHERE household_id = ? ORDER BY sort, id
`

func (q *Queries) ListCategories(ctx context.Context, householdID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.GroupID,
			&i.Name,
			&i.Icon,
			&i.Sort,
			&i.Archived,
			&i.Chunk,
			&i.BudgetHidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryGroups = `-- name: ListCategoryGroups :many
SELECT id, household_id, name, kind, sort FROM category_groups WHERE household_id = ? ORDER BY sort, id
`

func (q *Queries) ListCategoryGroups(ctx context.Context, householdID int64) ([]CategoryGroup, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryGroups, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryGroup
	for rows.Next() {
		var i CategoryGroup
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Kind,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdIDs = `-- name: ListHouseholdIDs :many
SELECT id FROM households
`

func (q *Queries) ListHouseholdIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholdIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkCandidates = `-- name: ListLinkCandidates :many

SELECT t.id, t.date, t.amount_cents, t.description, t.payee, COALESCE(m.name, '') AS merchant_name
FROM transactions t LEFT JOIN merchants m ON m.id = t.merchant_id
WHERE t.account_id = ?1 AND t.provisional = 1 AND t.linked_txn_id IS NULL
  AND t.amount_cents >= ?2 AND t.amount_cents <= ?3
  AND t.date >= ?4 AND t.date <= ?5
  AND NOT EXISTS (SELECT 1 FROM link_blacklist b WHERE b.provisional_id = t.id AND b.posted_id = ?6)
`

type ListLinkCandidatesParams struct {
	AccountID int64  `json:"account_id"`
	AmountLo  int64  `json:"amount_lo"`
	AmountHi  int64  `json:"amount_hi"`
	DateLo    string `json:"date_lo"`
	DateHi    string `json:"date_hi"`
	PostedID  int64  `json:"posted_id"`
}

type ListLinkCandidatesRow struct {
	ID           int64  `json:"id"`
	Date         string `json:"date"`
	AmountCents  int64  `json:"amount_cents"`
	Description  string `json:"description"`
	Payee        string `json:"payee"`
	MerchantName string `json:"merchant_name"`
}

// ---- linking ----
func (q *Queries) ListLinkCandidates(ctx context.Context, arg ListLinkCandidatesParams) ([]ListLinkCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinkCandidates,
		arg.AccountID,
		arg.AmountLo,
		arg.AmountHi,
		arg.DateLo,
		arg.DateHi,
		arg.PostedID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkCandidatesRow
	for rows.Next() {
		var i ListLinkCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.Description,
			&i.Payee,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedProvisional = `-- name: ListLinkedProvisional :many
SELECT id, household_id, account_id, external_id, source, date, amount_cents, description, payee, memo, pending, created_at, updated_at, merchant_id, category_id, category_source, notes, hidden, needs_review, provisional, linked_txn_id, linked_at, goal_id, owner_user_id, ai_cat_tried, goal_withdrawal FROM transactions WHERE linked_txn_id = ? ORDER BY id
`

func (q *Queries) ListLinkedProvisional(ctx context.Context, linkedTxnID sql.NullInt64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listLinkedProvisional, linkedTxnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.AccountID,
			&i.ExternalID,
			&i.Source,
			&i.Date,
			&i.AmountCents,
			&i.Description,
			&i.Payee,
			&i.Memo,
			&i.Pending,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MerchantID,
			&i.CategoryID,
			&i.CategorySource,
			&i.Notes,
			&i.Hidden,
			&i.NeedsReview,
			&i.Provisional,
			&i.LinkedTxnID,
			&i.LinkedAt,
			&i.GoalID,
			&i.OwnerUserID,
			&i.AiCatTried,
			&i.GoalWithdrawal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantTransactions = `-- name: ListMerchantTransactions :many
SELECT t.id, t.date, t.amount_cents, t.description, a.name AS account_name, COALESCE(c.name, '') AS category_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.household_id = ? AND t.merchant_id = ? AND t.id != ? AND t.linked_txn_id IS NULL
ORDER BY t.date DESC, t.id DESC LIMIT 50
`

type ListMerchantTransactionsParams struct {
	HouseholdID int64         `json:"household_id"`
	MerchantID  sql.NullInt64 `json:"merchant_id"`
	ID          int64         `json:"id"`
}

type ListMerchantTransactionsRow struct {
	ID           int64  `json:"id"`
	Date         string `json:"date"`
	AmountCents  int64  `json:"amount_cents"`
	Description  string `json:"description"`
	AccountName  string `json:"account_name"`
	CategoryName string `json:"category_name"`
}

func (q *Queries) ListMerchantTransactions(ctx context.Context, arg ListMerchantTransactionsParams) ([]ListMerchantTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMerchantTransactions, arg.HouseholdID, arg.MerchantID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMerchantTransactionsRow
	for rows.Next() {
		var i ListMerchantTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.Description,
			&i.AccountName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostedDuplicates = `-- name: ListPostedDuplicates :many
SELECT t.id, t.date, t.amount_cents, t.description, COALESCE(m.name, '') AS merchant_name
FROM transactions t LEFT JOIN merchants m ON m.id = t.merchant_id
WHERE t.account_id = ? AND t.provisional = 0 AND t.amount_cents = ? AND t.date >= ?3 AND t.date <= ?4
`

type ListPostedDuplicatesParams struct {
	AccountID   int64  `json:"account_id"`
	AmountCents int64  `json:"amount_cents"`
	DateLo      string `json:"date_lo"`
	DateHi      string `json:"date_hi"`
}

type ListPostedDuplicatesRow struct {
	ID           int64  `json:"id"`
	Date         string `json:"date"`
	AmountCents  int64  `json:"amount_cents"`
	Description  string `json:"description"`
	MerchantName string `json:"merchant_name"`
}

// Posted rows that look like the same purchase as a new pending entry (duplicate warning).
func (q *Queries) ListPostedDuplicates(ctx context.Context, arg ListPostedDuplicatesParams) ([]ListPostedDuplicatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostedDuplicates,
		arg.AccountID,
		arg.AmountCents,
		arg.DateLo,
		arg.DateHi,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostedDuplicatesRow
	for rows.Next() {
		var i ListPostedDuplicatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.Description,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostedForLink = `-- name: ListPostedForLink :many
SELECT t.id, t.date, t.amount_cents, t.description, COALESCE(m.name, '') AS merchant_name,
    CAST(ABS(t.amount_cents - ?1) AS INTEGER) AS distance
FROM transactions t LEFT JOIN merchants m ON m.id = t.merchant_id
WHERE t.account_id = ?2 AND t.provisional = 0
  AND t.date >= ?3 AND t.date <= ?4
  AND NOT EXISTS (SELECT 1 FROM transactions p WHERE p.linked_txn_id = t.id)
ORDER BY distance, t.date DESC
LIMIT 20
`

type ListPostedForLinkParams struct {
	AmountCents int64  `json:"amount_cents"`
	AccountID   int64  `json:"account_id"`
	DateLo      string `json:"date_lo"`
	DateHi      string `json:"date_hi"`
}

type ListPostedForLinkRow struct {
	ID           int64  `json:"id"`
	Date         string `json:"date"`
	AmountCents  int64  `json:"amount_cents"`
	Description  string `json:"description"`
	MerchantName string `json:"merchant_name"`
	Distance     int64  `json:"distance"`
}

// Posted rows a provisional entry could be linked to by hand.
func (q *Queries) ListPostedForLink(ctx context.Context, arg ListPostedForLinkParams) ([]ListPostedForLinkRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostedForLink,
		arg.AmountCents,
		arg.AccountID,
		arg.DateLo,
		arg.DateHi,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostedForLinkRow
	for rows.Next() {
		var i ListPostedForLinkRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.Description,
			&i.MerchantName,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleTags = `-- name: ListRuleTags :many
SELECT rt.rule_id, t.id, t.name FROM rule_tags rt JOIN tags t ON t.id = rt.tag_id
JOIN rules r ON r.id = rt.rule_id WHERE r.household_id = ? ORDER BY t.name
`

type ListRuleTagsRow struct {
	RuleID int64  `json:"rule_id"`
	ID     int64  `json:"id"`
	Name   string `json:"name"`
}

func (q *Queries) ListRuleTags(ctx context.Context, householdID int64) ([]ListRuleTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuleTags, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRuleTagsRow
	for rows.Next() {
		var i ListRuleTagsRow
		if err := rows.Scan(&i.RuleID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleTargets = `-- name: ListRuleTargets :many
SELECT t.id, t.account_id, t.date, t.amount_cents, t.description, t.payee, t.merchant_id, COALESCE(m.name, '') AS merchant_name
FROM transactions t LEFT JOIN merchants m ON m.id = t.merchant_id
WHERE t.household_id = ? AND t.linked_txn_id IS NULL
`

type ListRuleTargetsRow struct {
	ID           int64         `json:"id"`
	AccountID    int64         `json:"account_id"`
	Date         string        `json:"date"`
	AmountCents  int64         `json:"amount_cents"`
	Description  string        `json:"description"`
	Payee        string        `json:"payee"`
	MerchantID   sql.NullInt64 `json:"merchant_id"`
	MerchantName string        `json:"merchant_name"`
}

// Transactions a rule may apply to (it never overrides a category the user chose by hand).
func (q *Queries) ListRuleTargets(ctx context.Context, householdID int64) ([]ListRuleTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuleTargets, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRuleTargetsRow
	for rows.Next() {
		var i ListRuleTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.AmountCents,
			&i.Description,
			&i.Payee,
			&i.MerchantID,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many

SELECT id, household_id, priority, match_field, match_op, match_value, account_id, amount_min, amount_max, set_category_id, set_merchant, add_tag_id, set_hidden, created_at, direction, day_min, day_max, set_goal_id FROM rules WHERE household_id = ? ORDER BY priority, id
`

// ---- rules ----
func (q *Queries) ListRules(ctx context.Context, householdID int64) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listRules, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Priority,
			&i.MatchField,
			&i.MatchOp,
			&i.MatchValue,
			&i.AccountID,
			&i.AmountMin,
			&i.AmountMax,
			&i.SetCategoryID,
			&i.SetMerchant,
			&i.AddTagID,
			&i.SetHidden,
			&i.CreatedAt,
			&i.Direction,
			&i.DayMin,
			&i.DayMax,
			&i.SetGoalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many

SELECT id, household_id, name, color FROM tags WHERE household_id = ? ORDER BY name
`

// ---- tags ----
func (q *Queries) ListTags(ctx context.Context, householdID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTransactions = `-- name: ListTagsForTransactions :many
SELECT tt.transaction_id, t.id, t.name, t.color FROM transaction_tags tt JOIN tags t ON t.id = tt.tag_id
WHERE tt.transaction_id IN (/*SLICE:ids*/?) ORDER BY t.name
`

type ListTagsForTransactionsRow struct {
	TransactionID int64  `json:"transaction_id"`
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Color         string `json:"color"`
}

func (q *Queries) ListTagsForTransactions(ctx context.Context, ids []int64) ([]ListTagsForTransactionsRow, error) {
	query := listTagsForTransactions
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForTransactionsRow
	for rows.Next() {
		var i ListTagsForTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.ID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTagIDs = `-- name: ListTransactionTagIDs :many
SELECT tag_id FROM transaction_tags WHERE transaction_id = ?
`

func (q *Queries) ListTransactionTagIDs(ctx context.Context, transactionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionTagIDs, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var tag_id int64
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many

SELECT t.id, t.household_id, t.account_id, t.external_id, t.source, t.date, t.amount_cents, t.description, t.payee, t.memo, t.pending, t.created_at, t.updated_at, t.merchant_id, t.category_id, t.category_source, t.notes, t.hidden, t.needs_review, t.provisional, t.linked_txn_id, t.linked_at, t.goal_id, t.owner_user_id, t.ai_cat_tried, t.goal_withdrawal, a.name AS account_name, a.mask AS account_mask,
    COALESCE(m.name, '') AS merchant_name,
    COALESCE(c.name, '') AS category_name, COALESCE(c.icon, '') AS category_icon,
    EXISTS (SELECT 1 FROM transactions p WHERE p.linked_txn_id = t.id) AS has_linked,
    CAST(COALESCE((SELECT p.source FROM transactions p WHERE p.linked_txn_id = t.id ORDER BY p.id LIMIT 1), '') AS TEXT) AS linked_source,
    CAST(COALESCE(t.owner_user_id, a.owner_user_id, 0) AS INTEGER) AS owner_id
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN merchants m ON m.id = t.merchant_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.household_id = ?1
  AND t.linked_txn_id IS NULL
  AND a.status != 'ignored'
  AND (?2 IS NULL OR t.account_id = ?2)
  AND (?3 IS NULL OR t.category_id = ?3)
  AND (?4 IS NULL OR t.goal_id = ?4)
  AND (?5 IS NULL OR COALESCE(t.owner_user_id, a.owner_user_id, 0) = ?5)
  AND (?6 = '' OR t.date >= ?6)
  AND (?7 = '' OR t.date <= ?7)
  AND (?8 = 0 OR t.category_id IS NULL)
  AND (?9 = 0 OR t.needs_review = 1)
  AND (?10 = 1 OR t.hidden = 0)
  AND (?11 = '' OR t.description LIKE '%' || ?11 || '%' OR m.name LIKE '%' || ?11 || '%'
       OR t.notes LIKE '%' || ?11 || '%' OR t.payee LIKE '%' || ?11 || '%')
  AND (?12 = '' OR t.date < ?12
       OR (t.date = ?12 AND t.id < ?13))
ORDER BY t.date DESC, t.id DESC
LIMIT ?14
`

type ListTransactionsParams struct {
	HouseholdID   int64       `json:"household_id"`
	AccountID     interface{} `json:"account_id"`
	CategoryID    interface{} `json:"category_id"`
	GoalID        interface{} `json:"goal_id"`
	OwnerID       interface{} `json:"owner_id"`
	FromDate      interface{} `json:"from_date"`
	ToDate        interface{} `json:"to_date"`
	Uncategorized interface{} `json:"uncategorized"`
	NeedsReview   interface{} `json:"needs_review"`
	IncludeHidden interface{} `json:"include_hidden"`
	Q             interface{} `json:"q"`
	BeforeDate    interface{} `json:"before_date"`
	BeforeID      int64       `json:"before_id"`
	Lim           int64       `json:"lim"`
}

type ListTransactionsRow struct {
	ID             int64          `json:"id"`
	HouseholdID    int64          `json:"household_id"`
	AccountID      int64          `json:"account_id"`
	ExternalID     sql.NullString `json:"external_id"`
	Source         string         `json:"source"`
	Date           string         `json:"date"`
	AmountCents    int64          `json:"amount_cents"`
	Description    string         `json:"description"`
	Payee          string         `json:"payee"`
	Memo           string         `json:"memo"`
	Pending        int64          `json:"pending"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	MerchantID     sql.NullInt64  `json:"merchant_id"`
	CategoryID     sql.NullInt64  `json:"category_id"`
	CategorySource string         `json:"category_source"`
	Notes          string         `json:"notes"`
	Hidden         int64          `json:"hidden"`
	NeedsReview    int64          `json:"needs_review"`
	Provisional    int64          `json:"provisional"`
	LinkedTxnID    sql.NullInt64  `json:"linked_txn_id"`
	LinkedAt       sql.NullInt64  `json:"linked_at"`
	GoalID         sql.NullInt64  `json:"goal_id"`
	OwnerUserID    sql.NullInt64  `json:"owner_user_id"`
	AiCatTried     int64          `json:"ai_cat_tried"`
	GoalWithdrawal int64          `json:"goal_withdrawal"`
	AccountName    string         `json:"account_name"`
	AccountMask    string         `json:"account_mask"`
	MerchantName   string         `json:"merchant_name"`
	CategoryName   string         `json:"category_name"`
	CategoryIcon   string         `json:"category_icon"`
	HasLinked      bool           `json:"has_linked"`
	LinkedSource   string         `json:"linked_source"`
	OwnerID        int64          `json:"owner_id"`
}

// ---- transactions (user side) ----
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions,
		arg.HouseholdID,
		arg.AccountID,
		arg.CategoryID,
		arg.GoalID,
		arg.OwnerID,
		arg.FromDate,
		arg.ToDate,
		arg.Uncategorized,
		arg.NeedsReview,
		arg.IncludeHidden,
		arg.Q,
		arg.BeforeDate,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.AccountID,
			&i.ExternalID,
			&i.Source,
			&i.Date,
			&i.AmountCents,
			&i.Description,
			&i.Payee,
			&i.Memo,
			&i.Pending,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MerchantID,
			&i.CategoryID,
			&i.CategorySource,
			&i.Notes,
			&i.Hidden,
			&i.NeedsReview,
			&i.Provisional,
			&i.LinkedTxnID,
			&i.LinkedAt,
			&i.GoalID,
			&i.OwnerUserID,
			&i.AiCatTried,
			&i.GoalWithdrawal,
			&i.AccountName,
			&i.AccountMask,
			&i.MerchantName,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.HasLinked,
			&i.LinkedSource,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncategorizedForAI = `-- name: ListUncategorizedForAI :many

SELECT t.id, t.merchant_id, t.amount_cents, t.description, t.payee, COALESCE(m.name, '') AS merchant_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN merchants m ON m.id = t.merchant_id
WHERE t.household_id = ?1 AND t.category_id IS NULL AND t.hidden = 0
  AND t.linked_txn_id IS NULL AND a.status != 'ignored'
  AND t.date >= ?2 AND (?3 = 1 OR t.ai_cat_tried = 0)
  AND t.created_at >= ?4
ORDER BY t.date DESC, t.id DESC LIMIT 2000
`

type ListUncategorizedForAIParams struct {
	HouseholdID  int64       `json:"household_id"`
	Since        string      `json:"since"`
	IncludeTried interface{} `json:"include_tried"`
	CreatedSince int64       `json:"created_since"`
}

type ListUncategorizedForAIRow struct {
	ID           int64         `json:"id"`
	MerchantID   sql.NullInt64 `json:"merchant_id"`
	AmountCents  int64         `json:"amount_cents"`
	Description  string        `json:"description"`
	Payee        string        `json:"payee"`
	MerchantName string        `json:"merchant_name"`
}

// ---- AI categorization ----
// Uncategorized money movements the AI may look at. `tried` rows (the AI already passed on
// them) are skipped unless include_tried.
func (q *Queries) ListUncategorizedForAI(ctx context.Context, arg ListUncategorizedForAIParams) ([]ListUncategorizedForAIRow, error) {
	rows, err := q.db.QueryContext(ctx, listUncategorizedForAI,
		arg.HouseholdID,
		arg.Since,
		arg.IncludeTried,
		arg.CreatedSince,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUncategorizedForAIRow
	for rows.Next() {
		var i ListUncategorizedForAIRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.AmountCents,
			&i.Description,
			&i.Payee,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAICategoryTried = `-- name: MarkAICategoryTried :exec
UPDATE transactions SET ai_cat_tried = 1 WHERE id = ? AND household_id = ?
`

type MarkAICategoryTriedParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) MarkAICategoryTried(ctx context.Context, arg MarkAICategoryTriedParams) error {
	_, err := q.db.ExecContext(ctx, markAICategoryTried, arg.ID, arg.HouseholdID)
	return err
}

const merchantHistoryCategory = `-- name: MerchantHistoryCategory :one
SELECT category_id FROM transactions
WHERE household_id = ? AND merchant_id = ? AND category_id IS NOT NULL
  AND category_source IN ('user', 'rule', 'linked', 'ai')
ORDER BY category_source = 'ai', date DESC, id DESC LIMIT 1
`

type MerchantHistoryCategoryParams struct {
	HouseholdID int64         `json:"household_id"`
	MerchantID  sql.NullInt64 `json:"merchant_id"`
}

// Category most recently chosen by the user (or a rule) for a merchant. An AI pick counts too
// (a "soft rule": the merchant needn't go to the AI again), but anything a person chose wins.
func (q *Queries) MerchantHistoryCategory(ctx context.Context, arg MerchantHistoryCategoryParams) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, merchantHistoryCategory, arg.HouseholdID, arg.MerchantID)
	var category_id sql.NullInt64
	err := row.Scan(&category_id)
	return category_id, err
}

const moveCategoryRules = `-- name: MoveCategoryRules :exec
UPDATE rules SET set_category_id = ?1 WHERE set_category_id = ?2 AND household_id = ?3
`

type MoveCategoryRulesParams struct {
	ToID        sql.NullInt64 `json:"to_id"`
	FromID      sql.NullInt64 `json:"from_id"`
	HouseholdID int64         `json:"household_id"`
}

func (q *Queries) MoveCategoryRules(ctx context.Context, arg MoveCategoryRulesParams) error {
	_, err := q.db.ExecContext(ctx, moveCategoryRules, arg.ToID, arg.FromID, arg.HouseholdID)
	return err
}

const moveCategoryTransactions = `-- name: MoveCategoryTransactions :execrows
UPDATE transactions SET category_id = ?1 WHERE category_id = ?2 AND household_id = ?3
`

type MoveCategoryTransactionsParams struct {
	ToID        sql.NullInt64 `json:"to_id"`
	FromID      sql.NullInt64 `json:"from_id"`
	HouseholdID int64         `json:"household_id"`
}

func (q *Queries) MoveCategoryTransactions(ctx context.Context, arg MoveCategoryTransactionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveCategoryTransactions, arg.ToID, arg.FromID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameMerchant = `-- name: RenameMerchant :exec
UPDATE merchants SET name = ? WHERE id = ? AND household_id = ?
`

type RenameMerchantParams struct {
	Name        string `json:"name"`
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
}

func (q *Queries) RenameMerchant(ctx context.Context, arg RenameMerchantParams) error {
	_, err := q.db.ExecContext(ctx, renameMerchant, arg.Name, arg.ID, arg.HouseholdID)
	return err
}

const setCategoryPlace = `-- name: SetCategoryPlace :exec
UPDATE categories SET group_id = ?, sort = ? WHERE id = ? AND household_id = ?
`

type SetCategoryPlaceParams struct {
	GroupID     int64 `json:"group_id"`
	Sort        int64 `json:"sort"`
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) SetCategoryPlace(ctx context.Context, arg SetCategoryPlaceParams) error {
	_, err := q.db.ExecContext(ctx, setCategoryPlace,
		arg.GroupID,
		arg.Sort,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const setTransactionAICategory = `-- name: SetTransactionAICategory :exec
UPDATE transactions SET category_id = ?, category_source = 'ai', needs_review = ?, ai_cat_tried = 1
WHERE id = ? AND household_id = ? AND category_id IS NULL
`

type SetTransactionAICategoryParams struct {
	CategoryID  sql.NullInt64 `json:"category_id"`
	NeedsReview int64         `json:"needs_review"`
	ID          int64         `json:"id"`
	HouseholdID int64         `json:"household_id"`
}

func (q *Queries) SetTransactionAICategory(ctx context.Context, arg SetTransactionAICategoryParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionAICategory,
		arg.CategoryID,
		arg.NeedsReview,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const setTransactionAuto = `-- name: SetTransactionAuto :exec
UPDATE transactions SET merchant_id = ?, category_id = ?, category_source = ?, needs_review = ?, hidden = ?
WHERE id = ?
`

type SetTransactionAutoParams struct {
	MerchantID     sql.NullInt64 `json:"merchant_id"`
	CategoryID     sql.NullInt64 `json:"category_id"`
	CategorySource string        `json:"category_source"`
	NeedsReview    int64         `json:"needs_review"`
	Hidden         int64         `json:"hidden"`
	ID             int64         `json:"id"`
}

func (q *Queries) SetTransactionAuto(ctx context.Context, arg SetTransactionAutoParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionAuto,
		arg.MerchantID,
		arg.CategoryID,
		arg.CategorySource,
		arg.NeedsReview,
		arg.Hidden,
		arg.ID,
	)
	return err
}

const setTransactionOwner = `-- name: SetTransactionOwner :exec
UPDATE transactions SET owner_user_id = ? WHERE id = ? AND household_id = ?
`

type SetTransactionOwnerParams struct {
	OwnerUserID sql.NullInt64 `json:"owner_user_id"`
	ID          int64         `json:"id"`
	HouseholdID int64         `json:"household_id"`
}

func (q *Queries) SetTransactionOwner(ctx context.Context, arg SetTransactionOwnerParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionOwner, arg.OwnerUserID, arg.ID, arg.HouseholdID)
	return err
}

const unlinkTransaction = `-- name: UnlinkTransaction :exec
UPDATE transactions SET linked_txn_id = NULL, linked_at = NULL WHERE id = ?
`

func (q *Queries) UnlinkTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unlinkTransaction, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = ?, icon = ? WHERE id = ? AND household_id = ?
`

type UpdateCategoryParams struct {
	Name        string `json:"name"`
	Icon        string `json:"icon"`
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Icon,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const updateRule = `-- name: UpdateRule :exec
UPDATE rules SET priority = ?, match_field = ?, match_op = ?, match_value = ?, account_id = ?,
    amount_min = ?, amount_max = ?, direction = ?, day_min = ?, day_max = ?,
    set_category_id = ?, set_merchant = ?, set_hidden = ?, set_goal_id = ?
WHERE id = ? AND household_id = ?
`

type UpdateRuleParams struct {
	Priority      int64         `json:"priority"`
	MatchField    string        `json:"match_field"`
	MatchOp       string        `json:"match_op"`
	MatchValue    string        `json:"match_value"`
	AccountID     sql.NullInt64 `json:"account_id"`
	AmountMin     sql.NullInt64 `json:"amount_min"`
	AmountMax     sql.NullInt64 `json:"amount_max"`
	Direction     string        `json:"direction"`
	DayMin        sql.NullInt64 `json:"day_min"`
	DayMax        sql.NullInt64 `json:"day_max"`
	SetCategoryID sql.NullInt64 `json:"set_category_id"`
	SetMerchant   string        `json:"set_merchant"`
	SetHidden     int64         `json:"set_hidden"`
	SetGoalID     sql.NullInt64 `json:"set_goal_id"`
	ID            int64         `json:"id"`
	HouseholdID   int64         `json:"household_id"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateRule,
		arg.Priority,
		arg.MatchField,
		arg.MatchOp,
		arg.MatchValue,
		arg.AccountID,
		arg.AmountMin,
		arg.AmountMax,
		arg.Direction,
		arg.DayMin,
		arg.DayMax,
		arg.SetCategoryID,
		arg.SetMerchant,
		arg.SetHidden,
		arg.SetGoalID,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const updateTransactionUser = `-- name: UpdateTransactionUser :exec
UPDATE transactions SET
    date = ?, amount_cents = ?, description = ?, merchant_id = ?, category_id = ?, category_source = ?,
    notes = ?, hidden = ?, needs_review = ?, updated_at = ?
WHERE id = ? AND household_id = ?
`

type UpdateTransactionUserParams struct {
	Date           string        `json:"date"`
	AmountCents    int64         `json:"amount_cents"`
	Description    string        `json:"description"`
	MerchantID     sql.NullInt64 `json:"merchant_id"`
	CategoryID     sql.NullInt64 `json:"category_id"`
	CategorySource string        `json:"category_source"`
	Notes          string        `json:"notes"`
	Hidden         int64         `json:"hidden"`
	NeedsReview    int64         `json:"needs_review"`
	UpdatedAt      int64         `json:"updated_at"`
	ID             int64         `json:"id"`
	HouseholdID    int64         `json:"household_id"`
}

func (q *Queries) UpdateTransactionUser(ctx context.Context, arg UpdateTransactionUserParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionUser,
		arg.Date,
		arg.AmountCents,
		arg.Description,
		arg.MerchantID,
		arg.CategoryID,
		arg.CategorySource,
		arg.Notes,
		arg.Hidden,
		arg.NeedsReview,
		arg.UpdatedAt,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const upsertMerchant = `-- name: UpsertMerchant :one

INSERT INTO merchants (household_id, name, normalized) VALUES (?, ?, ?)
ON CONFLICT (household_id, normalized) DO UPDATE SET normalized = excluded.normalized
RETURNING id, household_id, name, normalized
`

type UpsertMerchantParams struct {
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Normalized  string `json:"normalized"`
}

// ---- merchants ----
func (q *Queries) UpsertMerchant(ctx context.Context, arg UpsertMerchantParams) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, upsertMerchant, arg.HouseholdID, arg.Name, arg.Normalized)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Normalized,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (household_id, name) VALUES (?, ?)
ON CONFLICT (household_id, name) DO UPDATE SET name = excluded.name
RETURNING id, household_id, name, color
`

type UpsertTagParams struct {
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, arg.HouseholdID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Color,
	)
	return i, err
}
