// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wishlist.sql

package db

import (
	"context"
	"database/sql"
)

const addWishlistWanter = `-- name: AddWishlistWanter :exec
INSERT OR IGNORE INTO wishlist_wanters (item_id, user_id) VALUES (?, ?)
`

type AddWishlistWanterParams struct {
	ItemID int64 `json:"item_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddWishlistWanter(ctx context.Context, arg AddWishlistWanterParams) error {
	_, err := q.db.ExecContext(ctx, addWishlistWanter, arg.ItemID, arg.UserID)
	return err
}

const clearWishlistWanters = `-- name: ClearWishlistWanters :exec
DELETE FROM wishlist_wanters WHERE item_id = ?
`

func (q *Queries) ClearWishlistWanters(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, clearWishlistWanters, itemID)
	return err
}

const countOpenWishlistItems = `-- name: CountOpenWishlistItems :one
SELECT COUNT(*) FROM wishlist_items WHERE household_id = ? AND bought_at IS NULL
`

func (q *Queries) CountOpenWishlistItems(ctx context.Context, householdID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenWishlistItems, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWishlistItem = `-- name: CreateWishlistItem :one
INSERT INTO wishlist_items (household_id, title, url, store, price_cents, price_source, price_checked_at,
    image_source_url, stars, saves_money, notes, added_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, household_id, title, url, store, price_cents, price_source, price_checked_at, image_source_url, stars, saves_money, notes, added_by, created_at, bought_at, bought_txn_id
`

type CreateWishlistItemParams struct {
	HouseholdID    int64         `json:"household_id"`
	Title          string        `json:"title"`
	Url            string        `json:"url"`
	Store          string        `json:"store"`
	PriceCents     sql.NullInt64 `json:"price_cents"`
	PriceSource    string        `json:"price_source"`
	PriceCheckedAt sql.NullInt64 `json:"price_checked_at"`
	ImageSourceUrl string        `json:"image_source_url"`
	Stars          int64         `json:"stars"`
	SavesMoney     int64         `json:"saves_money"`
	Notes          string        `json:"notes"`
	AddedBy        sql.NullInt64 `json:"added_by"`
	CreatedAt      int64         `json:"created_at"`
}

func (q *Queries) CreateWishlistItem(ctx context.Context, arg CreateWishlistItemParams) (WishlistItem, error) {
	row := q.db.QueryRowContext(ctx, createWishlistItem,
		arg.HouseholdID,
		arg.Title,
		arg.Url,
		arg.Store,
		arg.PriceCents,
		arg.PriceSource,
		arg.PriceCheckedAt,
		arg.ImageSourceUrl,
		arg.Stars,
		arg.SavesMoney,
		arg.Notes,
		arg.AddedBy,
		arg.CreatedAt,
	)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Url,
		&i.Store,
		&i.PriceCents,
		&i.PriceSource,
		&i.PriceCheckedAt,
		&i.ImageSourceUrl,
		&i.Stars,
		&i.SavesMoney,
		&i.Notes,
		&i.AddedBy,
		&i.CreatedAt,
		&i.BoughtAt,
		&i.BoughtTxnID,
	)
	return i, err
}

const deleteWishlistImage = `-- name: DeleteWishlistImage :exec
DELETE FROM wishlist_images WHERE item_id = ?
`

func (q *Queries) DeleteWishlistImage(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteWishlistImage, itemID)
	return err
}

const deleteWishlistItem = `-- name: DeleteWishlistItem :exec
DELETE FROM wishlist_items WHERE id = ? AND household_id = ?
`

type DeleteWishlistItemParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteWishlistItem(ctx context.Context, arg DeleteWishlistItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteWishlistItem, arg.ID, arg.HouseholdID)
	return err
}

const getWishlistImage = `-- name: GetWishlistImage :one
SELECT i.mime, i.data, i.updated_at FROM wishlist_images i JOIN wishlist_items w ON w.id = i.item_id
WHERE i.item_id = ? AND w.household_id = ?
`

type GetWishlistImageParams struct {
	ItemID      int64 `json:"item_id"`
	HouseholdID int64 `json:"household_id"`
}

type GetWishlistImageRow struct {
	Mime      string `json:"mime"`
	Data      []byte `json:"data"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) GetWishlistImage(ctx context.Context, arg GetWishlistImageParams) (GetWishlistImageRow, error) {
	row := q.db.QueryRowContext(ctx, getWishlistImage, arg.ItemID, arg.HouseholdID)
	var i GetWishlistImageRow
	err := row.Scan(&i.Mime, &i.Data, &i.UpdatedAt)
	return i, err
}

const getWishlistItem = `-- name: GetWishlistItem :one
SELECT id, household_id, title, url, store, price_cents, price_source, price_checked_at, image_source_url, stars, saves_money, notes, added_by, created_at, bought_at, bought_txn_id FROM wishlist_items WHERE id = ? AND household_id = ?
`

type GetWishlistItemParams struct {
	ID          int64 `json:"id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetWishlistItem(ctx context.Context, arg GetWishlistItemParams) (WishlistItem, error) {
	row := q.db.QueryRowContext(ctx, getWishlistItem, arg.ID, arg.HouseholdID)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Url,
		&i.Store,
		&i.PriceCents,
		&i.PriceSource,
		&i.PriceCheckedAt,
		&i.ImageSourceUrl,
		&i.Stars,
		&i.SavesMoney,
		&i.Notes,
		&i.AddedBy,
		&i.CreatedAt,
		&i.BoughtAt,
		&i.BoughtTxnID,
	)
	return i, err
}

const listWishlistItems = `-- name: ListWishlistItems :many
SELECT w.id, w.household_id, w.title, w.url, w.store, w.price_cents, w.price_source, w.price_checked_at, w.image_source_url, w.stars, w.saves_money, w.notes, w.added_by, w.created_at, w.bought_at, w.bought_txn_id, CAST(COALESCE(i.updated_at, 0) AS INTEGER) AS image_updated_at,
    CAST(COALESCE(t.amount_cents, 0) AS INTEGER) AS txn_amount, CAST(COALESCE(t.date, '') AS TEXT) AS txn_date,
    CAST(COALESCE(m.name, t.description, '') AS TEXT) AS txn_name
FROM wishlist_items w
LEFT JOIN wishlist_images i ON i.item_id = w.id
LEFT JOIN transactions t ON t.id = w.bought_txn_id
LEFT JOIN merchants m ON m.id = t.merchant_id
WHERE w.household_id = ?
ORDER BY w.created_at DESC, w.id DESC
`

type ListWishlistItemsRow struct {
	ID             int64          `json:"id"`
	HouseholdID    int64          `json:"household_id"`
	Title          string         `json:"title"`
	Url            string         `json:"url"`
	Store          string         `json:"store"`
	PriceCents     sql.NullInt64  `json:"price_cents"`
	PriceSource    string         `json:"price_source"`
	PriceCheckedAt sql.NullInt64  `json:"price_checked_at"`
	ImageSourceUrl string         `json:"image_source_url"`
	Stars          int64          `json:"stars"`
	SavesMoney     int64          `json:"saves_money"`
	Notes          string         `json:"notes"`
	AddedBy        sql.NullInt64  `json:"added_by"`
	CreatedAt      int64          `json:"created_at"`
	BoughtAt       sql.NullString `json:"bought_at"`
	BoughtTxnID    sql.NullInt64  `json:"bought_txn_id"`
	ImageUpdatedAt int64          `json:"image_updated_at"`
	TxnAmount      int64          `json:"txn_amount"`
	TxnDate        string         `json:"txn_date"`
	TxnName        string         `json:"txn_name"`
}

func (q *Queries) ListWishlistItems(ctx context.Context, householdID int64) ([]ListWishlistItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWishlistItems, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWishlistItemsRow
	for rows.Next() {
		var i ListWishlistItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Title,
			&i.Url,
			&i.Store,
			&i.PriceCents,
			&i.PriceSource,
			&i.PriceCheckedAt,
			&i.ImageSourceUrl,
			&i.Stars,
			&i.SavesMoney,
			&i.Notes,
			&i.AddedBy,
			&i.CreatedAt,
			&i.BoughtAt,
			&i.BoughtTxnID,
			&i.ImageUpdatedAt,
			&i.TxnAmount,
			&i.TxnDate,
			&i.TxnName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishlistWanters = `-- name: ListWishlistWanters :many
SELECT ww.item_id, ww.user_id FROM wishlist_wanters ww
JOIN wishlist_items w ON w.id = ww.item_id
WHERE w.household_id = ?
ORDER BY ww.item_id, ww.user_id
`

func (q *Queries) ListWishlistWanters(ctx context.Context, householdID int64) ([]WishlistWanter, error) {
	rows, err := q.db.QueryContext(ctx, listWishlistWanters, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WishlistWanter
	for rows.Next() {
		var i WishlistWanter
		if err := rows.Scan(&i.ItemID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWishlistBought = `-- name: SetWishlistBought :exec
UPDATE wishlist_items SET bought_at = ?, bought_txn_id = ? WHERE id = ? AND household_id = ?
`

type SetWishlistBoughtParams struct {
	BoughtAt    sql.NullString `json:"bought_at"`
	BoughtTxnID sql.NullInt64  `json:"bought_txn_id"`
	ID          int64          `json:"id"`
	HouseholdID int64          `json:"household_id"`
}

func (q *Queries) SetWishlistBought(ctx context.Context, arg SetWishlistBoughtParams) error {
	_, err := q.db.ExecContext(ctx, setWishlistBought,
		arg.BoughtAt,
		arg.BoughtTxnID,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}

const setWishlistImage = `-- name: SetWishlistImage :exec
INSERT INTO wishlist_images (item_id, mime, data, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT (item_id) DO UPDATE SET mime = excluded.mime, data = excluded.data, updated_at = excluded.updated_at
`

type SetWishlistImageParams struct {
	ItemID    int64  `json:"item_id"`
	Mime      string `json:"mime"`
	Data      []byte `json:"data"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetWishlistImage(ctx context.Context, arg SetWishlistImageParams) error {
	_, err := q.db.ExecContext(ctx, setWishlistImage,
		arg.ItemID,
		arg.Mime,
		arg.Data,
		arg.UpdatedAt,
	)
	return err
}

const updateWishlistItem = `-- name: UpdateWishlistItem :exec
UPDATE wishlist_items SET title = ?, url = ?, store = ?, price_cents = ?, price_source = ?, price_checked_at = ?,
    image_source_url = ?, stars = ?, saves_money = ?, notes = ?
WHERE id = ? AND household_id = ?
`

type UpdateWishlistItemParams struct {
	Title          string        `json:"title"`
	Url            string        `json:"url"`
	Store          string        `json:"store"`
	PriceCents     sql.NullInt64 `json:"price_cents"`
	PriceSource    string        `json:"price_source"`
	PriceCheckedAt sql.NullInt64 `json:"price_checked_at"`
	ImageSourceUrl string        `json:"image_source_url"`
	Stars          int64         `json:"stars"`
	SavesMoney     int64         `json:"saves_money"`
	Notes          string        `json:"notes"`
	ID             int64         `json:"id"`
	HouseholdID    int64         `json:"household_id"`
}

func (q *Queries) UpdateWishlistItem(ctx context.Context, arg UpdateWishlistItemParams) error {
	_, err := q.db.ExecContext(ctx, updateWishlistItem,
		arg.Title,
		arg.Url,
		arg.Store,
		arg.PriceCents,
		arg.PriceSource,
		arg.PriceCheckedAt,
		arg.ImageSourceUrl,
		arg.Stars,
		arg.SavesMoney,
		arg.Notes,
		arg.ID,
		arg.HouseholdID,
	)
	return err
}
